### ISSUE TITLE
Tablature no longer working?

### ISSUE THREAD

**Issue by gramster** [Abjad/abjad#1038]
This used to work with an earlier version of Abjad (2.16) back in 2016:

    duration = abjad.Duration(1, 4)
    notes = [abjad.Note(pitch, duration) for pitch in range(8)]
    staff = abjad.Staff(notes, context_name='TabStaff')

context\_name seems to be gone in 3.0.0, so I'm trying:

    duration = abjad.Duration(1, 4)
    notes = [abjad.Note(pitch, duration) for pitch in range(8)]
    staff = abjad.Staff(notes, lilypond_type='TabStaff')

but I get:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-e2cb7c180bb3> in <module>()
----> 1 staff = abjad.Staff(notes, lilypond_type='TabStaff')
      2 show(staff)

~/anaconda/lib/python3.6/site-packages/abjad/core/Staff.py in __init__(self, components, lilypond_type, is_simultaneous, name)
     95             lilypond_type=lilypond_type,
     96             is_simultaneous=is_simultaneous,
---> 97             name=name,
     98             )

~/anaconda/lib/python3.6/site-packages/abjad/core/Context.py in __init__(self, components, lilypond_type, is_simultaneous, name)
     81             is_simultaneous=is_simultaneous,
     82             components=components,
---> 83             name=name,
     84             )
     85 

~/anaconda/lib/python3.6/site-packages/abjad/core/Container.py in __init__(self, components, identifier, is_simultaneous, name)
    178         self._named_children: dict = {}
    179         self._is_simultaneous = None
--> 180         self._initialize_components(components)
    181         self.identifier = identifier
    182         self.is_simultaneous = is_simultaneous

~/anaconda/lib/python3.6/site-packages/abjad/core/Container.py in _initialize_components(self, components)
    799             message = 'can not initialize container from {!r}.'
    800             message = message.format(components)
--> 801             raise TypeError(message)
    802 
    803     def _is_one_of_my_first_leaves(self, leaf):

TypeError: can not initialize container from [Note("c'4"), Note("cs'4"), Note("d'4"), Note("ef'4"), Note("e'4"), Note("f'4"), Note("fs'4"), Note("g'4")].
```

This seems like a bug to me, or maybe I'm doing something wrong; the docs aren't helpful as they don't mention tablature at all.

**Comment by trevorbaca** [comment]
@gramster your example works fine for me in Abjad 3.0:

```
duration = abjad.Duration(1, 4)                                                 
notes = [abjad.Note(pitch, duration) for pitch in range(8)]                     
staff = abjad.Staff(notes, lilypond_type='TabStaff')                            
abjad.f(staff)                                                                  
\new TabStaff
{
    c'4
    cs'4
    d'4
    ef'4
    e'4
    f'4
    fs'4
    g'4
}
```

Actually, I'm working out of the Abjad mainline, which will soon become Abjad 3.1. But everything in your example looks fine for 3.0: the correct change is `lilypond_type` just like you've done.

Looks like you're running Abjad in iPython: can you try the example at a vanilla Python prompt (no iPython) so we can see if it's an iPython interaction?

**Comment by gramster** [comment]
My repro steps were incorrect. I found the problem. I was reusing notes. What I actually had in my notebook was:

```
duration = abjad.Duration(1, 4)
notes = [abjad.Note(pitch, duration) for pitch in range(8)]
staff = abjad.Staff(notes)
show(staff)
```

followed by:

```
staff = abjad.Staff(notes, context_name='TabStaff')
show(staff)
```

It seems that creating a Staff from a list of Notes has side-effects that affect the Notes and they cannot be reused like this.

**Comment by trevorbaca** [comment]
Right! The constraint there is that notes, rests, chords (and all the other score components: tuplets, voices, staves, scores) can be held in *only one* container at at time. So everything is good in the last example when notes are inserted into a staff *the first time*; but the attempt to insert already-housed notes into a (new) staff generates the exception shown at initialization time.
