### ISSUE TITLE
add varC to Clef.py

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1047]
at line 167 in Clef.py insert
`'varC': 0,`
at 189
`'varC': 2.75,`
at 297
`'varC': NamedPitch('C4'),`
in 3.0 I had to change the __init__.py file but that doesn't seem to be the case anymore.

**Comment by GregoryREvans** [comment]
Actually the __init__.py change had to do with a different file. Sorry.

**Comment by GregoryREvans** [comment]
Sent pull request.

**Comment by trevorbaca** [comment]
Merged in #1056
