### ISSUE TITLE
Optional Bowings in bowcontact specifier

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1050]
Is there any way of making the up bow and down bow markings optional in the bowcontactspanner? I had a version of this file before spanner removal that eliminated the bow markings so I could use this spanner for ponticello/tasto markings. With the new system without the spanners, I am not certain if its worth creating an entire definition of this.
Is it possible to make the bow markings optional?

**Comment by GregoryREvans** [comment]
@trevorbaca any possibility of this when you next have time?

**Comment by trevorbaca** [comment]
I'll look this afternoon @GregoryREvans.

**Comment by trevorbaca** [comment]
Hey @GregoryREvans it's merged into mail. Just pull in your Abjad clone.
