### ISSUE TITLE
Issue getting logical ties in abjad 3.0

### ISSUE THREAD

**Issue by n-armstrong** [Abjad/abjad#1053]
_get_logical_tie() produces an incorrect result when leaves in a Selection do not have a common root node:

a = Tuplet.from_duration_and_ratio((1,4), (1,1,1)) * 2
a = Selection(a)
a.leaves()[2:4]._attach_tie_to_leaves()  
print(a.leaves()[2]._get_logical_tie())

This breaks code that iterates by logical-ties over e.g. a list of selections produced by a rhythm-maker. The correct logical-tie can't be made because calls to _leaf(n) in _get_logical_tie() return None when parents are traversed.

There are workarounds, of course, but it seems like this should work without having to add the selection contents to a temporary container.

**Comment by trevorbaca** [comment]
Hi @n-armstrong Use `abjad.inspect().logical_tie()` and the other public accessors in Abjad 3.0 and everything works cleanly:
```
tuplet = abjad.Tuplet.from_duration_and_ratio((1, 4), (1, 1, 1))
staff = abjad.Staff(2 * tuplet)
leaves = abjad.select(staff).leaves()
abjad.tie(leaves[2:4])
```

```
abjad.f(staff)
\new Staff
{
    \times 2/3 {
        c'8
        c'8
        c'8
        ~
    }
    \times 2/3 {
        c'8
        c'8
        c'8
    }
}
```

<img width="267" alt="tied-tuplets" src="https://user-images.githubusercontent.com/5804733/62897658-b6cd7780-bd21-11e9-8446-5b8891603641.png">

```
for leaf in leaves:
   leaf, abjad.inspect(leaf).logical_tie()
```

```
(Note("c'8"), LogicalTie([Note("c'8")]))
(Note("c'8"), LogicalTie([Note("c'8")]))
(Note("c'8"), LogicalTie([Note("c'8"), Note("c'8")]))
(Note("c'8"), LogicalTie([Note("c'8"), Note("c'8")]))
(Note("c'8"), LogicalTie([Note("c'8")]))
(Note("c'8"), LogicalTie([Note("c'8")]))
```
