### ISSUE TITLE
Problems with Bartok's Mikrokosmos

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#1059]
Apologies in advance if this is not the best place to report issues with the documentation.

I noticed a couple of problems with the example of [Bartok's _Mikrokosmos_](http://www.abjad.mbrsi.org/literature_examples/bartok.html):

1. the last twelve notes in the bottom staff (i.e. all notes starting with the **_mp_** dynamic) have a slur in the original score but this slur is missing in the given example. The [tree graph](http://www.abjad.mbrsi.org/_images/bartok-wandering-graph.png) in [this page](http://www.abjad.mbrsi.org/core_concepts/lcsi.html#example-2) about Leaf, Container, Spanner, Indicator does show that a slur spanner was intended to be applied to those last notes. 

2. in this example, Abjad was imported into its own namespace using `import abjad` and therefore all functions must include the namespace prefix `abjad.`. Some functions seem to be missing it and the code will not run. The problem is affecting some (but not all) `attach()` functions and all `score()` functions, which should instead be `abjad.attach()` and `abjad.score()`.

**Comment by gilbertohasnofb** [comment]
The second problem concerning the lack of namespace prefix seem to also be present in many other Core Concepts pages.

**Comment by trevorbaca** [comment]
The literature examples (Bartók, Ferneyhough, etc) do tend to drift quite a bit during development cycles!

Fixed now. PR coming next.
