### ISSUE TITLE
Finalize abjad.Tremolo

### ISSUE THREAD

**Issue by timpauli** [Abjad/abjad#1067]
First of all thx for creating abjad. It is of great use.

If you try to run:

```
import abjad

chord = abjad.Chord("<c' cs'>4")
tremolo = abjad.Tremolo(beam_count=2)
abjad.attach(tremolo, chord)
markup = abjad.Markup('bug')
abjad.attach(markup, chord)
abjad.show(chord)
```

lilypond runs into a compilation error.
The lilypond command `\repeat` `tremolo` uses curly brackets for the corresponding chord.
If you move the markup inside the brackets manually it works. (exact positioning depending after which note)

Is there a workarround for this at the moment?

Keep up the good work.

**Comment by trevorbaca** [comment]
Hi @inkeye and thanks for the example.

The `abjad.Tremolo` class is incomplete: I'm changing the name of this thread to "Finalize abjad.Tremolo" as a reminder eventually to finalize the class. The element of trickiness in the implementation comes from the fact that the traditional notation itself is a bit unusual in western notation: each of the notes in a conventional multinote tremolo carries a duration equal to half of what we might expect. That's the element that's not yet modeled in the Abjad class, and the underlying the reason that the other small details (like markup handling) haven't been finalized yet.

In the meantime, you can build the underlying LilyPond notation (with the containerized `\repeat` command) "by hand" in Abjad with something like this:

```
tremolo_container = abjad.Container("c'16 * 2 cs'16 * 2")
markup = abjad.Markup('legg.', direction=abjad.Up)
abjad.attach(markup, tremolo_container[0])
tremolo_literal = abjad.LilyPondLiteral(
    r'\repeat tremolo 2',
    format_slot='before',
    )
abjad.attach(tremolo_literal, tremolo_container)
abjad.f(tremolo_container)
```

The thing that probably needs explaining in that example are the "duration multipliers" applied to each note: these are there to make sure that Abjad understands the notational construct as having the historically received correct duration:

```
>>> abjad.inspect(tremolo_container).duration()
Duration(1, 4)
```

Hope this helps for the moment. Happy composing.
