### ISSUE TITLE
rewrite_meter resets note heads of any notes it changes

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#1077]
The `rewrite_meter` mutation resets all note heads in notes which it changes, but not those which are left untouched. Consider the following example:

```
import abjad

staff = abjad.Staff(r"c'32 d'2.. ~ d'16 e'32")
abjad.mutate(staff[:]).rewrite_meter(abjad.Meter((4, 4))) 
abjad.show(staff)
```
![image](https://user-images.githubusercontent.com/5700795/57197340-07cd1300-6f5e-11e9-8917-e21d827de777.png)

One can then change all note heads using:
```
import abjad

staff = abjad.Staff(r"c'32 d'2.. ~ d'16 e'32")
for leaf in abjad.select(staff).leaves():
    abjad.tweak(leaf.note_head).style = 'harmonic'
abjad.show(staff)    
```
![image](https://user-images.githubusercontent.com/5700795/57197344-17e4f280-6f5e-11e9-96ee-fee47b019182.png)

But if the `rewrite_meter` mutation is applied after the note heads have been altered, the note heads are reset for whatever durations that are affected by the mutation:
```
import abjad

staff = abjad.Staff(r"c'32 d'2.. ~ d'16 e'32")
for leaf in abjad.select(staff).leaves():
    abjad.tweak(leaf.note_head).style = 'harmonic'
abjad.mutate(staff[:]).rewrite_meter(abjad.Meter((4, 4)))
abjad.show(staff)
```
![image](https://user-images.githubusercontent.com/5700795/57197353-3a770b80-6f5e-11e9-8efd-ef0a65f80ee2.png)

**Comment by GregoryREvans** [comment]
@trevorbaca This seems like a pretty understandable and expected behavior to me. Although it would be nice if `rewrite_meter` handled things like preserving changes to rewritten logical ties, I'm not sure that it would be easy to keep this behavior consistent (i.e. articulations vs noteheads vs markups) although a case could be made due to `rewrite_meter`'s preservation of pitch that these other features deserve more attention. `rewrite_meter` has also left some orphaned/unterminated spanners for me in the past. In my opinion, the real solution is fixing the order of operations of creating a score. Rhythm should come into existence first whether or not it is what is conceptualized first or in tandem with other parameters, then is should be rewritten to match meters if desired. Only after this process is it really a good idea to start making changes like pitch and various attachments. I'm still working on how to do this efficiently in my own music, but I think that's the way to go.

**Comment by jefftrevino** [comment]
I think the trade-off here is between flexibility of compositional process and the speed of the rewriting algorithm. `rewrite_meter` is already pretty slow, and checking for and preserving notehead modifications would make it slower still. But it would be more flexible if one could think of notehead modifications both before or after meter rewriting.

**Comment by gilbertohasnofb** [comment]
I see. So let's say I want only the second logical tie in a bar to be altered (for instance, have its noteheads changed to harmonics). Would this code below be a good approach? I am first mutating, then selecting the second logical tie, then iterating through its leaves changing their noteheads:

```
import abjad

staff = abjad.Staff(r"c'32 d'2.. ~ d'16 e'32")

abjad.mutate(staff[:]).rewrite_meter(abjad.Meter((4, 4)))

second_logical_tie = list(abjad.iterate(staff).logical_ties())[1]
for leaf in abjad.select(second_logical_tie).leaves():
    abjad.tweak(leaf.note_head).style = 'harmonic'

abjad.show(staff)
```

**Comment by GregoryREvans** [comment]
@gilbertohasnofb if you happened to want to use timespans as a means of selecting chunks of material from your score to perform operations on (like changing note heads, adding pitches, or anything really) as opposed to slicing, take a look at this file in my evans repo 

https://github.com/GregoryREvans/evans/blob/master/abjad_functions/timespans_as_selectors/testing_Timespans_as_selectors.py

this is a minimal example of how to do such a procedure. Of course there are other comparison methods for the timespans for you to explore. Searching through every logical tie in a score can get pretty slow depending on the density of the piece, so I also modified a file from Josiah's `consort` package. This file `LogicalTieCollection` comes from consort's `TimespanCollection` which is essentially a timespan list that is always sorted and optimized for lookup.

https://github.com/GregoryREvans/evans/blob/master/abjad_functions/timespans_as_selectors/testing_Timespans_as_selectors_with_collection.py

In particularly large examples it should prove to be faster. I haven't totally integrated these processes into my own scores, but I plan to soon.

**Comment by gilbertohasnofb** [comment]
@GregoryREvans Thanks a lot, I will take a look at it!

**Comment by trevorbaca** [comment]
@gilbertohasnofb The approach you came up with in your earlier comment (June 1) is the right way to go: rewrite meter first; then make typographic changes second.

@GregoryREvans Thanks for helping point the way!
