### ISSUE TITLE
Sorting Timespans upon illustration.

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1082]
When invoking `abjad.show()` on an `abjad.TimespanList`, annotated timespans, if sorted by `key='annotation'`, are sorted alphabetically. In this process, the string sorting does not consider human sorting of numbers, therefore a list of voices labeled as `'voice 1', 'voice 2', 'voice 10', 'voice 100'` ends up getting sorted as `'voice 1', 'voice 10', 'voice 100', 'voice 2'`. This issue rarely comes up with other naming conventions, but should maybe still be addressed. I have looked into the illustration protocol in `abjad.TimespanList` but I'm having trouble finding where the sorting for illustration occurs (the order of elements within the list itself is not the same as the order upon illustration). Human sorting of strings with numbers is not an extremely complicated process and I have some code that should be a starting point, but I don't see where the bad sorting actually happens.

**Comment by GregoryREvans** [comment]
Solution is related to the following process
```
import re

def _to_digit(text):
    return int(text) if text.isdigit() else text

def human_sorted_keys(text):
    return [ _to_digit(_) for _ in re.split(r'(\d+)', text) ]

###demo###

alist=[
    "voice 1",
    "voice 17",
    "voice 12",
    "voice 2",
    "voice 29",
    "voice 25",
    ]

alist.sort()

print(alist)

alist.sort(key=human_sorted_keys)

print(alist)

###alternate demo###

anotherlist=[
    "1 Flute",
    "12 Violin",
    "3 Bass",
    ]

anotherlist.sort()

print(anotherlist)

anotherlist.sort(key=human_sorted_keys)

print(anotherlist)
```
now to find where the sorting occurs.

**Comment by trevorbaca** [comment]
@GregoryREvans can you paste in an MWE I can test against?

**Comment by GregoryREvans** [comment]
```python
import abjad

ts_list = abjad.TimespanList()
spans = [abjad.AnnotatedTimespan(start_offset=0, stop_offset=(1, 4), annotation='voice 1'), abjad.AnnotatedTimespan(start_offset=0, stop_offset=(1, 4), annotation='voice 2'), abjad.AnnotatedTimespan(start_offset=0, stop_offset=(1, 4), annotation='voice 10')]
for _ in spans:
    ts_list.append(_)

abjad.show(ts_list, scale=0.5, key='annotation')
```

**Comment by trevorbaca** [comment]
@GregoryREvans ok there's a new `sort_callable=None` keyword you can pass to `abjad.TimespanList.__illustrate__()`. Currently in my development branch.

The updated part of the API entry looks like this:

<img width="618" alt="sort-callable" src="https://user-images.githubusercontent.com/5804733/59805191-2e4cd080-92b6-11e9-910e-c72456dd256d.png">
