### ISSUE TITLE
Reassess automatic Scheme parsing

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1086]
With some recent talk of reconsidering when and where Scheme is automatically parsed, I thought it might be useful compile some of the files that might be affected by a change in this process.

List to come soon.

**Comment by trevorbaca** [comment]
Will wait until after 3.1 release.

**Comment by trevorbaca** [comment]
Checklist starting here:

- [ ] pare down `abjad.LilyPondFormatManager.format_lilypond_value()` to skip string formatting, with the possible exception of known Scheme colors. Seems like one of the hackiest points in the system is figuring out what `format_lilypond_value()` does with Python strings like `"#(ly:make-moment 1 64)"`. These are best just treated as literals, ie, passed through `format_lilypond_value()` without change.

**Comment by trevorbaca** [comment]
Release in Abjad 3.6, when all markup became literal.
