### ISSUE TITLE
Encoding error with save_last_pdf_as

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#1090]
I am running Linux, Abjad 3.0, and Python 3.6 and I am having troubles with `IOManager.save_last_pdf_as()`: it outputs an encoding error and creates an empty pdf file. If I run the code below....:

```
import abjad

staff = abjad.Staff(r"c'4 d'4 e'2")
abjad.show(staff)
abjad.IOManager.save_last_ly_as(r'./foobar.ly')
```

...the file `foobar.ly`does get created in the current path. But if I add the line bellow...:

```abjad.IOManager.save_last_pdf_as(r'./foobar.pdf')```

...I get the following error:

```
Original exception was:
Traceback (most recent call last):
  File "/home/gilberto/Programming/Abjad/47 using IOManager.py", line 11, in <module>
    abjad.IOManager.save_last_pdf_as(r'./foobar.pdf')
  File "/home/gilberto/.local/lib/python3.6/site-packages/abjad/system/IOManager.py", line 781, in save_last_pdf_as
    new.write(''.join(old.readlines()))
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 10: invalid continuation byte
```

**Comment by GregoryREvans** [comment]
Gilberto,
I’ve personally never used IOManager so I don’t have a solution to your direct problem, but depending on what you are trying to achieve, I think you might want to use persist instead: http://abjad.mbrsi.org/api/abjad/system/PersistenceManager.html?highlight=persist#abjad.system.PersistenceManager.PersistenceManager.as_pdf

From your example, I suspect this is what you are trying to do?

**Comment by GregoryREvans** [comment]
@gilbertohasnofb If you are trying to save a pdf of something you already rendered with `abjad.show()` then it looks like `IOManager` may be able to help, but if you look here https://github.com/Abjad/abjad/blob/0addf28d4f9ee7f70191f819b9c681187d39c0f5/abjad/top/show.py#L52 `abjad.show()` is actually just calling `abjad.persist().as_pdf()` under the hood and here https://github.com/Abjad/abjad/blob/0addf28d4f9ee7f70191f819b9c681187d39c0f5/abjad/top/show.py#L58 `IOManager` is being used to open the file. So shortening the code from the following
```python
abjad.show(staff)
abjad.IOManager.save_last_pdf_as(r'./foobar.pdf')
```
to instead be the following
```python
abjad.persist(staff).as_pdf(/home/gilberto/foobar.pdf)
```
should not only work as you expect it to, it is also a slightly more simple process.

**Comment by gilbertohasnofb** [comment]
@GregoryREvans Thank you _so_ much for the reply, using `abjad.persist()` really solved my issue. It actually solves another issue I had which is the fact that the `IOManager` does not have an option to save a midi file elsewhere. And `abjad.persist()` will create the files only in my designated path, not inside my `~/.abjad/output` folder, which is also great for my use.

So now I am using the following code:

```
import abjad

staff = abjad.Staff(r"c'4 d'4 e'2")
abjad.persist(staff).as_pdf(r'./foobar')
abjad.persist(staff).as_midi(r'./foobar')
```

Note that for some reason neither `abjad.persist().as_midi()` nor `abjad.persist().as_pdf()` require the filename to have an extension. In fact, it seems that whatever extension I use gets ignored (for instance, I tried setting the MIDI output to `./foobar.mid` but got lilypond's usual `./foobar.midi` with the extra `i` at the end.

So my personal problem is solved, but the encoding error with `IOManager` still persist so should this issue stay opened?

**Comment by GregoryREvans** [comment]
@gilbertohasnofb Fantastic. Yes let’s leave it open and let @TrevorBaca have a look at this.

**Comment by trevorbaca** [comment]
Hi guys (@gilbertohasnofb, @GregoryREvans). Yep, the error reproduces for me. And Googling gives ...

https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte

... which results in a one-line fix that changes `abjad.IOManager` line 720 from ...
```
            with open(last_pdf_full_name, "r") as old:
```
... to ...
```
            with open(last_pdf_full_name, "r", encoding="ISO-8859-1") as old:
```
... which fixes the problem.

Also, you guys took the right path using `abjad.persist()`. That's a great way to work. Though the `abjad.IOManager` fix is still important.

I'll open a PR and merge into the mainline in a bit. Ticket will close after.
