### ISSUE TITLE
Uprev, make new release, and fix webpage (three issues in one!)

### ISSUE THREAD

**Issue by j5awry** [Abjad/abjad#1124]
Checking PyPi versus Github, I'm seeing marked differences. Propose:

1. uprev _version.py in abjad
2. prepare a release of 3.1 for PyPi
3. fix the homepage: http://www.projectabjad.org  (currently broken with a CPanel response)

Commits show this is still active (awesome!) but PyPi is well behind, and documentation is lost due to the site being down.

**Comment by trevorbaca** [comment]
@j5awry yeah we should've built / released 3.1 almost a year ago!

The code's been quite active in the intervening period, however. Will need until the beginning of October to build.

**Comment by trevorbaca** [comment]
Abjad 3.1 was released in December 2019.
