### ISSUE TITLE
Travis CI error when importing abjad 

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#1126]
I am developing a library which makes use of abjad. Locally, everything is fine when I run my tests with:

 `$ python3.6 -m pytest -v`

But when Travis CI runs its automatic tests, an error happens when importing abjad.

I created a dummy library with an empty function and an empty class just to make sure that this wasn't an error on my side. Besides importing abjad, this library does not use any of its function or classes. There are two tests with two functions, one creating an object from this empty dummy class and another calling an empty dummy function. The dummy code can be seen here: https://github.com/gilbertohasnofb/barfoo

Whenever Travis reaches the `import abjad` line in either of the two test files, it raises a `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`. 

My `setup()` in `setup.py` includes `install_requires=['abjad==3.0.0']`. Locally, I use Abjad 3.0.0 installed via pip, which should match the version that Travis uses.

Any idea what might be happening and why everything is fine locally but broken with Travis?

Here is the full error report:

```
==================================== ERRORS ====================================

______________________ ERROR collecting tests/test_Bar.py ______________________

tests/test_Bar.py:1: in <module>

    import abjad

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/__init__.py:17: in <module>

    from abjad import parser

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/parser/__init__.py:7: in <module>

    from .GuileProxy import GuileProxy

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/parser/GuileProxy.py:2: in <module>

    from abjad import core

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/core/__init__.py:29: in <module>

    from .Mutation import Mutation

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/core/Mutation.py:4: in <module>

    from abjad.meter import Meter

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/meter.py:8: in <module>

    import abjad.rhythmtrees

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/rhythmtrees.py:402: in <module>

    class RhythmTreeContainer(RhythmTreeMixin, uqbar.containers.UniqueTreeContainer):

E   TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

______________________ ERROR collecting tests/test_foo.py ______________________

tests/test_foo.py:1: in <module>

    import abjad

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/__init__.py:17: in <module>

    from abjad import parser

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/parser/__init__.py:7: in <module>

    from .GuileProxy import GuileProxy

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/parser/GuileProxy.py:2: in <module>

    from abjad import core

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/core/__init__.py:29: in <module>

    from .Mutation import Mutation

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/core/Mutation.py:4: in <module>

    from abjad.meter import Meter

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/meter.py:8: in <module>

    import abjad.rhythmtrees

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/abjad/rhythmtrees.py:402: in <module>

    class RhythmTreeContainer(RhythmTreeMixin, uqbar.containers.UniqueTreeContainer):

E   TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!

=========================== 2 error in 0.91 seconds ============================

The command "python -m pytest -v" exited with 2.
cache.2

store build cache

Done. Your build exited with 1.
```

**Comment by kuzmoyev** [comment]
Same issue here on macOS Mojave, with `uqbar-0.4.1`

**Comment by trevorbaca** [comment]
Looking at this initially, I'm not sure what the problem would be. Abjad 3.0.0 is old, however, and I'm always working off of the Abjad mainline. So it may be that uqbar 0.4.1 works only against the newer, mainline Abjad. Not certain, though.

**Comment by gilbertohasnofb** [comment]
The strange thing is that I don't get this error locally on my Linux Mint 18.3 machine. I install all my libraries using pip, so I find it a bit weird that I don't see these errors over here.

**Comment by trevorbaca** [comment]
I'm assuming this ticket is ancient and can be closed, @gilbertohasnofb?

**Comment by gilbertohasnofb** [comment]
Hi @trevorbaca, yes this can be closed, Travis is not reporting any errors with my package any longer. I had forgotten about this issue otherwise I would have closed it before.
