### ISSUE TITLE
tweaks do not survive abjad.mutate().copy()

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1129]
tweaks do not survive abjad.mutate().copy()
```python
import abjad


staff = abjad.Staff("c'4 cs' d' ds'")
abjad.tweak(staff[1].note_head).color = "red"
abjad.tweak(staff[1].note_head).accidental.color = "red"
abjad.show(staff)
```
<img width="196" alt="Screen Shot 2019-09-26 at 5 07 23 PM" src="https://user-images.githubusercontent.com/40587295/65728337-3750f900-e080-11e9-84e2-657b239bbe92.png">

```python
copied_staff = abjad.mutate(staff).copy()
abjad.show(copied_staff)
```
<img width="200" alt="Screen Shot 2019-09-26 at 5 07 32 PM" src="https://user-images.githubusercontent.com/40587295/65728341-3d46da00-e080-11e9-91c2-7db8c5fd802c.png">

**Comment by nivlekp** [comment]
This bug seems to be resolved in Abjad 3.2

The updated syntax should be:

```python
>>> import abjad
>>> staff = abjad.Staff("c'4 cs' d' ds'")
>>> abjad.tweak(staff[1].note_head).color = "red"
>>> abjad.tweak(staff[1].note_head).Accidental.color = "red"
>>> string = abjad.lilypond(staff)
>>> print(string)
\new Staff
{
    c'4
    \tweak Accidental.color #red
    \tweak color #red
    cs'4
    d'4
    ds'4
}
>>> copied_staff = abjad.mutate.copy(staff)
>>> string = abjad.lilypond(staff)
>>> print(string)
\new Staff
{
    c'4
    \tweak Accidental.color #red
    \tweak color #red
    cs'4
    d'4
    ds'4
}
```

**Comment by GregoryREvans** [comment]
Hi @nivlekp and thanks for looking at this. It seems like you're correct! Except for the following. On my machine (just pulled from main 2 minutes ago) this bug seems to persist
```python
>>> import abjad
>>> staff = abjad.Staff("c'4 cs'4 d'4 ef'4")
>>> abjad.tweak(staff[0].note_head).color = "red"
>>> abjad.f(staff)
\new Staff
{
    \tweak color #red
    c'4
    cs'4
    d'4
    ef'4
}
>>> copy = abjad.mutate.copy(staff)
>>> abjad.f(copy)
\new Staff
{
    c'4
    cs'4
    d'4
    ef'4
}
```
I haven't looked at this at all myself, but maybe there's a difference between what `abjad.lilypond()` returns and what `abjad.f()` returns?

**Comment by GregoryREvans** [comment]
I'd like to add an addendum.  When calling `abjad.show()` on a copied staff, tweaks are missing.

**Comment by nivlekp** [comment]
Hi @GregoryREvans,

You are absolutely right!
My bad, in my code snippet, the second time when I called `abjad.lilypond()`, the argument should be `copied_staff` instead of `staff`.
I'll take a further look at this.

**Comment by trevorbaca** [comment]
Done by @nivlekp in Abjad 3.3.
