### ISSUE TITLE
Stem length

### ISSUE THREAD

**Issue by timpauli** [Abjad/abjad#1160]
Hi,

with `abjad.override(score).stem.length = 6` you can shorten all of your stems.
But when you do it like that all the stems of beamed notes keep their normal length.

I tried it with `abjad.override(score).stem.details.beamed_lengths` as documented for  [Lilypond](http://lilypond.org/doc/v2.18/Documentation/internals/stem) but abjad throws an error there.

Is there a way to shorten also beamed stems?

Thanks a lot
Best
Tim

**Comment by trevorbaca** [comment]
Hi Tim (@timpauli). You can use double-underscore sequences to cause Abjad to parse LilyPond property paths that are "long":
```
staff = abjad.Staff("c'16 d' e' f' g'4 a' b'")                                                                              
abjad.override(staff).stem.details__beamed_lengths = [5.26, 5.5, 5.6]
```

```
abjad.f(staff)                                                                            
\new Staff
\with
{
    \override Stem.details.beamed-lengths = #'(5.26 5.5 5.6)
}
{
    c'16
    d'16
    e'16
    f'16
    g'4
    a'4
    b'4
}
```

<img width="359" alt="Screen Shot 2020-03-03 at 3 09 43 PM" src="https://user-images.githubusercontent.com/5804733/75815229-0a0c2380-5d61-11ea-8ed5-8d5f80075c7e.png">

(Note that LilyPond wants you to use a LIST of values for `Stem.details.beamed-lengths`. If you use an integer, it will appear that LilyPond ignores the setting.)
