### ISSUE TITLE
iterating measures

### ISSUE THREAD

**Issue by gesellkammer** [Abjad/abjad#1161]
Hi. I am updating a project which used abjad 3.0 to work with 3.1. I see that Measure was removed. In the documentation I did not find a way to iterate the content of a Staff by measures. There is a reference in the 3.1 release but there seems to be something missing. 

```python
>>> for group in groups:
...     print(group)
Selection([Note("f''4."), Note("gf''4."), Note("f''4.")])
Selection([Note("gf''4."), Note("f''4."), Note("c'''4.")])
Selection([Note("c'''4."), Note("a''4."), Note("fs''4.")])
```

Where does this `groups` come from?

Thanks!

**Comment by trevorbaca** [comment]
Hi Eduardo (@gesellkammer)! Use the `group_by_measure()` method implemented on the `abjad.Selection` class. The easiest way to make an `abjad.Selection` is with the `abjad.select()` factory function.

Here's the relevant place in the docs:

https://abjad.github.io/api/abjad/core/Selection.html#abjad.core.Selection.Selection.group_by_measure

Example looks like this:

<img width="692" alt="Screen Shot 2020-03-03 at 3 15 38 PM" src="https://user-images.githubusercontent.com/5804733/75815720-e695a880-5d61-11ea-9e66-fb42e14e31c1.png">

The example above selects leaves (first) and groups leaves into measures (second).

But note that you can select whatever you want -- chords only, tuplets, whatever -- and then group those into measures, too.
