### ISSUE TITLE
How to spell according to key signature?

### ISSUE THREAD

**Issue by Efroymson** [Abjad/abjad#1171]
Using numeric notes to refer to keys doesn't always render correctly.  The default rendering of note 3 for example is E flat.  Even if C# major is specified, the note will still be rendered as an Eb rather than the correct D#.  Some keys by happenstance render correctly, but among those that do not is F# major, and you can see the result of this bug in the Ligeti Desorde rendering in your example, where there are several stray flat markings in the Bass Clef.
https://abjad.github.io/literature_examples/ligeti.html

The python code below generates a set of scales in several keys, some of which are ok.  C# is pessimal, every note except the root is decorated with an unnecessary accidental.

I've just begun using Abjad, so perhaps this is user error, but if so I humbly suggest it is a documentation bug, since I can't find any reference to how to deal with this.  Lilypond is apparently aggressive in demanding a # or flat signifier on every "black key" note, perhaps that is the source of the problem? 

`
import abjad

def majorM (listy):
    majorArr = [0,2,4,5,7,9,11,12,14,16,17,19,21,23,24,26]
    return list (map ((lambda x:  majorArr[x]), listy))

def runOfScales():
    notes = []
    for i in range(12):
        for n in (majorM(range(8))):
            notes.append(abjad.Note(n+i,  abjad.Duration(1, 4)))
            if i > 0 and n == 0:
                key_signature = abjad.KeySignature(i, "major")
                abjad.attach(key_signature, notes[len(notes)-1])

    container = abjad.Container(notes)
    abjad.show(container)
    
runOfScales()
`

**Comment by Efroymson** [comment]
I feel a little bad about filing a bug report as my first interaction with the devs on this terrific project.  It is a little as if I crashed party, then complained that there was not enough pepper in the pâté, and the Zinfandel ran out before I could get a second glass.

So let me say that I am very happy to discover Abjad!  Thank you for making it available.

**Comment by Efroymson** [comment]
I haven't yet worked out where in the code this is implemented, but it seems to me that the problem is in the Default accidental spelling as indicated at the bottom of this page:
http://abjad.mbrsi.org/appendices/pitch_conventions.html

To correctly deal with traditional key signatures the code should look for an enharmonic in the following order of priority:

1) doesn't require an accidental because one already is in the key signature
2) Can use a natural
3) Can use the same sharp or flat as is present in the key signature

I found a place where the defaults are output (in abjad/abjad/pitch/NamedPitchClass.py) but it is not clear to me how to determine what the active key signature is, and if this is the correct place to add this?  Or it should be done elsewhere in the code?

**Comment by trevorbaca** [comment]
Hi @Efroymson! Wow, sorry it's taken so long to go all the way back to your thread from April, but better late than never!

First, welcome to Abjad!

Second, the "Désordre" docs were, indeed, VERY out of date. I'm actually just now updating them (this week) for the first time in 10 years.

Third, I hope you found some good Zin and pâté for the recent holidays ;)

As to the substance of your question: I think there's no way -- without knowing exact harmonic function -- to know how pitch 3 (say) should be spelled in a traditional key signature, right?

Neither Eb nor D# is included in C major. But if we're spelling a minor tonic triad (borrowed from c minor) then 3 would be spelled as Eb. And if we're tonicizing E natural with a diminished triad (functioning as viio/III) then 3 would be spelled as D#, right?

So this is why Abjad ignores key signature when spelling numeric pitches: it's only possible to do correctly with exact harmonic function included as input.

Put another way, working with numeric pitches is part of the inheritance of 20th-century pitch-class theory (in turn deriving from Schoenberg). So working with numbered pitches kinda means that you're not planning on spelling your music according to key signature.

Note, though, that you can just type LilyPond pitch names directly into Abjad! Which maybe you didn't know back in April when you first started working with the system:
```
voice = abjad.Voice("a b cs' d' e' fs' gs' a''")
key_signature = abjad.KeySignature("a", "major")
abjad.attach(key_signature, voice[0])
```

Hope this helps!

**Comment by Efroymson** [comment]
Trevor,

Thanks for getting back to me on this!  I understand your point, and it is true that C major gives no indication whatsoever about how to spell enharmonic notes.  I think, however, that a case can be made that other key signatures do give such a clue, and one could argue (perhaps!) that that is in fact the purpose of a key signature.  

Consider F major.  Is there any question but that the flat on B is telling you that pitch 10 is a B flat?  It is true that to go back to your example, pitch 3 is still ambiguous, but perhaps the heuristic of using flats if there are flats in the key signature and sharps if sharps is a better solution than just defaulting to flats, as abjad seems to do now. 

For one thing, that simple heuristic would fix the problems in the Desorde rendering!  It would indeed make all the key signatures render more cleanly, without extra accidentals. And of course, if for whatever reason a composer wished to specify an accidental other than the default, that would be possible, as you indicate.

I am even willing to try to implement this feature in the code, I went looking for the right place some months back when I first reported it, but I could not find the right spot.  Perhaps you can point me to the place?

Thanks,

Robert

PS I have, for some reason, a desire to use key signatures in a somewhat unorthodox fashion, i.e. to write something that "looks like" F major, but the B flat is actually a flatted 7th, or leading tone, not an A sharp, which would have a different harmonic meaning.  I understand that using key signatures for other than major and minor is a thing that went out of fashion about 1720, but maybe its time is coming back?

**Comment by trevorbaca** [comment]
Hi Robert (@Efroymson) why are you using numbers for pitches? You know you can just type note names into Abjad, right?

**Comment by Efroymson** [comment]
Oh!  Of course I did not answer that.  I like using numbers because I can manipulate them more easily.  My musical training is rather limited, so it is easier for me to think of adding or subtracting rather than transposing, and if I use other transformations (permutations, inversions, etc) it is easier for me to "see" what I am doing with numbers rather than note names.

Another example: I once wrote a sequencer based on a weakened version of a WWII encryption machine (the M-209, not the Enigma).  It used varying sets of additions and subtractions.  I used it to play live, so I don't know exactly what the sequences would have looked like if I had made them into sheet music, but I am pretty sure I would have wanted it to work in the way I described above, the values were chosen to "make sense" in an ordinary scale.

**Comment by trevorbaca** [comment]
I see. Then make a number-to-name Python dictionary that captures the heuristics you want to experiment with:
```
number_to_name = {0: "c", 1: "cs", 2: "d", 3: "ds", ..., 10: "bf", 11: "b"}
```
Play around with different dictionaries. Each one is a model that will let you test your heuristics.

**Comment by Efroymson** [comment]
Dictionaries are useful of course, but in this case they are a workaround for a bug.  You point out that note 3 in C major is ambiguous, so we can't know whether it is Eb or D#.  Which of course is true! But note 0 is actually in C major, and we know for sure that it is spelled C, not B#.  That is (part of) what it means to be writing in the key of C. I would argue that at the very least, abjad should correctly spell numeric notes that are actually in the current key signature, because there is no real ambiguity.

I must apologize, my code in the original comment got scrambled, and all the leading white space was crushed, which of course renders it very poor Python.  I will try to include an improved version at the bottom of this comment.  If you run the code you will get a sheet of "music" with 18 keys represented.  Each key has a run of notes, all notes that are in that key, starting from one note below the root, up to the root, and back down again to the root.

Note that some keys render "correctly", that is without extraneous sharps, flats, or naturals.  Those keys are C, D, Eb, F, G and Bb.  All the others render poorly, some extremely poorly, such as C#, where in this rendering every note in the ascending portion has an extraneous marking!  It is interesting that sometimes the same note is spelled differently in the descending run than in the ascending, but that is clearly because of the effect of a previous accidental.

At the bottom of the sheet are six "extra" keys, each an enharmonic equivalent of one of the first twelve, included for near completeness.  At first I left out B#, since it is a rather absurd key, but the way abjad renders a scale in it is pretty hilarious!  A#, D#, and E# are still missing, but probably unnecessary.

The pdf output is also attached below, if I GitHub is working as I expect.

'''python
import abjad

majorArr2  = [-1,0,2,4,5,7,9,11,12,11,9,7,5,4,2,0]

def runOfScales():
    notes = []
    for i in range(12):
        for n in majorArr2:
            notes.append(abjad.Note(n+i,  abjad.Duration(1, 8)))
            if n == -1:
                key_signature = abjad.KeySignature(i, "major")
                abjad.attach(key_signature, notes[len(notes)-1])
                
    #add missing major keys
    # Db, Gb, Cb, Fb, G#, B#
    enhar = [1,6,-1,4,8,0]
    enhark = ["df", "gf", "cf", "ff", "gs","bs"] 
    for j in range (len(enhar)):
        i = enhar[j]
        k = enhark [j]
        for n in majorArr2:
            notes.append(abjad.Note(n+i,  abjad.Duration(1, 8)))
            if n == -1:
                key_signature = abjad.KeySignature(k, "major")
                abjad.attach(key_signature, notes[len(notes)-1])

    container = abjad.Container(notes)
    abjad.show(container)
    
runOfScales()
'''

[18keys.pdf](https://github.com/Abjad/abjad/files/5857968/18keys.pdf)

**Comment by Efroymson** [comment]
I can't seem to get that code to render correctly, so I will try attaching it.
[runof2.py.txt](https://github.com/Abjad/abjad/files/5858012/runof2.py.txt)

**Comment by trevorbaca** [comment]
Please see ...

https://abjad.github.io/examples/scales_diatonic.html

... for much better ways of dealing with diatonic scales.
