### ISSUE TITLE
Change the playback of instrument sound from Abjad

### ISSUE THREAD

**Issue by JamesGreenaway** [Abjad/abjad#1205]
Adding ` \new Staff \with {midiInstrument = "cello"} {` to a lilypond file will change the playback sound of the instrument to sound like a cello. Is this possible to do this with Abjad? Specifically, I would like to instruct the ipython abjad extension to run using different instrument soundfont sounds.

**Comment by maribote** [comment]
Hi James,
what I do is to simply use a literal:
```
literal = abjad.LilyPondLiteral('\set Staff.midiInstrument = "cello"', "before")
abjad.attach(literal, cello[0])
```
This can also be done mid-score when changing an instrument.

Cheers,
Martín.

**Comment by trevorbaca** [comment]
A literal is a good way to go.

You can also use `abjad.setting()` to put stuff in a `\with` block:
```
staff = abjad.Staff("c'4")
abjad.setting(staff).midiInstrument = '#"cello"'
abjad.f(staff)
\new Staff
\with
{
    midiInstrument = #"cello"
}
{
    c'4
}
```
