### ISSUE TITLE
Potential bug in _fuse_leaves_by_immediate_parent

### ISSUE THREAD

**Issue by nivlekp** [Abjad/abjad#1245]
When there is a grace note (or potentially other "attachments", e.g. time signature, metronome mark, as well?) attached to the first note of a logical tie that Abjad is trying to fuse, the grace note might appear in the last note, which it probably should not.

Here is an example:

```
import abjad

voice = abjad.Voice(r"\grace { b'16 } c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
logical_tie = abjad.get.logical_tie(voice[0])
result = abjad.mutate._fuse_leaves_by_immediate_parent(logical_tie)

print(abjad.lilypond(voice))
```

which produce:
```
\new Voice
{
    \grace {
        b'16
    }
    c'4
    ~
    \grace {
        b'16
    }
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

If this is indeed a bug, I might try to go ahead and fix it.

**Comment by nivlekp** [comment]
Here is another example with a metronome mark.

```
import abjad

voice = abjad.Voice(r"\tempo 4 = 120 c'16 ~ c'16 ~ c'16 ~ c'16 ~ c'16 r16 r16 r16 r4 r4")
logical_tie = abjad.get.logical_tie(voice[0])
result = abjad.mutate._fuse_leaves_by_immediate_parent(logical_tie)

print(abjad.lilypond(voice))
```

which produces:
```
\new Voice
{
    \tempo 4=120
    c'4
    ~
    \tempo 4=120
    c'16
    r16
    r16
    r16
    r4
    r4
}
```

**Comment by trevorbaca** [comment]
Excellent catch. This is definitely bug, and these two examples are super helpful.

I see your fix in the PR, and I think it will work! Will respond there after I finish some extra tests. Thanks for this one @nivlekp
