### ISSUE TITLE
\fermataMarkup

### ISSUE THREAD

**Issue by maribote** [Abjad/abjad#1255]
This is an enhancement request. 

We can use `abjad.Fermata()` for fermatas attached to notes and rests but not when attaching them to MultiMeasure rests. The current solution for MM rests is to attach `abjad.LilyPondLiteral(r"\fermataMarkup", "after")`. This is not ideal if the MultiMeasure rest is eventually changed to something else. This is certainly an issue of Lilypond and not of abjad, since changing a MultiMeasure rest to something else in Lilypond also requires the user to manually change the `\fermataMarkup` command to `\fermata`. It would be great if `abjad.Fermata()` could do that automatically, i.e., if it could have an internal condition where MultiMeasure rests get the corresponding Lilypond command when using `abjad.attach()`.

**Comment by maribote** [comment]
For the record, I just solved this for myself. I suppose `abjad.attach` is the one who should be taught about this stuff.

```python
def attach_fermata(client, command="fermata"):
    if isinstance(client, abjad.MultimeasureRest):
        if command == "fermata":
            literal = abjad.LilyPondLiteral(r"\fermataMarkup")
            abjad.attach(literal, client)
        if command == "shortfermata":
            markup = abjad.Markup.musicglyph("scripts.ushortfermata")
            abjad.attach(markup, client)
        if command == "longfermata":
            markup = abjad.Markup.musicglyph("scripts.ulongfermata")
            abjad.attach(markup, client)
        if command == "verylongfermata":
            markup = abjad.Markup.musicglyph("scripts.uverylongfermata")
            abjad.attach(markup, client)
    else:
        abjad.attach(abjad.Fermata(command=command), client)
```

**Comment by trevorbaca** [comment]
Very nice @maribote! The other place I always have to remember this LilyPond distinction (between markup and fermata markup) is when I want to override the corresponding LilyPond grob. It made me go crazy a couple of times wondering why `\override TextScript.color = #red` didn't work for fermata markup!
