### ISSUE TITLE
Release Jupyter notebook extension together with 3.2

### ISSUE THREAD

**Issue by SG60** [Abjad/abjad#1272]
Hi, I just tried to install abjad in a venv and am getting the following error. Do you know what the issue might be?

```
pip install "abjad[ipython]"

Collecting abjad[ipython]
  Using cached Abjad-3.1.tar.gz (654 kB)
Requirement already satisfied: ply in ./.venv/lib/python3.9/site-packages (from abjad[ipython]) (3.11)
Requirement already satisfied: roman in ./.venv/lib/python3.9/site-packages (from abjad[ipython]) (3.3)
Requirement already satisfied: uqbar<0.5.0,>=0.4.4 in ./.venv/lib/python3.9/site-packages (from abjad[ipython]) (0.4.8)
ERROR: Could not find a version that satisfies the requirement abjad-ext-ipython<3.2.0,>=3.1.0 (from abjad[ipython]) (from versions: 3.0.0a0, 3.0.0a1, 3.0.0)
ERROR: No matching distribution found for abjad-ext-ipython<3.2.0,>=3.1.0 (from abjad[ipython])
```

It works fine when I don't try and install the ipython extension, however. This is on Arch Linux running under WSL.

**Comment by nivlekp** [comment]
Hi @SG60, the ipython extension was not released as part of the 3.1 package, hence the error. Since the current syntax of the extension is only compatible with abjad 3.2, I would suggest cloning the ipython [repository](https://github.com/Abjad/abjad-ext-ipython) and the abjad [repository](https://github.com/Abjad/abjad) and installing both of them using pip install.

Hope this helps.

**Comment by trevorbaca** [comment]
Hi @SG60, yep @nivlekp is right!

Also, the Abjad 3.2 release is coming next week, and I'll release the updated IPython extension at the same time. Then the dependencies will be synched up again.

(In some release of Abjad even later this year I'm going to move the IPython extension back into the Abjad repository proper. But for now, install as @nivlekp recommends.)

**Comment by SG60** [comment]
Ah, that explains it. Thanks! Got it all working now.
