### ISSUE TITLE
Typing Scheme values in 3.3?

### ISSUE THREAD

**Issue by MarcTheSpark** [Abjad/abjad#1331]
If I run the following

```
import abjad
staff = abjad.Staff("c'4 cs'4 d'4 ef'4")
abjad.tweak(staff[0].note_head).style = "diamond"
print(abjad.lilypond(staff))
```
I get:

```
\new Staff
{
    \tweak style diamond
    c'4
    cs'4
    d'4
    ef'4
}
```

It should be `#'diamond`, no? Unless I'm now supposed to write:

```
abjad.tweak(staff[0].note_head).style = "#'diamond"
```

**Comment by MarcTheSpark** [comment]
Actually, looking over the release notes, I guess I am supposed to write the literal scheme now. Is that the idea?

**Comment by nivlekp** [comment]
@MarcTheSpark, thanks for reading the release note. That's right, we are trying to encourage the users to write the literal scheme. Another example would be instead of `True` and `False`, the user would have to write `##t` and `##f`.

**Comment by trevorbaca** [comment]
Hi @MarcTheSpark, yes you've got it! (And hi @nivlekp!) I know it's a bit of a pain making the transition, but an easy way to think about the new way of typing the value of the Scheme setting (like `"#'diamond"` or `"#red"` or `"#(ly:make-moment 1 16)"`) is just start with the `#` and then type exactly what you would type in LilyPond, enclosed in a Python string. (In other words, type the complete Scheme expression, beginning with the `#` symbol that LilyPond uses to signal the beginning of an embedded Scheme expression.)

By contrast, the older way of typing things (like `"diamond"`, `"red"`, `abjad.SchemeMoment((1, 16))`) was somewhat trying to "hide" Scheme expressions from Abjad users: `"diamond"` and `"red"` are just Python strings and so Abjad users' mental model probably conflated `"diamond"` and `"red"` over time, even though these are different constructs in LilyPond underlyingly: `"#'diamond"` is a Scheme symbol whereas `#red` is a Scheme color constant (which, I think, is actually just a Scheme function call), etc etc.

In other words, the older way of typing Scheme values in Abjad leaned towards the implicit; the new way of typing Scheme values in Abjad just uses LilyPond's syntax exactly, hopefully meaning that Abjad users will never again have to "guess" whether Abjad will prefix `#` or `#'` or a `##` to user input behind the scenes.

Also, it's great that you're using tweaks (as opposed to `\once \override` for everything). I can't believe how much my own code cleaned up after I started moving from many years of using only `\once \override` to instead using `\tweak` on every LilyPond grob that allows it.

A bit of a development roadmap for the changes I'm slowly working into Abjad this year:

Abjad 3.2: January 2021 [done]
Abjad 3.3: 1 March: [done]
Abjad 3.4: 1 May
Abjad 3.5: 1 July
Abjad 3.6: 1 Sep

This is the current plan. One of the primary things I'm working on in the series of releases is finally cleaning up 100% of Abjad's handling of LilyPond "settings" (broadly construed): overrides; tweaks; context settings (like `\tupletFullLength`); Scheme settings that appear at the head of LilyPond files (like `#(global-staff-size 12)`; and markup. Probably the biggest change users will notice is that overrides, settings and tweaks will become normal objects ("indicators," I suppose) that you can attach to score components, just like markup and articulations are today. So where we have ...
```
abjad.override(note).note_head.color = "#red"
```
... we'll eventually have ...
```
override = abjad.Override("NoteHead.color = #red")
abjad.attach(override, note)
```
... instead.

And where we have ...
```
abjad.tweak(note.note_head).style = "#'diamond"
```
... we'll eventually have ...
```
tweak = abjad.Tweak("style = #'diamond")
abjad.attach(tweak, note.note_head)
```
... instead.

This will look surprising to our users when I put it in place, but it will bring us much closer to the final version of Abjad's model: the special-cased syntax for overrides, tweaks and settings will disappear, and the handling of those objects will be exactly like all the others. So look for those changes down the road, and I'll make an effort to document them super clearly as we go.
