### ISSUE TITLE
Hosting a separate site on GitHub for the last release

### ISSUE THREAD

**Issue by nivlekp** [Abjad/abjad#1337]
Hi @trevorbaca, after doing some duckduckgo search, I found that it is actually very easy to host a separate site on Github for the last release, or for the dev/unstable docs if we want to do it the other way round!

All we have to do is to create a repo (e.g. abjad-stable / abjad-dev), then move the docs to that repo, just like what you are currently doing with `abjad.github.io`. Then under settings, we would have to configure GitHub page as shown.
![Screen Shot 2021-03-24 at 12 22 11 am](https://user-images.githubusercontent.com/38950857/112153290-38dc8c80-8c37-11eb-9b3f-7d055fda6b9a.png)

And there you go!

Of course, it is another question whether you want to maintain two sites.

**Comment by trevorbaca** [comment]
Hi @nivlekp, this is great news to hear. Thank you for the research, and I think that I probably will go ahead and start hosting stable and dev versions of Abjad's docs. (But only those two; beyond that would, I think, be too much to keep up with.) Will probably a few weeks before I build and publish the dev docs.

**Comment by trevorbaca** [comment]
Closing for now. If we decide to take on the extra maintenance effort of hosting two doc sites, we'll open this issue again.
