### ISSUE TITLE
Swap order of BeforeGraceNoteContainer and indicators

### ISSUE THREAD

**Issue by levinericzimmermann** [Abjad/abjad#1376]
Hi everyone,

as always thanks for the great work, I keep on enjoying to use abjad for mostly everything!

I have a question about how to use `BeforeGraceContainer` at the first beat of a bar.
When using the code below abjad will move the \grace command before the \time command.
Is this behavior intended? How could I switch the order?

```python
import abjad
voice = abjad.Voice([abjad.Note("c'", 1)])
abjad.attach(abjad.BeforeGraceContainer([abjad.Note("d'", 0.125)]), voice[0])
abjad.attach(abjad.TimeSignature((4, 4)), voice[0])
score = abjad.Score([abjad.Staff([voice])])
abjad.show(score)
```

![test](https://user-images.githubusercontent.com/28804655/139556777-94a9151f-879b-4454-9363-f2221475eda5.png)

Best, Levin

**Comment by trevorbaca** [comment]
Hi @levinericzimmermann, maybe try attaching the time signature to the grace note?
```
voice = abjad.Voice([abjad.Note("c'", 1)])
container = abjad.BeforeGraceContainer([abjad.Note("d'", 0.125)])
abjad.attach(container, voice[0])
abjad.attach(abjad.TimeSignature((4, 4)), container[0])
score = abjad.Score([abjad.Staff([voice])])
```

```
>>> string = abjad.lilypond(score)
>>> print(string)
\new Score
<<
    \new Staff
    {
        \new Voice
        {
            \grace {
                \time 4/4
                d'8
            }
            c'1
        }
    }
>>
```

```
>>> abjad.show(score)
```
<img width="211" alt="Screen Shot 2021-10-31 at 12 28 41 PM" src="https://user-images.githubusercontent.com/5804733/139580841-3afb05d9-7e0f-480d-a14c-a3adf7effd95.png">

**Comment by levinericzimmermann** [comment]
Hi Trevor, thank you for the fast and helpful reply, that's indeed a solution!
