### ISSUE TITLE
Add container documentation example for CyclicTuple __contains__ dunder method

### ISSUE THREAD

**Issue by jgarte** [Abjad/abjad#1468]
Add sphinx `..  container:: example` for CyclicTuple [\_\_contains\_\_ dunder method](https://github.com/Abjad/abjad/blob/c2b1011f6e473a430b500c515669d1e15985b85e/abjad/cyclictuple.py#L43).

I'm adding this as a `TODO` for myself or anyone else that would like to work on it. 

@trevorbaca Is this something that would be ok to add documentation for?

Maybe a label of `low-hanging fruit` and/or `docs` can be added to this one.

**Comment by trevorbaca** [comment]
@jgarte, Sure!

**Comment by trevorbaca** [comment]
Hey @jgarte add this by the end of the month to get it included in Abjad 3.14. If you're busy, I'm happy to add it, too.
