### ISSUE TITLE
Uqbar 0.6.0 released

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#1469]
I've dropped `sphinx-rtd-theme` as a dependency of https://github.com/josiah-wolf-oberholtzer/uqbar

Abjad should add "sphinx-rtd-theme >= 1.0.0" to its `install_requires` in `setup.py` to continue using the theme.

I also recommend the `sphinx-immaterial` theme as a replacement for `sphinx-rtd-theme`. See https://josiahwolfoberholtzer.com/supriya/ and https://jbms.github.io/sphinx-immaterial/ for examples.

**Comment by trevorbaca** [comment]
Awesome, thanks for the heads-up.
