### ISSUE TITLE
Make regex match stricter?

### ISSUE THREAD

**Issue by jgarte** [Abjad/abjad#1477]
The matches here allow strings like `"zz,,,"` or `zl,,,`:

```python
        match = re.match(r"^([a-z]+)(\,*|'*)$", name)
        assert match is not None, repr(match)
        name, ticks = match.groups()
        return class_.from_ticks(ticks)
```

https://github.com/Abjad/abjad/blob/587c8064ccdfc4eb786f88c877b1824291d707d5/abjad/pitch.py#L1120

Should we make the regex stricter?

**Comment by trevorbaca** [comment]
I think it's probably ok to leave. If `zz,,,` were a recognized pitch name then it's octave number would be 0.
