### ISSUE TITLE
NamedPitchClass.__sub__ is symmetrical

### ISSUE THREAD

**Issue by egginabucket** [Abjad/abjad#1482]
When subtracting `PitchClass` from `PitchClass` and an interval of P4 is expected, P5 is returned and vice versa.

**Comment by trevorbaca** [comment]
@egginabucket Please add a small example.

**Comment by egginabucket** [comment]
Sorry for the issues earlier, I was in a rush :(
example:
```
>>> abjad.NamedPitchClass('g') - abjad.NamedPitchClass('c')
NamedInversionEquivalentIntervalClass('+P4')

>>> abjad.NamedPitchClass('c') - abjad.NamedPitchClass('g')
NamedInversionEquivalentIntervalClass('+P4')
```

**Comment by trevorbaca** [comment]
The behavior you're seeing is correct.

Try subtracting pitches, rather than pitch-classes, to see a different behavior.

**Comment by egginabucket** [comment]
Thank you, I solved my problem using PitchClass.number. This just seemed like unusual behaviour at the time.

**Comment by trevorbaca** [comment]
I think you were probably thinking in pitches instead of pitch-classes.
