### ISSUE TITLE
abjad-book Sphinx extension should halt building on image-generation failure

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#184]
_From [josiah.oberholtzer](https://code.google.com/u/josiah.oberholtzer/) on December 09, 2012 10:38:17_

The abjad-book Sphinx extension uses a process pool to handle generating all images.  Should an image fail to generate for whatever reason - usually because the Abjad object cannot be formatted, or because the resulting formatted object results in bad LilyPond code - the error is not reported, and does not cause the sphinx-build process to halt.  This makes it difficult to determine where an error occurred.

Instead, failed images should fail the API page where they occur, and force the build to halt, as though they were an ReST syntax error.

_Original issue: http://code.google.com/p/abjad/issues/detail?id=183_

**Comment by josiah-wolf-oberholtzer** [comment]
Failed rendering does *not* cause the entire Sphinx build process to fail. That was actually a big problem, requiring a complete re-read and re-write. Now failed renderings are reported, but are not catastrophic.

**Comment by trevorbaca** [comment]
Incredibly better than the complete destruction we had before ;)
