### ISSUE TITLE
Implement two-way-pipe abjad-book Sphinx directive

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#196]
_From [josiah.oberholtzer](https://code.google.com/u/josiah.oberholtzer/) on January 03, 2013 17:34:24_

Now that we know how to create Sphinx extensions with custom nodes and ReST directives, we should reimplement abjad-book entirely as a Sphinx extension (although, of course, keeping the old AbjadBookScript which still handles modifying HTML, ReST and LaTeX sources).

The directive might look like this:

.. abj::

   staff = Staff("c'4 d'4 e'4 f'4")
   len(staff)
   show(staff)

We could implement the various abjad-book options something like this:

.. abj::
   :hidden:
   :strip-prompt:

Why go through the trouble?  Having all image-generation code run during the doc-build process will mean regenerated-images no longer have to be kept in the repository.  It would also mean that the docs beyond the API will get more attention.

_Original issue: http://code.google.com/p/abjad/issues/detail?id=195_

**Comment by josiah-wolf-oberholtzer** [comment]
Done during 2.17 development.

**Comment by trevorbaca** [comment]
+1000
