### ISSUE TITLE
Extend NoteRhythmMaker with duration_pattern=None keyword.

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#214]
_From [trevorb...@gmail.com](https://code.google.com/u/118334091018461915321/) on February 26, 2013 21:09:31_

NoteRhythmMaker currently implements a decrease_durations_monotically=True keyword.

This allows two tie-drawing options:
 
  decrease_durations_monotically=True
  decrease_durations_monotically=False
  
But a very desirable third option will be to draw ties according to an arbitrary metric hierarchy.

This means the keyword will have to accept three values and will have to change names:

  duration_pattern=Left                            # same as decrease durations monotonically
  duration_pattern=Right                          # same as increase durations monotonically
  duration_pattern=None                          # draw ties according to metrical hierarchy of division

This pattern will probably make sense in other rhythm-makers.

Implement in NoteRhythmMaker first and then audit other rhythm-makers.

_Original issue: http://code.google.com/p/abjad/issues/detail?id=213_

**Comment by josiah-wolf-oberholtzer** [comment]
Done during 2.17 development.

Use `rhythmmakertools.PartitionTable`.
