### ISSUE TITLE
Make pychecker run against the codebase

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#228]
_From [trevorb...@gmail.com](https://code.google.com/u/118334091018461915321/) on April 26, 2013 12:46:22_

It used to be possible to run pychecker against the code.

But now we get this:

Desktop$ pychecker abjad
Processing module abjad (abjad)...
WARNING: Abjad no longer supports versions of Python less than 2.7.3!
WARNING: Please upgrade your version of Python to 2.7.3 or 2.7.4!
  ImportError: No module named configobj

Warnings...

abjad:1: NOT PROCESSED UNABLE TO IMPORT

Note that the WARNING statements shouldn't matter because the merely print to the terminal and do not halt execution.

What's going on here?

We really should be able to run pychecker before each build.

_Original issue: http://code.google.com/p/abjad/issues/detail?id=227_

**Comment by josiah-wolf-oberholtzer** [comment]
Done in b98314ab65b0d66c05db9644f4d6a187e533835b.

Linting is being handled by the landscape.io service.

See https://landscape.io/github/Abjad/abjad.
