### ISSUE TITLE
Implement StorageFormatMaker class and externalize storage format-making logic from AbjadObject

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#240]
_From [trevorb...@gmail.com](https://code.google.com/u/118334091018461915321/) on June 28, 2013 16:47:34_

This will clean up the (private) namespace of AbjadObject considerably.

_Original issue: http://code.google.com/p/abjad/issues/detail?id=240_

**Comment by josiah-wolf-oberholtzer** [comment]
Storage formatting logic has been externalized into the `StorageFormatManager` and `StorageFormatSpecifier` classes.

Classes wishing to implement a custom storage format (or repr) using these utilities need only define a private `_storage_format_specification` or `_repr_specification` property.
