### ISSUE TITLE
Write parameterized tests to ensure slots implementation (where appropriate)

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#315]
There's got to be some more-or-less programmatic way to determine if a class should implement slots.

**Comment by josiah-wolf-oberholtzer** [comment]
We now have a `__slots__` parameterized test that checks if a class implements slots locally (i.e. in its own class definition), and whether it also has a dict. Classes which implement slots should not have a dict. Classes whose superclasses implement slots are permitted to not implement slots.

**Comment by trevorbaca** [comment]
Sounds good.
