### ISSUE TITLE
Optimize abjad.Spanner formatting efficiency

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#320]
Spanner formatting logic is spread across discrete calls for each leaf to the following functions:

```
_format_before_leaf()
_format_right_of_leaf()
_format_after_leaf()
```

Some complex spanners (e.g. Beam subclasses) make use of score traversal in the process of formatting. That is, for each leaf that we wish to format a given spanner for, that spanner will ask for the leaf preceding the current leaf, as well as the leaf following, in order to make decisions about how to format the current leaf.

We could reduce the number of formatting function calls by collapsing all of the above functions into a single _format_leaf() function, allowing the results of traversal to be shared between the logic for formatting each format slot.

**Comment by trevorbaca** [comment]
Not sure if this is still valid in June 2017 or not.

Should benchmark.

**Comment by trevorbaca** [comment]
All spanners now implement `_get_lilypond_format_bundle()`.

All methods ...
```
_format_before_leaf()
_format_right_of_leaf()
_format_after_leaf()
```
... have been removed.

Done in 2.21.
