### ISSUE TITLE
Add NestedTupletSpecifier to rhythmmakertools

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#329]
Current output of any rhythm-maker is at most one tuplet deep.

We should be able to specify patterns by which tie chains can be further subdivided via `TieChain.to_tuplet()`.

Such logic can be housed in a `rhythmmakertools.NestedTupletSpecifier` class.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Moved to Abjad/abjad-ext-rmakers issue 7.
