### ISSUE TITLE
Make show(..., **kwargs) work in the docs

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#334]
We can now say ...

   maker = rhythmmakertools.NoteRhythmMaker()
   divisions = 4 * [(1, 16)]
   show(maker, divisions=divisions)

... because show() knows how to pass **kwargs into the appropriate PersistenceAgent methods.

Will be great to make this work in the docs.

**Comment by josiah-wolf-oberholtzer** [comment]
Done during 2.17 development. `show(expr, **kwargs)` now works in the docs!

**Comment by trevorbaca** [comment]
+100
