### ISSUE TITLE
Enhance docs to allow for curated class ordering per package

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#340]
Here're the classes in rhythmmakertools today:

rhythmmakertools.BeamSpecifier
rhythmmakertools.BurnishSpecifier
rhythmmakertools.DurationSpellingSpecifier
rhythmmakertools.EvenRunRhythmMaker
rhythmmakertools.ExampleWrapper
rhythmmakertools.InciseSpecifier
rhythmmakertools.IncisedRhythmMaker
rhythmmakertools.NoteRhythmMaker
rhythmmakertools.RestRhythmMaker
rhythmmakertools.SkipRhythmMaker
rhythmmakertools.TaleaRhythmMaker
rhythmmakertools.TieSpecifier
rhythmmakertools.TupletRhythmMaker
rhythmmakertools.TupletSpellingSpecifier

It would be nice to list the classes like this:

rhythmmakertools.BeamSpecifier
rhythmmakertools.BurnishSpecifier
rhythmmakertools.DurationSpellingSpecifier
rhythmmakertools.InciseSpecifier
rhythmmakertools.TieSpecifier
rhythmmakertools.TupletSpellingSpecifier

rhythmmakertools.EvenRunRhythmMaker
rhythmmakertools.IncisedRhythmMaker
rhythmmakertools.NoteRhythmMaker
rhythmmakertools.RestRhythmMaker
rhythmmakertools.SkipRhythmMaker
rhythmmakertools.TaleaRhythmMaker
rhythmmakertools.TupletRhythmMaker

rhythmmakertools.ExampleWrapper

(This is a longterm sort of thing that can be safely saved until later.)

**Comment by josiah-wolf-oberholtzer** [comment]
Done during 2.17 development.

Add a `__documentation_section__ = 'Some section name'` to any class to make it appear underneath that subheading.

**Comment by trevorbaca** [comment]
Awesome.
