### ISSUE TITLE
Order format contributions by priority rather than category

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#350]
We need a more fine-grained control of the ordering of format contributions for any given slot.

Consider the \afterGrace and \pitchedTrill commands:

```
\new Staff {
    \afterGrace
    \pitchedTrill
    fis''2
    \startTrillSpan gis''
    { e''16[ fis''] }
    g''2
    \stopTrillSpan
}
```

Try the above, and then try swapping \afterGrace for \pitchedTrill. One typesets beautifully and the other does not.

Currently we have \afterGrace hard-coded to appear immediately before a leaf if it has an after-grace container attached. \pitchedTrill will appear somewhere above that if a pitched trill-spanner is also attached. However, for the correct type-setting, \afterGrace _must_ appear before \pitchedTrill.

There are enumerable other examples where composers would need arbitrary fine-grained control of the order of typesetting commands.  One way to handle this is by assigning each format contribution a priority value, governing its location relative to the top/bottom or left/right of a format slot.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Merging into #500.
