### ISSUE TITLE
Forbid nested selections

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#411]
The data structures are too confusing the work with.

**Comment by josiah-wolf-oberholtzer** [comment]
OK. It is rather weird.

Will require some refactoring of selectortools, as some selector callbacks work with selections of selections internally. Can probably be changed to simply tuples of selections.

**Comment by trevorbaca** [comment]
Three years later (June 2017) it's still not clear how this should work. Maybe we should just allow nested selections and close the issue.
