### ISSUE TITLE
Take one more pass through pitchtools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#420]
It's time to take another refactoring pass through `pitchtools`.
- [x] Remove as many package-level functions as possible.
- [ ] Harmonize properties and initialization between classes.
- [ ] Write endless numbers of doc strings for the class properties.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Hey @josiah-wolf-oberholtzer, I feel like we can close this one, too. Wanna do it?

**Comment by josiah-wolf-oberholtzer** [comment]
Close it!
