### ISSUE TITLE
Implement optional look-ahead in abjad.Meter.fit_meters()

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#423]
The meter selection process in `Meter.fit_meters_to_expr()` should take into account the fitness of not only each meter at each target offset, but also the meters that could potentially follow that meter.

`fit_meters_to_expr()` should also be refactored for clarity.

**Comment by trevorbaca** [comment]
Not sure if this is still valid in June 2017.

**Comment by trevorbaca** [comment]
Probably still valid in January 2019.

**Comment by trevorbaca** [comment]
Closing because has been for almost five years.
