### ISSUE TITLE
Investigate possible duplicate tie application in TaleaRhythmMaker

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#436]
Certain configurations of TaleaRhythmMaker, when filling in certain divisions, might result in duplicate tie applications.

Investigate whether this is true and correct the behavior if so.

Do after current scores are complete.

**Comment by trevorbaca** [comment]
Example code needed. Not sure if still valid in June 2017.

**Comment by trevorbaca** [comment]
Will be handled in #438.
