### ISSUE TITLE
Add affordances for automated click-track creation

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#441]
It should be possible to generate and export click-track MIDI files from any well-formed score.

We can do this by creating the bare-minimum classes necessary to generate MIDI files, or by piggy-backing on LilyPond's MIDI export (which we have less control over).

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Can be implemented as a dedicated package if need arises again in future.
