### ISSUE TITLE
Add Beat class to either metertools or rhythmmakertools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#458]
New classes like DuratedBeatDivisionMaker in rhythmmakertools now provide a model of common practice understanding of the musical beat. That means it's probably time to implement an explicit Beat class.

Beat **has** a duration. But Beat probably does not inherit from Duration. Beat should model whether a beat is simple (divides in 2 parts) or compound (divides in 3 parts). Beat may also generalize the number of parts into which it is divisible. This may mean that Beat will work, in part, very much like Meter.

**Comment by jefftrevino** [comment]
I just checked out DuratedBeatMaker.py.

In my conceptual understanding of music theory, a Meter is a either a
schema for dividing a Duration into n parts (top-down), in which case a
Beat is a duration that results from the division, or a Meter is an accrued
grouping of more or less emphasized durations (bottom-up), in which case
the beat precedes its membership in a meter.

In neither case do I see the necessity for Beat as an autonomous concept or
model from Duration or Meter.

In any case, thinking about how to model these things computationally, it
seems the important thing is to allow one to think either bottom-up or
top-down about the relationship between Beats and Meter.

So maybe something like this should be possible:
meter = Meter().from_durations([listOfBeatsOfArbitraryDurations])

It also seems especially problematic to declare a certain level of the
metric hierarchy "Beat" when you'd want to be able to get back to it for
further division or fusion with things called "Duration."

But what does a Beat model get you that you don't already have with
Duration and Meter models?


--
Jeff Treviño, Ph.D.
Visiting Assistant Professor of Music
Carleton College

**Comment by josiah-wolf-oberholtzer** [comment]
Well, the main reason for the separate Beat and Meter classes is that we
still need to iron out some of the modeling differences between them in a
very practical sense. Since Trevor and I are down-to-the-wire on our
respective scores, and both making heavy use of beat- and meter-related
composition logic, we decided to develop the models separately rather than
potentially step on each others' toes.

Once these deadlines blow-over, we'll work on unifying beat and meter.

**Comment by trevorbaca** [comment]
Out-migrated to my own repository a year or two back.
