### ISSUE TITLE
Audit `isinstance(x, (list, tuple))` usage.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#459]
The expression `assert isinstance(x, (list, tuple))` should be replaced with `assert isinstance(x, collections.Sequence)` whenever possible, as the former is too restrictive.

**Comment by trevorbaca** [comment]
Right.

**Comment by trevorbaca** [comment]
Although we should make sure to remember that ``isinstance(foo, collections.Iterable)`` returns true for strings.

**Comment by josiah-wolf-oberholtzer** [comment]
Of course. In which case you'd add something like "and not isinstance(foo,
basestring)" for Py2 or "and not isinstance(foo, str)" for Py3. Still
better than being so strict.

**Comment by josiah-wolf-oberholtzer** [comment]
Also worth considering that sometimes we want an input argument that has an explicit length, and sometimes we don't. So: `collections.Sequence` and `collections.Iterable`.

Note that generator objects are registered as subclasses of `collections.Iterable`.

**Comment by trevorbaca** [comment]
Oh right. That's an excellent point.

**Comment by trevorbaca** [comment]
The change to ``sequencetools.partition_sequence_by_counts(sequence, counts)`` establishes a foothold on what this series of changes will look like.

Basically `sequence` must now be an instance of ``collections.Sequence`` (which accords nicely in terms of naming) and ``counts`` must only be an instance of ``collections.Iterable``. As you pointed out earlier, the most important difference between ``collections.Sequence`` instances and ``collections.Iterable`` instances is that ``collections.Sequence`` instances have length while ``collections.Iterable`` instances do not necessarily have length.

**Comment by josiah-wolf-oberholtzer** [comment]
This issue still stands.

Just noticed that `scoretools.make_notes()` and `scoretools.make_leaves()` both expect their `pitches` argument to be either a `list` or `tuple` instance, meaning you can't pass in `pitchtools.PitchSegment`.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

This works:
```
scoretools.make_leaves([12, 13, 14, 15], [Duration(1, 4)])
Selection([Note("c''4"), Note("cs''4"), Note("d''4"), Note("ef''4")])
```
This doesn't:
```
segment = PitchSegment([12, 13, 14, 15])
scoretools.make_leaves(segment, [Duration(1, 4)])
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 8, in <module>
    leaves = scoretools.make_leaves(segment, [Duration(1, 4)])
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/make_leaves.py", line 498, in make_leaves
    use_messiaen_style_ties=use_messiaen_style_ties,
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/make_leaves.py", line 597, in _make_leaf_on_pitch
    raise ValueError(message)
ValueError: unknown pitch: PitchSegment([12, 13, 14, 15]).
```

**Comment by trevorbaca** [comment]
This now works:
```
>>> segment = PitchSegment([12, 13, 14, 15])
>>> scoretools.make_leaves(segment, [Duration(1, 4)])
Selection([Note("c''4"), Note("cs''4"), Note("d''4"), Note("ef''4")])
```

**Comment by trevorbaca** [comment]
Done in 2.21.
