### ISSUE TITLE
Collapse ContiguousSelection, SliceSelection, SimultaneousSelection into vanilla Selection

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#462]
We get no benefit from those flavors of selection class. Turns out (after a year or so of usage) that checks for contiguity and simultaneity should just be done (via a method call) whenever they need to be done. Object modeling these constraints produces no benefits.

The other selection classes should remain in the system:

selectiontools.Descendants
selectiontools.Lineage
selectiontools.LogicalTie
selectiontools.Parentage
selectiontools.Selection
selectiontools.SelectionInventory
selectiontools.VerticalMoment

These provide real benefits as first-class objects in the system because they provide cleanly delimited interfaces.

**Comment by josiah-wolf-oberholtzer** [comment]
+100

**Comment by trevorbaca** [comment]
Done 2015-12-20.
