### ISSUE TITLE
Decouple LilyPond instrumentName from Abjad instrument classes

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#464]
Consider the "instrument names" written in the left margin before the start of every system.

What should appear to the left of the percussion staff?

If the percussionist plays only the marimba (for example) then it makes sense for "Marimba" / "Mb." to appear to the left of the percussion staff. Likewise for the vibraphone. (And possibly for the timpani in Enlightenment and Romantic scores.) We might designate instruments like the marimba, vibraphone (and possibly timpani) as "concert" percussion instruments (meaning that these instruments might constitute the entirety of a percussion part).

But then consider a percussion setup comprising six or seven different instruments. In this case it probably makes the most sense for only "Percussion" / "Perc." to appear to the left of the percussion staff. Instrument changes within the part will either be encoded with notes at different staff positions (and with differently shaped note heads) or else with in-staff markup that indicates an instrument change.

The model currently implemented in instrumenttools does not capture this distinction. Using `attach(bass_drum, leaf)` causes Abjad to set the LilyPond `\instrumentName` and `\shortInstrumentName` context settings which, in turn, changes the text to the left of the percussion staff to "Bass drum" / "BD" (or equivalent).

We should think this through and model the different between "auxiliary" percussion instruments (like the different drums and shakers) separately from the "concert" percussion instruments (like marimba and vibraphone). This will then clean up the text printed to the left of the percussion staff.

**Comment by jefftrevino** [comment]
I don't find the distinction between "auxiliary" and "concert instruments
so clear. I think you mean pitched vs. unpitched percussion when you say
auxiliary vs. concert, right?

I would probably make an n-line multi-percussion model for use with
unpitched instruments and a pitched percussion model for all the pitched
instruments.

The n-pitched multi-percussion object would take an argument for the number
of staff lines and always be named Perc./Percussion, while the pitched
percussion object could be the parent class of a bunch of
instrument-specific objects that pair instrument names with appropriate
grand or single-staff configurations (timpani is the only pitched
single-staff bass clef instrument, I think).

--
Jeff Treviño, Ph.D.
Visiting Assistant Professor of Music
Carleton College

**Comment by trevorbaca** [comment]
Still valid in June 2017.

It's still not clear what the right model is here. Thinking a bit more, neither the "concert / auxiliary" distinction nor the "pitched / unpitched" distinction is what's actually going on here. We can see that this is the case when we imagine a violinist changing from violin to some other pitched instrument (toy piano) in the middle of a movement.

Thinking a little further ...

The goal is to model who's playing which instrument at which times. Conventionally, the violinist plays a violin from the beginning of a piece until the end. But what should happen when the violinist switches to toy piano for 20 measures? Should LilyPond's left-margin "(short) instrument name" change from "Vn." to "Toy pf."? Or not?

Perhaps the answer will almost certainly be largely a matter of composer preference. Which means that we need to allow both cases ("change instrument name" / "do not change instrument name"). And I think that may be the center of the problem currently: **attaching an Abjad instrument (like `instrumenttools.Piano`) currently does two things at once: sets instrument and also sets instrument name.**

So perhaps this coupling is the problem and the solution is to decouple instrument name from instrument.

How to accomplish this decoupling?

The `LilyPondCommand` (and `LilyPondLiteral`) classes can of course currently be used to set arbitrary LilyPond commands (like `\instrumentName` and `\shortInstrumentName`). So maybe we just need an optional boolean in Abjad instrument classes that can be set to prevent Abjad instruments from setting the LilyPond `\instrumentName` and `\shortInstrumentName` settings, leaving those open for composers to set "by hand" with `LilyPondCommand` / `LilyPondLiteral`.

**Comment by trevorbaca** [comment]
Mental note to review suggestion Randall made at CCRMA. The basic idea is to model something like part name ("Fl. I") separately from current instrument ("Picc." being played by Fl I). Then the principle at format-time is to *always* print part name ("Fl I") to the left of the part (as per historical norms) and then also include a parenthetical indication of any unusual instrument that is being played at the start of each system ("Fl. I (picc.)").

**Comment by trevorbaca** [comment]
Started with a commit this morning; (should've tagged the commit.)

There's now an `Instrument.suppress_markup` property. Set this to true to attach instruments semantically ("this music is being played by the violin") but without setting LilyPond's `instrumentName` or `shortInstrumentName` settings. It then becomes possible to handle "margin markup" (LilyPond's two instrument name context settings) independently.

I have `baca.MarginMarkup` class in my composition repo that I'll probably add to `indicatortools` after I've smoothed it out.

The combination of these two things (neutered instruments + explicit `MarginMarkup` handling) allows us -- for the first time! -- the ability to model standard orchestral stuff where the staff make-up of the string section is changing all the time to show different types of divisi, with indications like "Vni. div a 2", "Vni. div a 4", "2 Vci soli" appearing in the margin as the changes happen. Under our new Instrument / MarginMarkup regime, cases like that will be modeled with the Abjad instrument contexted to each staff (or staff group) to stay the same while the Abjad margin markup changes as needed.

**Comment by josiah-wolf-oberholtzer** [comment]
Do you need the `suppress_markup` property, or is it sufficient to attach the instrument as an annotation via `annotate(component, my_instrument)`?

**Comment by trevorbaca** [comment]
We probably need (something like) the `suppress_markup` property because (right now) attaching something with `abjad.annotate()` means that the attached object should not participate in the `abjad.inspect().get_effective()` regime (and we want, say, the violin attached somewhere to show up in calls to `get_effective(abjad.Instrument)`.

It's possible that introducing `abjad.MarginMarkup` (which is just the pair of `instrumentName` and `shortInstrumentName` ... exactly like the two properties currently implemented on `abjad.Instrument`) will let us remove `abjad.Instrument.instrument_name` and `abjad.Instrument.short_instrument_name` entirely; the `suppress_markup` property is a stepping stone to allow both types of functionality to coexist for a while so that we can see everything feels. (I'm writing the orchestra piece with `baca.MarginMarkup` for the first time to allow for mixed divisi all over the place. If it works out then we'll know that we've got a reasonable generalization to add to the mainline.)
