### ISSUE TITLE
AbjadBook: Add :no-trim: option to AbjadDirective.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#481]
This will help beautify the Pärt literature example.

**Comment by jefftrevino** [comment]
I believe the appropriate term, in this composer's case, is the liturgical
"beatify."

On Tuesday, July 28, 2015, Josiah Wolf Oberholtzer <notifications@github.com>
wrote:

> This will help beautify the Pärt literature example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/481>.
>


-- 
--
Jeff Treviño, Ph.D.
Assistant Professor of Music and Technology
Colorado College

**Comment by josiah-wolf-oberholtzer** [comment]
Haha!

On Tue, Jul 28, 2015 at 5:09 PM, Jeff Treviño <notifications@github.com>
wrote:

> I believe the appropriate term, in this composer's case, is the liturgical
> "beatify."
>
> On Tuesday, July 28, 2015, Josiah Wolf Oberholtzer <
> notifications@github.com>
> wrote:
>
> > This will help beautify the Pärt literature example.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Abjad/abjad/issues/481>.
> >
>
>
> --
> --
> Jeff Treviño, Ph.D.
> Assistant Professor of Music and Technology
> Colorado College
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/481#issuecomment-125786376>.
>



-- 
Josiah Wolf Oberholtzer, PhD
http://josiahwolfoberholtzer.com

**Comment by josiah-wolf-oberholtzer** [comment]
Implemented but requires tests.

**Comment by josiah-wolf-oberholtzer** [comment]
Done in d55aabaab37067c5e18d159249c99a343add36fb.
