### ISSUE TITLE
Upgrade abjad.LilyPondParser to 2.19 syntax

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#492]
- [ ] Update style of LilyPondLexicalDefinition
  - [x] PEP8
  - [x] Variable names (`t` --> `token`, etc.)
  - [x] `str.format()` rather than interpolations
  - [ ] LilyPond source line numbers
- [ ] Update style of LilyPondSyntacticalDefinition
  - [ ] PEP8
  - [ ] Variable names (`p` --> `product`, etc.)
  - [ ] `str.format()` rather than interpolations
  - [ ] LilyPond source line numbers
- [ ] Update content of LilyPondLexicalDefinition from `lexer.ll`
  - This can be done by hand (??).
- [ ] Update content of LilyPondSyntacticalDefinition from `parser.yy`
  - Requires scraping LilyPond 2.19.24's grammar and comparing.

**Comment by trevorbaca** [comment]
Is this still open in June 2017?
