### ISSUE TITLE
Make Abjad PyPy compatible.

### ISSUE THREAD

**Issue by crantila** [Abjad/abjad#493]
Hi&mdash;it's time!

I've started trying to make Abjad compatible with PyPy.JS. I thought I'd go for PyPy first, which is an easier target than PyPy.JS, and probably a worthwhile goal anyway. We could either track all the discussion in this single issue, or spread it out across many sub-issues as we encounter them, whichever you prefer.

In any case, the first issue is quite small. There was a weird thing in ``ImportManager`` that looks like it should also cause problems with CPython, but it doesn't. (It seems like ``import_public_names_from_path_into_namespace()`` tries to set an attribute on a module as though it were a dict, which isn't allowed in any Python). I've fixed the issue in [this commit](https://github.com/nCoda/abjad/commit/d47f42801405984d13ef128e97d33d40c587b937), and it doesn't seem to create new failures in the test suite in CPython 2, 3, or PyPy 2.4.

Could you please take a look at that commit to see whether I've actually fixed this in the best way possible? I don't really understand why the ``ImportManager`` exists, so I have a strange feeling that I'm trying to fix the wrong spot.

Thank you!

**Comment by josiah-wolf-oberholtzer** [comment]
Hi Chris,

- Let's track the discussion here for now. I'm not sure how much adjustment will be required to get things compatible across all of our supported versions. As we encounter discrete topics for edits, I'll ask you to spin off pull requests, or will make the changes myself.

- The very step should be to add `pypy` to our Travis-CI script.

- Regarding ImportManager, you should take a look at how it's actually used in the system, e.g.`abjad/tools/scoretools/__init__.py`. That will help you understand what's going on in `ImportManager.import_public_names_from_path_into_namespace()`. In CPython, the `namespace` argument you find there isn't a module object, but a dictionary coming from a call to `globals()` as an argument to `import_structured_package()` in a tools-package initializer. So, looks like PyPy treats `globals()` different from CPython.

- The change you suggest looks sound, although I'm going to ask you for some stylistic changes as we go forward. *But*, I'm thinking it might be better (mainly for understanding the code down the line) if these tests were made against `platform.system() == 'Java'` instead. None of Abjad's core devs use PyPy, so getting an explicit indication that an `if` branch isn't nonsense, but is specifically for PyPY, could be a big help long term. Note that I'm generally anti-comment; it's too easy to lose them, or for them to go out of date.

- Style: if a big boolean test with an `or` operator fits under 80 characters, go for it. Otherwise, we like to split the right side of the `or` off into its own `else if` line. Hanging parentheses are highly desirable.

This is good:

```
        if ((
            isinstance(namespace, dict) and 
            ImportManager.__name__ in namespace
            ) or hasattr(namespace, ImportManager.__name__)
            ):
            del(namespace[ImportManager.__name__])
```

I would personally lean towards this, even though it looks redundant:

```
        if (
            isinstance(namespace, dict) and 
            ImportManager.__name__ in namespace
            ):
            del(namespace[ImportManager.__name__])
        elif hasattr(namespace, ImportManager.__name__):
            del(namespace[ImportManager.__name__])
```

With `platform.system()`:

```
        if platform.system() == 'Java':
            if hasattr(namespace, ImportManager.__name__):
                del(namespace[ImportManager.__name__])
        elif ImportManager.__name__ in namespace:
            del(namespace[ImportManager.__name__])
```

The above never runs the risk of being on PyPy, but without `ImportManager.__name__` in the namespace. You're either on PyPy or not, and then you run the appropriate check in each platform's branch.

Also:

```
        if ((
            platform.system() == 'Java' and
            hasattr(namespace, ImportManager.__name__)
            ) or ImportManager.__name__ in namespace
            ):
            del(namespace[ImportManager.__name__])
```

**Comment by josiah-wolf-oberholtzer** [comment]
PS: Let's go with `platform.system() == 'Java'` as our main predicate. I was a little worried that it might have performance problems, but Python caches the system check the very first time you make it. I think that's going to be the clearest way to delineate PyPy from CPython checks.

**Comment by josiah-wolf-oberholtzer** [comment]
After installing `pypy` on my local machine and tinkering a little, it's clear that `globals()` actually works exactly the same across both PyPy and CPython. In fact, the `ImportManager` doesn't need to be changed at all. The offending command is in Abjad's root initializer, *after* all of the tools packages have been successfully imported.

abjad/__init__.py:82

```
# import custom exceptions into the builtins module
import os
from abjad.tools.systemtools.ImportManager import ImportManager
ImportManager.import_public_names_from_path_into_namespace(
    os.path.join(__path__[0], 'tools', 'exceptiontools'),
    __builtins__,
    )
del ImportManager
del os
del tools
```

If you start the interactive interpreter for CPython 2/3 or PyPy and ask for `__builtins__`, you get back a module object. But, if create a module and put the line `x = __builtins__` into it, then ask for the value of `x`, you get back a dictionary under CPython, but a module object under PyPy.

So, the absolute simplest (and most universally useful) way of solving this for us is to simply put the following lines at the top of `ImportManager.import_public_names_from_path_into_namespace`:

```
        if isinstance(namespace, types.ModuleType):
            namespace = namespace.__dict__
```

Easy, and actually makes the function more helpful for other situations.

**Comment by crantila** [comment]
Damn... I was just writing to explain that I discovered the same thing, but through [slightly different means](https://docs.python.org/2.7/library/__builtin__.html) (see especially the "CPython implementation detail" note).

In any case, there's another thing to clarify: I don't think ``platform.system() == 'Java'`` will ever do what we want. For one, PyPy returns the same as CPython (e.g., ``'Linux'`` on my computer). For another, PyPy.js returns ``'Emscripten'``.

If we really want to detect the three interpreters, a more reliable alternative is:
```
if 'PyPy' == platform.python_implementation():
    if 'Emscripten' == platform.system():
        # PyPy.js
        pass
    else:
        # PyPy
        pass
else:
    # CPython
    pass
```
... or something like that.

**Comment by josiah-wolf-oberholtzer** [comment]
Ugh. `platform.system()` would've been so clean. OK, let's proceed cautiously without system tests for the moment.

I've committed my change to `ImportManager` and added PyPY to our Travis-CI build matrix. You can watch the PyPy build here: https://travis-ci.org/Abjad/abjad/jobs/73946236. Let's see what blows up.

**Comment by crantila** [comment]
> Let's see what blows up.

True words of an experiened software developer.

Well, ``platform.system()`` would be clean, but it's better this way anyway. I think. Whatever the changes required for PyPy (shouldn't be much) we'll need that *and more* for PyPy.js, so a nested if-statement is a relatively clean way to deal with it.

**Comment by josiah-wolf-oberholtzer** [comment]
Well, something blows up, and it blows up really consistently. Virtually every failure in the test suite comes down to measure instantiation:

```
(pypy)workstation:abjad josiah$ python
Python 2.7.9 (295ee98b69288471b0fcf2e0ede82ce5209eb90b, Jun 02 2015, 18:26:45)
[PyPy 2.6.0 with GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import abjad
>>>> measure = abjad.Measure()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josiah/Development/abjad/abjad/tools/scoretools/Measure.py", line 65, in __init__
    attach(time_signature, self)
  File "/Users/josiah/Development/abjad/abjad/tools/topleveltools/attach.py", line 55, in attach
    expression._bind_to_component(component)
  File "/Users/josiah/Development/abjad/abjad/tools/indicatortools/IndicatorExpression.py", line 105, in _bind_to_component
    self._unbind_component()
  File "/Users/josiah/Development/abjad/abjad/tools/indicatortools/IndicatorExpression.py", line 86, in __repr__
    self.name,
  File "/Users/josiah/Development/abjad/abjad/tools/scoretools/Measure.py", line 127, in __repr__
    indicator = self._get_indicator(indicatortools.TimeSignature)
  File "/Users/josiah/Development/abjad/abjad/tools/scoretools/Component.py", line 478, in _get_indicator
    raise ValueError(message)
ValueError: no attached indicators found matching <class 'abjad.tools.indicatortools.TimeSignature.TimeSignature'>.
```

**Comment by josiah-wolf-oberholtzer** [comment]
I gotta say, this traceback is confusing. When it hits `IndicatorExpression.py:105`, it should be entering the `IndicatorExpression`'s `_unbind_component()` method. Instead, the traceback shows it hitting `__repr__()`? If I stick print() statements into `_unbind_component()`, I see them in the interpreter, but they `_unbind_component()` still doesn't show up in the traceback.

Changing the body of `_unbind_component()` by factoring out the try/except fixes the error:

```
     def _unbind_component(self):
         component = self.component
         if component is not None:
-            try:
-                component._indicator_expressions.remove(self)
-            except ValueError:
-                pass
+            if hasattr(component, '_indicator_expressions'):
+                if self in component._indicator_expressions:
+                    component._indicator_expressions.remove(self)
         self._component = None
```

Is there something I should know about exception handling in PyPy?

**Comment by crantila** [comment]
Maybe [this](https://pypy.readthedocs.org/en/latest/cpython_differences.html#ignored-exceptions)? I'm not sure. I was previously using PyPy 2.4 (which doesn't have the error you showed above) because it was in my distro. So I just installed PyPy 2.6

**Comment by crantila** [comment]
This traceback really doesn't make sense, and it's also not obvious why your fix works&mdash;what it does that the previous code didn't.

**Comment by josiah-wolf-oberholtzer** [comment]
Right? I'm a little baffled. Anyways, the fix works, and it works on CPython, and it reads well.

So more PyPy exception documentation: http://pypy.readthedocs.org/en/latest/coding-guide.html#application-level-and-interpreter-level-execution-and-objects

**Comment by josiah-wolf-oberholtzer** [comment]
OK, Chris. I've pushed a fix. Everything passes.

However, the PyPy test suite is running so slow that it actually hits Travis-CI's timeout-maximum of 50 minutes. Our CPython 2 build usually finishes in 10-15 minutes, and the CPython 3 in 15-20.

The PyPy test suite doesn't even make out of the initial doc-testing phase into the unit-testing phase, so it's really only getting through about 1/8 of the whole thing.

**Comment by josiah-wolf-oberholtzer** [comment]
Sounds like the slowness may be related to coverage testing, on top of our usual test suit: http://morepypy.blogspot.com/2013/10/making-coveragepy-faster-under-pypy.html

I'll see about disabling for non-CPython Travis-CI builds.

**Comment by josiah-wolf-oberholtzer** [comment]
And here: https://bitbucket.org/pypy/pypy/issues/1871/10x-slower-than-cpython-under-coverage

**Comment by josiah-wolf-oberholtzer** [comment]
The results are in: https://travis-ci.org/Abjad/abjad/builds/73966275 (ignore the CPython 3.3 failure - that's a separate issue already in the tracker).

PyPy2 passes the entire suite. *And* it takes basically exactly the same amount of time as CPython 2.7.

PyPy3 is not ready for primetime. Despite disabling coverage collection, it still times-out before completing the test suite. However, it does get very close to completion, making it into the next-to-last set of unit tests. That's a lot better than failing on the A*s during doc-testing.

I'm going to rename this issue to solely target PyPy and mark it closed. We'll open a second one for changes targeting PyPy.js.

Thanks for your patience. I tend to approach these changes rather pessimistically, but getting the codebase PyPy-compatible was *much* easier than the (always ongoing) CPython 2&3 cross-compatibility project.

Cheers!

**Comment by crantila** [comment]
Thanks for my patience?! I start an issue, go have supper, and come back to find you've done all the hard work&mdash;I should be thanking you!

I don't think we'll be using PyPy3 for quite a while, at least until they have support for Python 3.3 (it's currently only 3.2 compatible). The interesting thing will be to see how much faster PyPy will be than CPython in the real world, where the JIT will pay off more than in tests.

**Comment by josiah-wolf-oberholtzer** [comment]
Maybe you can come up with a benchmark? After a number of Travis-CI runs, PyPy seems anywhere from 0%-10% faster on our battery. Not sure what "real-world" usage of Abjad actually entails. Anyways, I'm willing to bet that some prudent refactoring could make parts of the code-base play better with the JIT.

**Comment by crantila** [comment]
That sounds fun actually, but I think I'll avoid making a benchmark unless we have to...
