### ISSUE TITLE
Refactor and add error handling to Block and ContextBlock

### ISSUE THREAD

**Issue by odub** [Abjad/abjad#494]
Refactoring issue, branching off from #488

Issues to resolve:
- Length of `_format_pieces`
- Code duplication in between `ContextBlock` and `Block`
- Items in `self.items` with unexpected type aren't rendered in LilyPond output due to `else pass` here: https://github.com/Abjad/abjad/blob/master/abjad/tools/lilypondfiletools/Block.py#L141 Seems best to fix with input validation when assigning `self.items`

@josiah-wolf-oberholtzer:

> The formatting code for these two classes is getting sufficiently lengthy that it's probably worth breaking out chunks of the `_format_pieces` property into private methods on `Block`, and allowing `ContextBlock` to inherit and incorporate those methods in its own `_format_pieces` property.
> 
> Likewise, I'll probably refactor these two private properties as private methods, as merited by their complexity.

**Comment by josiah-wolf-oberholtzer** [comment]
For the moment, let's just handle 1 and 2 in your list above.

3 is potentially really complex, as you have to proxy the entirety of the `list` interface, adding validation to each method. One way 3 is solvable by subclassing our `datastructuretools.TypedList` and overriding its `_item_coercer` property with one that returns a function which checks for valid types and throws an error on an incorrectly-typed object. That could do the trick. If you want to investigate, see `TypedList`, `TypedCollection` (for `_item_coercer`) and `TimespanInventory` (for an example implementation). However, the change is large enough to merit its own issue.

**Comment by trevorbaca** [comment]
Can we include a minimal example issue reported in OP?

**Comment by trevorbaca** [comment]
Think @josiah-wolf-oberholtzer completed this more than a year ago: both `Block` and `ContextBlock` now implement private `_get_format_pieces()` methods rather than `_format_pieces` properties.
