### ISSUE TITLE
Revise and streamline release build process

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#498]
- [x] Audit packaging checklist instructions
- [x] Audit developer scripts mentioned in packaging checklist
- [x] Use descriptions from merged PRs to created release log
- [x] Create script for building documentation and uploading to `abjad.mbrsi.org` via recursive `scp`
- [x] Create script for automatically filling out packaging transcript entry

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Still valid in January 2019.

**Comment by trevorbaca** [comment]
Done in 3.0, 3.1, 3.2 series. The items in the checklist from 2015 were fixed by the targets Josiah implemented in Abjad's Makefile.
