### ISSUE TITLE
Investigate refactoring LilyPond formatting

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#500]
Is it feasible for all formatting contributions (including child contributions to containers, container opening and closing braces, leaf nuclei) to pass through LilyPond format bundles?

**Comment by trevorbaca** [comment]
Good question ... still in June 2017 ...

**Comment by trevorbaca** [comment]
Still valid in January 2019.

Design goals:

- [ ] Finally figure out the correct collection of format slots; document explicitly.
- [ ] Alphabetize everything that can be alphabetized (probably within a format slot).
