### ISSUE TITLE
Use SVG in Sphinx output for all notation

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#505]
This requires trimming and scaling. It's not clear how crop SVGs automatically on the command-line without resorting to InkScape (which appears to need GUI operation to do this).

Other possibilities involve significant non-Python-tool installations.

**Comment by jefftrevino** [comment]
This says Inkscape will do it:
https://shkspr.mobi/blog/2013/03/inkscape-cropping-svg-files-on-the-command-line/

On Friday, August 7, 2015, Josiah Wolf Oberholtzer <notifications@github.com>
wrote:

> This requires trimming and scaling. It's not clear how crop SVGs
> automatically on the command-line without resorting to InkScape (which
> appears to need GUI operation to do this).
>
> Other possibilities involve significant non-Python-tool installations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/505>.
>


-- 
--
Jeff Treviño, Ph.D.
Assistant Professor of Music and Technology
Colorado College

**Comment by josiah-wolf-oberholtzer** [comment]
saw that. it launches inkscape's gui. no go for me - don't want that
happening 1000x when building the docs.

**Comment by jefftrevino** [comment]
Flicker films might become fashionable again someday soon?

Would Imagemagick work?: http://www.imagemagick.org/script/index.php

On Friday, August 7, 2015, Josiah Wolf Oberholtzer <notifications@github.com>
wrote:

> saw that. it launches inkscape's gui. no go for me - don't want that
> happening 1000x when building the docs.
>
> On Fri, Aug 7, 2015, 01:44 Jeff Treviño <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > This says Inkscape will do it:
> >
> >
> https://shkspr.mobi/blog/2013/03/inkscape-cropping-svg-files-on-the-command-line/
> >
> > On Friday, August 7, 2015, Josiah Wolf Oberholtzer <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > This requires trimming and scaling. It's not clear how crop SVGs
> > > automatically on the command-line without resorting to InkScape (which
> > > appears to need GUI operation to do this).
> > >
> > > Other possibilities involve significant non-Python-tool installations.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Abjad/abjad/issues/505>.
> > >
> >
> >
> > --
> > --
> > Jeff Treviño, Ph.D.
> > Assistant Professor of Music and Technology
> > Colorado College
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Abjad/abjad/issues/505#issuecomment-128643057>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/505#issuecomment-128643392>.
>


-- 
--
Jeff Treviño, Ph.D.
Assistant Professor of Music and Technology
Colorado College

**Comment by josiah-wolf-oberholtzer** [comment]
No, ImageMagick works with raster images. It can import vector graphics, but it rasterizes them in the process.

The following Python project on GitHub seems like it might do what I want, but I'm not sure how to install its dependencies: https://github.com/skagedal/svgclip/blob/master/svgclip.py

It uses InkScape (without its GUI) to determine the bounding box of the contents of your SVG. Then it uses some other libraries (cairo and rsvg) to transform the contents of the SVG and write it back to disk.

I'm fairly certain that the `cairo` mentioned in the script is this one: pypi.python.org/pypi/pycairo, which actually points at http://cairographics.org/pycairo/. Unfortunately, it can't be installed from pip, making it kind of a no-go. (I might get proved wrong about that, which would be nice).

BUT, InkScape still can give you the bbox coordinates, so maybe munging the SVG's `viewBox` attribute by hand, using one of Python's XML libs, is a path we can take.

**Comment by josiah-wolf-oberholtzer** [comment]
Part of this is addressed in #555, which introduces SVG output for Graphviz via the top-level `graph()` function.

**Comment by trevorbaca** [comment]
Still valid in January 2019.

**Comment by trevorbaca** [comment]
It looks like this has been done for a while, which is awesome.
