### ISSUE TITLE
Implement logical staff, staff group and score

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#506]
- [x] Implement model of all available LilyPond contexts and their hierarchization.
- [x] Categorize LilyPondContext instances as score-like, staff-group-like, staff-like and voice-like.
- [ ] Teach `scoretools.Context` about `lilypondnametools.LilyPondContext`.
  - `scoretools.Context.context_name` --> `scoretools.Context.lilypond_context`

**Comment by josiah-wolf-oberholtzer** [comment]
One of the difficult parts of this problem is understanding which contexts are allowed to contain which other contexts, and how to resolve missing intermediate contexts (e.g. what does LilyPond implicitly create when you place a Voice inside a Score context). This especially applies when the contexts have been custom-created by a composer using the system. 

Some of this can now be solved by our `lilypondnametools.LilyPondContext` class, which allows the registration of custom contexts, and can resolve the relationships between contexts.

**Comment by trevorbaca** [comment]
This is is really super helpful. The entire stream of context-resolution
commits today have been really amazing.

**Comment by josiah-wolf-oberholtzer** [comment]
Thanks. We're a *lot* closer to having path towards solving this problem.

With some work (akin to your very early sketches on how spanners work in LilyPond) we may be able to demonstrate exactly how different kinds of context can contain one another, what intermediate contexts are created and how context properties and grob overrides propagate through the hierarchy.

Something that may become desirable is to enforce that custom contexts be registered with our LilyPond environment before attempting to create `Context` instances with custom context names. See `LilyPondContext.register()` for what I'm talking about. I've provided methods for altering the default information provided by our LilyPond scrape which, in turn, is available to the parser. Subsequent investigation may suggest sandboxing the default scrape from "custom" LilyPond environment changes, but I'm not sure that's necessary yet.

**Comment by josiah-wolf-oberholtzer** [comment]
The custom context registration is potentially extendable to registering custom LilyPond engravers and grobs. However, I've never created a custom grob or engraver in any source file associated with a score project. I doubt you have either. Our modifications seem constrained to creating custom contexts and loading them up with engraver additions and removals, as well as property changes and grob overrides. All of that is conveniently constrained to the domain of context modifications.

**Comment by trevorbaca** [comment]
Right. Definitely haven't ever created a custom grob or engraver. So, yeah:
context modifications.

**Comment by trevorbaca** [comment]
Of the last 10 or 15 scores I've built, I've been able to make do with the insanely simple combination of these:

* our vanilla `Context` class (with `context_name` set to something)
* custom definition of named context in `stylesheet.ily`

Is it possible that such an incredibly simple approach might eliminate the need for this issue? Possibly including the existing `LilyPondContext` class?

**Comment by josiah-wolf-oberholtzer** [comment]
I'd like to leave this open for now, and I sincerely intend to implement this when I have the time. You're correct that `LilyPondContext` will play a role. I'm hoping to use `LilyPondContext` to teach the core component classes about what can contain what in a simple and intelligent way, and then using that to deduce the nearest context of the correct type to contain a given scoped indicator.

We've both definitely gotten around the problems that arise from not having logical staves and scores. Neither of us have trouble putting together complex score objects. But this is the sort of problem that always bites newcomers. Solving it will be a great win for the system model, our understanding of LilyPond, and a boon to inexperienced users.

**Comment by trevorbaca** [comment]
Leaving open in January 2019. Hey @josiah-wolf-oberholtzer if you ever wanna drop some examples into this thread of desired final functionality, I'd be happy to take a look at them and think through them over the months ahead. If I know exactly what we want to achieve, I bet we can find a path now.
