### ISSUE TITLE
Implement Neo-Riemannian transforms

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#512]

**Comment by trevorbaca** [comment]
Wow. Who's been working with those? (I'd personally have to go re-read a bunch of stuff in order to be able to implement.)

**Comment by josiah-wolf-oberholtzer** [comment]
Actually, I want to use them myself (pretty funny). And it gives a good excuse for revisiting tonalanalysistools.

**Comment by trevorbaca** [comment]
Great. Mean I'll probably learn rather a lot from reading the model!!

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by josiah-wolf-oberholtzer** [comment]
Close it. Additional tonal analysis can go in the tonality extension.
