### ISSUE TITLE
AbjadBook: Add ".. reveal::" directive.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#518]
Use case: at the beginning of a cookbook, you define a function or class, then use it to create some notation. All of this is hidden except for the notation. At the end of the cookbook, you want to summarize the work done throughout the article. Rather than duplicating the hidden code used at the very beginning, you should be able to label the initial code with some string, then reference that string to simply duplicate it, unhidden, at the end of the article.

**Comment by jefftrevino** [comment]
This sounds very useful. Would there also be a way to insert comments in
the initial code that would appear at the end, too? It seems like code
revelation
is half of the desired summarizing functionality.

On Thursday, August 13, 2015, Josiah Wolf Oberholtzer <
notifications@github.com> wrote:

> Use case: at the beginning of a cookbook, you define a function or class,
> then use it to create some notation. All of this is hidden except for the
> notation. At the end of the cookbook, you want to summarize the work done
> throughout the article. Rather than duplicating the hidden code used at the
> very beginning, you should be able to label the initial code with some
> string, then reference that string to simply duplicate it, unhidden, at the
> end of the article.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/518>.
>


-- 
--
Jeff Treviño, Ph.D.
Assistant Professor of Music and Technology
Colorado College

**Comment by josiah-wolf-oberholtzer** [comment]
Comments? Definitely.

I should have an example up later today, assuming I get this working
quickly.

**Comment by josiah-wolf-oberholtzer** [comment]
I've got this feature working and integrated into a couple of the new, in-progress cookbook articles.

Pull and rebuild the docs (via `ajv api -CM`). It will take quite awhile (i.e. > 30minutes).

Then take a look at cookbook 10 and 21. Both of them show some graphics up-front via hidden code which is later revealed using the new `..  reveal::` directive.

**Comment by josiah-wolf-oberholtzer** [comment]
Done in 7d529123959eedfb5e3dbabf8acfa9d43573db76.
