### ISSUE TITLE
pip install in OS X fails, import error

### ISSUE THREAD

**Issue by heretogo** [Abjad/abjad#525]
I am getting this error and I have know idea why since ContextMap.py is in the site-packges directory.

ImportError: No module named site-packages.abjad.tools.datastructuretools.ContextMap

**Comment by josiah-wolf-oberholtzer** [comment]
Can you tell us how you installed Abjad? From PyPI via `pip` or `easy_install`, or via a `git clone` from the repository on GitHub?
