### ISSUE TITLE
Merge selectortools.Selector into selectiontools.Selection (universalizing select())

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#527]
The rich interface of methods provided on `selectortools.Selector` can all be implemented on the `selectiontools.Selection` class.

This will mean that selector chaining can be initiated by a call to the top-level `select()` function:

```
selector = select()
selector = selector.by_leaves()
selector = selector.by_duration()
```

This will also pave the way for merging the `selectortools` and `selectiontools` packages.

Note that before this item is done, the `selectiontools.SimultaneousSelection` and `selectiontools.ContiguousSelection` classes should be merged into the unified `selectiontools.Selection` class, as specified in #462.

**Comment by josiah-wolf-oberholtzer** [comment]
Tentatively giving a :+1: to this idea.

1. Selections have to support nested selections. They already do, but making this change requires that they continue to do so. The use case is selecting logical ties. Under this change, `select().by_logical_tie()` is going to return a selection of selections.

2. We need to hammer out how `select(my_staff).by_logical_tie()` differs from `select().by_logical_tie()`.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
The dot-chaining asked for in the OP has been possible for a year or two:
```
selector = select().by_leaf().by_duration()
```
Closing issue.

If we later decide we want to merge `selectortools`, `selectiontools` just because, then that's ok and we can open a new issue.
