### ISSUE TITLE
Break nonmusical classes / functions into separate repositories

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#528]
Abjad has developed organically over many years. Numerous classes, functions, even whole tools packages have great utility outside of musical contexts. Examples include:
- `stringtools`
- large parts of `documentationtools`
- `datastructuretools`
- `developerscripttools`
- `AbjadObject`, `AbjadValueObject`
- `StorageFormatSpecification`, `StorageFormatManager`

Other tools packages, such as `abjadbooktools` and `ipythontools` could also broken out (for the first time, or again). These represent tools unlikely to be used by many Abjad users, and require extra dependencies that can complicate and slow down testing of core functionality.

**Comment by trevorbaca** [comment]
I think the direction of this idea is right.

Interesting to note that the packages (and classes) listed above can divide into two groups: packages that could (conceivably) be used completely outside of Abjad, and packages that probably only make sense with reference to Abjad.

Group 1: possible use outside of Abjad: `stringtools`, `datastructuretools`. Also `mathtools` and, unexpectedly, `sequencetools`. These are basically base-level packages in the system that are identifiable by their *lack* of dependencies on other packages.

Group 2: probably only make sense with reference to Abjad: `developerscripttools`, `abjadbooktools` and possibly `ipythontools`.

Interestingly, group 1 are "slim" (and therefore slow testing very little) whereas group 2 are "fatter" (and slow testing more).

**Comment by josiah-wolf-oberholtzer** [comment]
Note that I do use `systemtools`, `datastructuretools`, `documentationtools` and `stringtools` in my Supriya project (https://github.com/josiah-wolf-oberholtzer/supriya).

I also use `abjadbooktools` for documentation purposes (because it handles both notation *and* graphs).

Additionally, `sequencetools`, `mathtools`, `timespantools` show up for musical reasons.

**Comment by trevorbaca** [comment]
That's really cool. Because that means that -- somehow -- you're able to use the timespan models we've implemented in Abjad ... for Supercollider!

**Comment by josiah-wolf-oberholtzer** [comment]
Oh, of course, easily. `Timespan` is germane to lots of domains. I started down that path in the first place in order to make Abjad more like electro-acoustic tools I was using.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Also wanna remove `rhythmmakertools` for the 3.0 release.

**Comment by trevorbaca** [comment]
Closing: abjad-ext-nauert, abjad-ext-book, abjad-ext-cli, abjad-ext-rmakers all exist as of Abjad 3.0.
