### ISSUE TITLE
Activate hyperlinks in the "attribute summaries" section of class API pages

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#534]
(Recall that the API includes pages for 30 or so packages in the system and also pages for couple of hundred classes in the system. So we have "package API pages" and "class API pages".)

Package API pages implement a very helpful feature: package API pages activate the table-of-contents listing of classes as hyperlinks, which makes navigation to classes within a package very easy. The pitchtools API page, for example, activates the NamedPitch and NumberedPitch classes as hyperlinks.

It would be extremely helpful to extend this feature to the level of class API pages, too. This would mean that the attributes (ie, properties and methods) listed in the "attribute summary" section at the top of each class API page would be hyperlinked. For example, the "attribute summary" of the NamedPitch API page could hyperlink "accidental", "accidental_spelling", "alteration_in_semitones" and so on, making it extremely easy to navigate directly to a single property or method on a class.

**Comment by josiah-wolf-oberholtzer** [comment]
This should happen automatically in autosummaries, but I believe there is a long-standing bug with Sphinx standing in the way.

**Comment by josiah-wolf-oberholtzer** [comment]
A couple things are at play here.

- Our attribute entries are currently flagged with `:noindex:`, meaning that they had no entry in Sphinx's index of referenceable objects, could not be hyperlinked, etc.

- The names used as references in the autosummary and autoattribute directives differed: `~module_path.class_name.attribute_name` versus `class_name.attribute_name`. Even though Sphinx is able to resolve each one properly to an actual piece of code in Abjad, it doesn't seem able to link one reference to the other. I don't know why.

**Comment by josiah-wolf-oberholtzer** [comment]
Fixing this involves making all class attributes indexable, and harmonizing the names used as references in the autosummary table and the autoattibute directives.

There is no visual down-side to this, but it does mean that the docs index becomes bloated with links to methods and properties. There doesn't appear to be a way around that, but it seems like a fair trade-off.

**Comment by trevorbaca** [comment]
Great diagnosis. IIUC then the upswell of links would happen in the .rst pages (which users effectively never see ... which makes sense in your description of "no visual down-side"). If that's the case then I think I'm completely ok increasing the link freight in the .rsts :)

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca A version of the docs with this change are now online at http://abjad.mbrsi.org. Check out any class API page and try the autosummary links. Also notice that there's a link anchor next to every method and property entry. I find it very nice: you can finally link someone to a specific class member.

If there's no complaints, I'll merge the associated PR pending Travis-CI tests passing.

**Comment by trevorbaca** [comment]
Holy crap this is great.

YES: *please* merge. Both the in-page navigation afford by the activated links AND the reference-ability of the named anchors are major improvements!

**Comment by jdavancens** [comment]
Yeah that’s awesome. I was going to ask about that.
