### ISSUE TITLE
Redefine abjad.Container.__setitem__, abjad.Container.__delitem__ as special cases of explicit mutate methods

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#535]
See #463 for some previous discussion.

Both `Container.__setitem__()` and `Container.__delitem__()` are complex.

`Container.__setitem__()` should be replaced by `mutate().replace()` (as discussed in #463).

`Container.__delitem__()` should also be replaced by some combination of mutate methods.

**Comment by josiah-wolf-oberholtzer** [comment]
This doesn't sit well with me. I know that some implicit behavior is unavoidable with `__setitem__()`, but you could make the same case against appending, extending, inserting: break spanners? Extend them?

I really think practicality beats purity here. We go out of our way to create parity between interacting with Abjad containers and interacting with Python sequences only to pull the rug out now. Again, I think this is an unnecessary barrier to entry for new users.

**Comment by trevorbaca** [comment]
The non-documented complexity of `Container.__setitem__()`, `Container.__delitem__()` arises agin in the following use case.

I'll phrase in the form of a game.

Imagine you have two spanner-bearing selections:
```
>>> selections = [                                                                  
    select(Container("c'8 [ d'8 e'8 ]")),                                       
    select(Container("f'8 [ g'8 a'8 ]")),                                       
    ]
```                                                                          
And further imagine that you want temporarily to insert both selections in a container.

So that (for example) you can get the start offset of the last note:
```
>>> container = Container(selections)
>>> inspect_(container[-1]).get_timespan().start_offset
Offset(3, 8)
```
So far so good.

The wrinkle arises when you want to destroy the temporary contain and restore the selections back to their original state **without destroying beams and other spanners**.

How do we do this in the current system?

I implemented the logic myself -- multiple times -- and every time I need this functionality (about every 6 months) I have to grep the code for the one corner case where it's used.

Notice that this ...
```
>>> container[:] = []
>>> f(selections[0][0])
>>> f(selections[0][0])
{
    c'8
    d'8
    e'8
}
```
... destroys beams.

There's a very easy solution the current system. But I'll leave the question unanswered here as a challenge. And to make the point that this *can not* continue to be the way we implement this small handful of tedious (but crucial) corner cases.

**Comment by trevorbaca** [comment]
Spoiler alert:
```
>>> del(container[:])
>>> f(selections[0][0])
{
    c'8 [
    d'8
    e'8 ]
}
```
Beams are preserved in the idiom `del(container[:])`, it turns out.

But idioms are bad. This is precisely the thing that should an explicit method somewhere.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
These will become incredibly cleaner with the removal of spanners.

**Comment by trevorbaca** [comment]
This issue disappears in Abjad 3.1 because spanners have been removed from the system!
