### ISSUE TITLE
Extend Abjad book to allow the display of exceptions in the API

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#536]
Python's doctest is ok with exceptions in doc strings:
```
                >>> music = maker(divisions)
                Traceback (most recent call last):
                ...
                Exception: talea is too short to read once only.
```
But including this sort of information causes Abjad book to error in ``CodeBlock.push_to_console()`` when the ``console`` object comes back with ``errored`` set to true.

Some preliminary fiddling shows that setting ``allow_errrors`` to be always true (even when it is the case that ``console`` returns ``errored``) does indeed allow exceptions to be printed in the API. (The stacktrace is even nicely color-coded.) But it seemed unwise to commit such a change because ``allow_errors`` is probably doing useful work somewhere. (And ignoring ``allow_errors`` might be a problem when real errors do arise.)

Will be nice eventually to document exceptions in the public API. But enhancement is not urgent and can wait as long as necessary.

**Comment by josiah-wolf-oberholtzer** [comment]
To summarize: the use case is documenting exception behavior in docstrings when building with Sphinx?

**Comment by josiah-wolf-oberholtzer** [comment]
And to clarify: do not set `allow_errors` to be always true. The flag is there to assist with building abjad-book-assisted docs like the cookbook and literature examples which are not doctested. There are tests for catching, propagating and permitting exceptions during abjad-book interpretation.

What you're seeing here requires teaching abjad-book to whitelist errors that appear in docstrings scooped-up by Sphinx's autodoc extension.

**Comment by trevorbaca** [comment]
Yup: to document exception behavior when building with Sphinx.

(And right: ``allow_errors`` is clearly doing work. That was my reason for bookmarking here rather than changing functionality.)

**Comment by josiah-wolf-oberholtzer** [comment]
OK, after some review, this should be an easy fix.

In `abjadbooktools.CodeBock.from_docutils_literal_block`, pass a `CodeBlockSpecifier` instance with `allow_errors=True` into the `CodeBlock` constructor.

That will set all `::`-delimited literal blocks in rst files to permit errors.

**Comment by trevorbaca** [comment]
Beautiful.

Thanks very much for this one. Worked perfectly and committed.

:+1:

**Comment by josiah-wolf-oberholtzer** [comment]
Good. Cheers!
