### ISSUE TITLE
Add "sudo easy_install pip" to install instructions

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#543]
One of the joys of setting up a new workstation is the ability to test our install instructions.

First-time users of Abjad will benefit from including ...
```
sudo easy_install pip
```
... near the beginning of the install instructions.

Will add after checkout and setup.

**Comment by trevorbaca** [comment]
Also, document the check ...
```
convert --version
```
... to allow users to make sure that ImageMagick installs correctly.

**Comment by trevorbaca** [comment]
Also, disambiguate the meaning of an important line in the virtual environment instructions:
```
If you have virtualenvwrapper installed, create a virtual environment and install Abjad into that instead:
```
The "instead" confounds the exposition of what the instructions are trying to communicate.

(Basically what we need to do is better to clarify what the composer is using ``virtualenv`` to do during installation and what the composer is using ``virtualenvwrapper`` to do during installation.)

**Comment by trevorbaca** [comment]
Also, the command ...
```
pip install virtualenv virtualenvwrapper
```
... needs to be ...
```
sudo pip install virtualenv virtualenvwrapper
```
... instead.

**Comment by trevorbaca** [comment]
Actually, even ...
```
sudo install virtualenv virtualenvwrapper
```
... errors with ...
```
Desktop$ sudo pip install virtualenv virtualenvwrapper
Password:
The directory '/Users/trevorbaca/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/trevorbaca/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting virtualenv
  Downloading virtualenv-14.0.6-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 304kB/s 
Collecting virtualenvwrapper
  Downloading virtualenvwrapper-4.7.1-py2.py3-none-any.whl
Collecting virtualenv-clone (from virtualenvwrapper)
  Downloading virtualenv-clone-0.2.6.tar.gz
Collecting stevedore (from virtualenvwrapper)
  Downloading stevedore-1.10.0-py2.py3-none-any.whl
Collecting pbr>=1.6 (from stevedore->virtualenvwrapper)
  Downloading pbr-1.8.1-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 90kB 4.2MB/s 
Collecting argparse (from stevedore->virtualenvwrapper)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting six>=1.9.0 (from stevedore->virtualenvwrapper)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: virtualenv, virtualenv-clone, pbr, argparse, six, stevedore, virtualenvwrapper
  Running setup.py install for virtualenv-clone ... done
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-Oh22CO-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```
Though it looks like ...
```
sudo -H virtualenv virtualenvwrapper
```
... works.

So add ...
```
sudo -H virtualenv virtualenvwrapper
```
... to the install instructions.

**Comment by trevorbaca** [comment]
Also, document the check ...
```
virtualenv --version
```
... for the composer to confirm ``virtualenv`` installation.

**Comment by trevorbaca** [comment]
Why does ``sudo -H virtualenvwrapper`` create a ``virtualenvwrapper`` directory?

Where (on the composer's filesystem) should this directory be housed?

**Comment by trevorbaca** [comment]
Also, the command ...
```
source /usr/local/bin/virtualenvwrapper.sh
```
... doesn't work because the file in question isn't created during virtualenvwrapper installation.

Here're what're created ...
```
$ ls /usr/local/bin/v*
/usr/local/bin/virtualenv       /usr/local/bin/virtualenv-clone
/usr/local/bin/virtualenv-3.5
```
... instead

(So the command above should be changed in the install instructions.)

**Comment by trevorbaca** [comment]
Actually, it looks like installation ``virutalenvwrapper`` (on a brand new drive) doesn't work at all:
```
Desktop$ sudo -H pip install virtualenvwrapper
Collecting virtualenvwrapper
  Using cached virtualenvwrapper-4.7.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /Library/Python/2.7/site-packages (from virtualenvwrapper)
Requirement already satisfied (use --upgrade to upgrade): virtualenv-clone in /Library/Python/2.7/site-packages (from virtualenvwrapper)
Collecting stevedore (from virtualenvwrapper)
  Using cached stevedore-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pbr>=1.6 in /Library/Python/2.7/site-packages (from stevedore->virtualenvwrapper)
Requirement already satisfied (use --upgrade to upgrade): argparse in /Library/Python/2.7/site-packages (from stevedore->virtualenvwrapper)
Collecting six>=1.9.0 (from stevedore->virtualenvwrapper)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, stevedore, virtualenvwrapper
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-WSMRV7-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by josiah-wolf-oberholtzer** [comment]
Hunh. Not sure what you're seeing or why you're using `-H`. I've followed these instructions on four different machines successfully.

**Comment by josiah-wolf-oberholtzer** [comment]
Also not sure why you had to `easy_install pip`. Python 2.7.9 and later bootstrap `pip` automatically so you don't have to perform that step. I'm willing to bet all of this is because of you using `easy_install`.

**Comment by trevorbaca** [comment]
Or:

http://stackoverflow.com/questions/32086631/cant-install-virtualenvwrapper-on-osx-10-11-el-capitan

**Comment by trevorbaca** [comment]
(Also, if there really is a possibility that ``easy_install`` can cause drama, then we really, really need to document it! Because Google will lead right to ``easy_install``.)

**Comment by josiah-wolf-oberholtzer** [comment]
Will investigate at home later today, but I have `virtualenvwrapper` installed happily on a 10.11.2 machine.

**Comment by trevorbaca** [comment]
The last comment in the Stackoverflow article (above) fixes the problem on my machine:
```
sudo pip install virtualenvwrapper --ignore-installed six
```

So this will also need to be documented in the install instructions.

**Comment by trevorbaca** [comment]
Also, add note for Mac users to prefer Homebrew (instead of MacPorts).

Remove MacPorts commands from install instructions; write Mac install instructions in terms of Homebrew only.

**Comment by josiah-wolf-oberholtzer** [comment]
:+1: for demoting MacPorts. All of the professional devs I know have migrated entirely to HomeBrew.

**Comment by geekraver** [comment]
The IPython install instructions:

    sudo pip install abjad [development, ipython]

shouldn't have spaces. Instead:

    sudo pip install abjad[development,ipython]

**Comment by trevorbaca** [comment]
Thanks! Will update the docs.

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca @geekraver I'm starting to address these concerns in #548. Will be running through the entire install process in a *nix environment. Comments welcome.

@geekraver I see from your homepage that's your using Abjad under Windows. *Definitely* let me know about that experience. Neither Trevor nor I have access to any Windows environments. He works exclusively under OSX and I work under a combination of OSX and (usually) Debian.

**Comment by geekraver** [comment]
Not sure how you got that idea; I am on OSX too.

-- 
Graham Wheeler

On February 29, 2016 at 9:09:29 PM, Josiah Wolf Oberholtzer (notifications@github.com) wrote:

@trevorbaca @geekraver I'm starting to address these concerns in #548. Will be running through the entire install process in a *nix environment. Comments welcome.

@geekraver I see from your homepage that's your using Abjad under Windows. Definitely let me know about that experience. Neither Trevor nor I have access to any Windows environments. He works exclusively under OSX and I work under a combination of OSX and (usually) Debian.

**Comment by josiah-wolf-oberholtzer** [comment]
LOL. Read too fast. Another narrow shave without having to address the _Windows menace_.

**Comment by jdavancens** [comment]
Yo @trevorbaca , I'd like to take a crack at this issue to familiarize myself with the pull request process.

**Comment by trevorbaca** [comment]
Sweet @jdavancens! Ok, @josiah-wolf-oberholtzer is the guardian (and engineer) of the PR process. Lemme check with him and see how he'd like us to publish the process ...

**Comment by josiah-wolf-oberholtzer** [comment]
Hey @jdavancens, I have a PR / branch open tackling the issues in this thread at #548. I haven't merged it in yet only because I want to round up some folks to really give it a good testing. Feel free to take a look, comment, etc.

Why don't you try #523 instead? You'd be dealing with the exact same workflow.

**Comment by jdavancens** [comment]
OK @josiah-wolf-oberholtzer and @trevorbaca , I will hop over to #523

**Comment by josiah-wolf-oberholtzer** [comment]
@jdavancens Don't hesitate to ping me for workflow instructions. We're moving to a kind of Git Flow Lite (http://nvie.com/posts/a-successful-git-branching-model/).

Basically:

- fork Abjad on GitHub
- clone your fork locally
- open an issue on Abjad's GitHub if there isn't one already
- make a branch in your local copy to tackle this issue
- make your changes and push them up to your fork (git will tell you what to do)
- when you're ready, open a pull request on the official Abjad GitHub 
- we'll take a look, talk about it and merge it if everything looks good
