### ISSUE TITLE
Allow Crescendo('p < f')

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#544]
We allow `Hairpin('p < f')`.

So we should allow `Crescendo('p < f')` and `Decrescendo('f > p')`, too.

**Comment by josiah-wolf-oberholtzer** [comment]
1) Isn't the `<` and `>` superfluous here? `Crescendo('p', 'f')` is also more programmatically useful.
2) Related: there should be a dynamic application protocol like the text spanner / markup protocol you've been outlining for a year.

**Comment by trevorbaca** [comment]
Yeah agreed.

1. The interface for Crescendo, Decrescendo should be as much the same as for Hairpin as possible. But yes the < and > indicators are redundant in the case of the named classes. And I think the form with the tuples of dynamics is already allowed (as in Hairpin).

2. Yes. This has been a bugaboo for almost 10 years. The general problem being solved here is *enchained spanners*. And, yes, I think the "piecewise definition protocol" (or whatever we want to call it) will be the end solution. I'm open to other solutions, but the PDP seems best. And, thinking back, I think I took the final stages of that idea from the work you were doing with BowSpanner.

**Comment by trevorbaca** [comment]
Hey, is there any interest in permanently removing `Crescendo` and `Decrescendo` in favor of `Hairpin`?

**Comment by josiah-wolf-oberholtzer** [comment]
I'm OK with removing them as long as you can instantiate a `Hairpin` with a bare `<` or `>` descriptor.

**Comment by trevorbaca** [comment]
Yup, exactly.

**Comment by trevorbaca** [comment]
Still valid in June 2017:
```
Abjad 2.21 (development)
>>> Crescendo('p < f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trevorbaca/abjad/abjad/tools/spannertools/Crescendo.py", line 49, in __init__
    overrides=overrides,
  File "/Users/trevorbaca/abjad/abjad/tools/spannertools/Hairpin.py", line 143, in __init__
    direction)
  File "/Users/trevorbaca/abjad/abjad/tools/stringtools/to_tridirectional_lilypond_symbol.py", line 82, in to_tridirectional_lilypond_symbol
    raise ValueError(argument)
ValueError: p < f
```

**Comment by trevorbaca** [comment]
Done in 2.21.
