### ISSUE TITLE
Fix size of lineage graphs in API

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#545]
Lineage graphs now appear to be rendering at a very large size.

The screenshot attached here shows a fullscreen view of one graph.
![big-lineage-graphs](https://cloud.githubusercontent.com/assets/5804733/12933433/a39e0f96-cf4d-11e5-9266-169a0fdba4a8.png)

**Comment by josiah-wolf-oberholtzer** [comment]
This typically occurs because ImageMagick isn't installed or isn't
installed correctly.

**Comment by trevorbaca** [comment]
Huhn. Because the installation was a one-line call to ``brew install imagemagick`` on a virgin drive yesterday. (Which seems like that should be about as clean an installation as possible!)

**Comment by josiah-wolf-oberholtzer** [comment]
That may be. Notation is the correct size?

I recall converting Graphviz diagrams to use SVG output, rather than PNG,
so this may simply be a problem with the docs' CSS.

**Comment by trevorbaca** [comment]
Yup notation is correct size throughout!

**Comment by josiah-wolf-oberholtzer** [comment]
OK, I've rebuilt the docs and can verify what you're seeing. Something has changed either in the Sphinx HTML/CSS or the SVG output from Graphviz. Should be simple to restyle the Graphviz-produced SVG to obey the page width again.

**Comment by trevorbaca** [comment]
Great! Thanks for checking. Obviously there's no rush on this because the images are, in fact, still visible and I'm able to use them while composing. Just glad you're able to reproduce what I'm seeing.

Oh, and fwiw, rebuilding the docs on my new workstation shows them behaving better than ever before (even given the graph resizing thing): "source" and "docs" links function well, syntax highlighting is consistently perfect, etc etc. Really looks great (just in the boring ole API pages, which is where I do most my day-to-day work in the docs).

**Comment by josiah-wolf-oberholtzer** [comment]
The problem is being caused by Graphviz explicitly setting `width` and `height` values in `pts` on the SVG element. The SVG image in the page therefore does not inherit the width of the parent container and so runs off the edge. Apparently there's no way to turn this off. I'll have to do a little search-and-replace as a post-processing step in the generated SVG sources.

**Comment by trevorbaca** [comment]
Ah, got it.
