### ISSUE TITLE
Allow hash symbols in markup parser

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#547]
There is apparently no way to initialize ``Markup('foo (#1)')`` right now.

**Comment by josiah-wolf-oberholtzer** [comment]
That should be equivalent to `Markup('foo (1)')`.

**Comment by trevorbaca** [comment]
Looks like the output differs:
```
>>> markup = Markup('foo (1)')
>>> markup
Markup(contents=('foo (1)',))
>>> f(markup)
\markup { foo (1) }
```
What I was looking for is the ability to output the hash symbol directly in the score. So I'm looking for something like ``\markup { foo (#1) }`` in the score. Meaning that the literal text ``#1`` and ``#2`` and so on will appear in the score at the start of new musical events.

**Comment by josiah-wolf-oberholtzer** [comment]
Ah, OK. If the use case is actually printing the hash symbol, then I can maybe work with that. The hash symbol typically means "the following is a Scheme expression".

**Comment by trevorbaca** [comment]
Right, I figured that's what was going on. Not hugely urgent, but just wanted to document that it's a possibility we could grant to extend the range of available markup even further.

**Comment by josiah-wolf-oberholtzer** [comment]
Have you tried writing the above into a LilyPond file by hand? `\markup { foo (#1) }` will fail to parse in LilyPond itself.

Try putting the `#1` inside quotes: `"(#1)"`

**Comment by trevorbaca** [comment]
Yeah I think I'd figured out that in my .ly test file. What's the recommended way to get the markup parser to preserve the quotes on our end?
```
>>> markup = Markup('foo "(#1)"')
>>> markup
Markup(contents=('foo (#1)',))
>>> f(markup)
\markup { foo (#1) }
```

**Comment by josiah-wolf-oberholtzer** [comment]
To preserve the quotation marks: we'll need to improve `Scheme.format_scheme_value()` and `Markup._get_format_pieces()`. Should be fairly simple.

**Comment by trevorbaca** [comment]
Awesome. Thank you!
