### ISSUE TITLE
abjadbooktools.DoctestDirective conflicts with sphinx.ext.doctest.DoctestDirective

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#554]
Our `abjadbook` Sphinx extension cannot be used in combination with Sphinx's built-in `doctest` extension.

Rename `abjadbooktools.DoctestDirective` and `..  doctest::` to something else.

**Comment by trevorbaca** [comment]
Still valid in July 2017.

**Comment by trevorbaca** [comment]
Done in 2.21. Use `docs::` (instead of `doctest::`).
