### ISSUE TITLE
Consider removing templatetools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#595]
Current package contents:
```
GroupedRhythmicStavesScoreTemplate
GroupedStavesScoreTemplate
StringOrchestraScoreTemplate
StringQuartetScoreTemplate
TwoStaffPianoScoreTemplate
```
The intention behind the classes is clear. But it's not clear that the classes are ever getting used. (I never use these classes, for example, even when writing music for piano or string quartet.)

Probably the biggest value the classes offer is in the form of examples that can be taken as starting points for composers who want to implement their own score templates. But a better way of doing this is looking at realworld score packages (hosted, for example, on GitHub).

So we might want to remove `templatetools` from Abjad and find a way of documenting explicitly the best practices for custom score template implementation.

**Comment by josiah-wolf-oberholtzer** [comment]
We use them in examples. You'd be obliging us to rebuild the score template
for *every* high-level example in the docs.

**Comment by trevorbaca** [comment]
Remind me where again?

Grepping shows me TwoStaffPianoScoreTemplate() getting instantiated in the Mozart demo.

Am I missing others?

**Comment by josiah-wolf-oberholtzer** [comment]
I'm using them in a branch for writing up all of the cookbook examples.

**Comment by trevorbaca** [comment]
Great! Then that at least motivates keeping them around.

**Comment by josiah-wolf-oberholtzer** [comment]
Thanks. I'd like us to be more prudent about removing things that have had wide public exposure. Remember that we use the GroupedStavesScoreTemplate in our inaugural paper. People reading that and arriving at the system are going to want to reproduce the examples they see there. We should endeavor to maintain the viability of those sorts of documents (maybe even via tests within the system). I know this puts a damper on our long-standing agile development model, but we are also gaining more exposure now. Users are never going to be as tapped in to our development rhythm as we are, and they also appreciate a little bit of batteries-included.

**Comment by trevorbaca** [comment]
Yes of course. Just remember two things:

1. It only gets *more* difficult to remove things the further along we go. Assuming continued success means increasing numbers of users ;)

2. Some new patterns will overtake older ones, no matter how carefully we proceed. My thoughts about potentially removing `templatetools` come from sketching curricula for Stanford this morning: an important part of the fourth day's material centers on teaching composers how to implement their own score templates. And while I'm still working out what that will look like, I'm pretty sure we'll be directing folks precisely to *not* copy the patterns in `templatetools` ;) Only because we've evolved considerably beyond the patterns there in our own work.

I like things not to break too ;) Just remember that there are still going to be a couple key remaining areas of the system where we're going to want pattern substitution. Hopefully only a few!

**Comment by josiah-wolf-oberholtzer** [comment]
Believe me, I understand the trade-offs. I'm advocating for slowing our
roll. Come to an agreement about deprecation, deprecate the code under
consideration, leave it for one point full point release after deprecation,
and only then remove. And find better systems for  communicating such
breaking changes.

But we do have users now, and these changes need to be careful. Deprecate
and leave it.

Buuut l, I'm also 100% OK with teaching the score template pattern. If you
have new info, I'd love to hear it! I think it's a solid pattern. I've
extended it a little in my own work, but the core is the same.

**Comment by trevorbaca** [comment]
Core of the pattern is the same. Take a look at ...

https://github.com/trevorbaca/akasha/blob/master/akasha/tools/ScoreTemplate.py
https://github.com/trevorbaca/akasha/blob/master/akasha/stylesheets/stylesheet.ily

... for an example of extension.

Basically I *think* the maximally flexible pattern is always to use custom (ie, user-defined) contexts for everything (instead of built-in LilyPond contexts). So ViolinMusicStaff (for example) instead of vanilla Staff.

Easy to do very similarly to existing score templates. But looks different from a user perspective. And needs to be synched with the primary user stylesheet. Both are easy.

The deprecation talk we can have more fully on the phone; I'm sure we align on all the goals of both release and deprecation, entirely. Right now the primary problem isn't how we approach deprecation. It's that there's been no public release in almost two years.

**Comment by josiah-wolf-oberholtzer** [comment]
Looks good. We're basically agreeing with each other.
