### ISSUE TITLE
Option to ask lilypond to render to SVG and use ipython.display.SVG to show it

### ISSUE THREAD

**Issue by chr15m** [Abjad/abjad#606]

**Comment by josiah-wolf-oberholtzer** [comment]
@chr15m To be really pedantic, you mean to use SVG output from LilyPond in an IPython notebook?

Do you care if the resulting SVGs are not cropped (like we do with PNG-format notation)? There'll be a lot of whitespace.

I haven't found a good command-line-only method for automatically cropping SVG images. I don't want to require users to install InkScape. That just seems like overkill.

**Comment by chr15m** [comment]
Hello! Thanks for your quick response.

> you mean to use SVG output from LilyPond in an IPython notebook?

Yes exactly. I found the PNG images don't look so great when the paper is rendered as a PDF.

I discovered that my version of lilypond won't output SVG from the command line anyway. I had success with the `pdf2svg` command on my system but as you said it outputs an entire page.

> automatically cropping SVG images

Ah yes, I see the problem.

It should be possible to measure the bounding box of the SVG and change the viewport bounds. Agree that inkscape is overkill for this.

I will try to investigate whether it's easy to do with any of the following libraries:

 * svgutils
 * pysvg
 * svgfig
 * svg.path

Hypothetically the algorithm should be a reasonably simple matter of iterating over all of the points in the SVG XML file and finding max & min for the x & y components.

I will report back if I have any success with this.

**Comment by josiah-wolf-oberholtzer** [comment]
I totally agree. Our PNGs looks awful. I've never been able to find a satisfactory set of conversion options in ImageMagick.

If you can figure out the cropping issue without resorting to non-pip-installable dependencies, I'll finally be able to use all-SVG output in our HTML docs too.

**Comment by chr15m** [comment]
Good news! After fiddling with parsing SVG files for a couple of hours I had some good luck with a search and found that the following command already generates a cropped SVG:

`lilypond -dpreview -dbackend=svg input.ly`

Source: http://comments.gmane.org/gmane.comp.gnu.lilypond.general/60073

\o/

If you end up integrating this functionality note that the lilypond that ships with Ubuntu 14.04 (LTS) is version `2.16.2` and that version won't do svg output correctly - it generates an invalid SVG that Inkscape won't read. Version `2.18.2` downloaded from the website works great however. Might be something to add to the docs for the SVG export.

**Comment by josiah-wolf-oberholtzer** [comment]
I've been under the impression that it removes all but the first system before cropping (hence "preview"). So no multi-system multi-page output.

**Comment by josiah-wolf-oberholtzer** [comment]
See discussion here: http://lilypond.1069038.n5.nabble.com/Cropped-SVG-Output-td182397.html

**Comment by chr15m** [comment]
Ah yes you're right. Ok, I'll keep hacking.

**Comment by chr15m** [comment]
I've got a basic SVG crop working. What this code does is examine the lines of the staff, apply a margin, and adjust the SVG head's width, height, and viewPort values so that the SVG only shows the staff area.

There is an optional setting for using a threshold at which to do this (so if the staff is wider than 50% of a page it will only do a vertical crop). There is also an option for specifying how much of a margin you want.

I think it would be great if these were options to `abjad.show()` with e.g. the following defaults:

    abjad.show(format="svg", crop=True, always_crop=True, svg_margin=7)

The following zipfile contains examples of SVGs I have created using scores downloaded from the Abjad site and rendered with lilypond, as well as the ones adjusted using this code (ending in `-cropped.png`):

[svg-crop-abjad.zip](https://github.com/Abjad/abjad/files/310754/svg-crop-abjad.zip)

Here is the source code of `crop.py` for your reference - it does not depend on anything except Python itself:

```
#!/usr/bin/env python

import sys
import re
from xml.dom import minidom

re_commaspace = re.compile(", +")

def extract_element_translation(s):
    return [float(x) for x in re_commaspace.split(s.replace("translate(", "").replace(")", ""))]

def get_element_bounding_box(el):
    translation = extract_element_translation(el.getAttribute("transform"))
    x1 = float(el.getAttribute("x1"))
    x2 = float(el.getAttribute("x2"))
    return [x1 + translation[0], translation[1], x2 + translation[0], translation[1]]

def totalbb(bbs):
    return [[min, max][int(s / 2)]([x[s] for x in bbs]) for s in range(4)]

def adjust_svg_bounding_box(svg_in, margin=7, always_crop=False):
    # parse the SVG document
    doc = minidom.parseString(source)
    # get the first tag and extract the viewbox and width/height
    svgtag = doc.getElementsByTagName("svg")[0]
    viewBox = [float(x) for x in svgtag.getAttribute("viewBox").split(" ")]
    width = float(svgtag.getAttribute("width")[:-2])
    height = float(svgtag.getAttribute("height")[:-2])
    # calculate the zoom ratio from the viewbox
    ratio_horizontal = width / viewBox[2]
    ratio_vertical = height / viewBox[3]
    # get the bounding boxes of all lines in the staff
    bbs = [get_element_bounding_box(el) for el in doc.getElementsByTagName("line") if el.getAttribute("y1") == el.getAttribute("y2")]
    # compute the overall bounding box of the staff lines
    boundingbox = totalbb(bbs)
    # compute the new width and height with a margin
    new_width = (boundingbox[2] - boundingbox[0]) + margin * 2
    new_height = (boundingbox[3] - boundingbox[1]) + margin * 2
    # get the head line of the original SVG and the rest of the document
    firstline, rest = source.split("\n", 1)
    # perform the crop by updating the bounding box
    # if the staff is wider than 50% of the page do a height-only crop
    # unless always_crop is selected in which case we just get the staff with margin no matter what
    if always_crop or (boundingbox[2] - boundingbox[0]) < viewBox[3] * 0.5:
        new_bounds = [new_width * ratio_horizontal, new_height * ratio_vertical, boundingbox[0] - margin, boundingbox[1] - margin, new_width, new_height]
    else:
        new_bounds = [width, new_height * ratio_vertical, viewBox[0], boundingbox[1] - margin, viewBox[2], new_height]
    # finish up and return the results
    doc.unlink()
    return '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.2" width="%fmm" height="%fmm" viewBox="%f %f %f %f">' % tuple(new_bounds) + rest

if len(sys.argv) > 1:
    filename = sys.argv[1]
    # read in the SVG
    source = file(filename).read()
    # get the adjusted version with modified SVG head
    cropped_svg = adjust_svg_bounding_box(source, always_crop=True)
    # write the SVG with the updated header
    out = file(filename.replace(".svg", "-cropped.svg"), "w")
    out.write(cropped_svg)
    out.close()
else:
    print "Usage:", sys.argv[0], "SVG-FILE"
```

I don't know the internals of Abjad well enough to dive in and get this working in the code itself, but let me know if you'd like me to do that and issue a pull-request. Hope this helps!

**Comment by josiah-wolf-oberholtzer** [comment]
Hmm. I'm still worried that this isn't general enough.

Why not just bite the bullet and use ImageMagick's `info` output?

Before cropping:

```
(supriya) ✔ [joberholtzer@josiah] ~/Downloads/svg-crop-abjad 
14:57 $ convert -density 200 lilypond-1afa912131367a351bf603fb2fb439368033a810.svg info:-
lilypond-1afa912131367a351bf603fb2fb439368033a810.svg MVG 1652x2338 1652x2338+0+0 16-bit sRGB 39.8KB 0.000u 0:00.000
```

After cropping:

```
(supriya) ✔ [joberholtzer@josiah] ~/Downloads/svg-crop-abjad 
14:57 $ convert -density 200 lilypond-1afa912131367a351bf603fb2fb439368033a810.svg -trim info:-
lilypond-1afa912131367a351bf603fb2fb439368033a810.svg MVG 1330x226 1652x2338+200+87 16-bit sRGB 0.000u 0:00.000
```

And to compare against the units in the original SVG:

```
(supriya) ✔ [joberholtzer@josiah] ~/Downloads/svg-crop-abjad 
14:57 $ head -n 1 lilypond-1afa912131367a351bf603fb2fb439368033a810.svg 
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.2" width="210.00mm" height="297.00mm" viewBox="0 0 132.7795 187.7882">
```

If you calculate the ratio of ImageMagick's claimed dimensions against those in the SVG, you can use the trimmed info output to calculate new bbox and height/width.

We already assume that people have ImageMagick in order to build the docs, so this isn't really a new dependency.

**Comment by josiah-wolf-oberholtzer** [comment]
After trying that technique, it's unfortunately apparent that ImageMagick can only locate the staff-lines automatically, and no other shapes. That means no generalized cropping via IM. 😢 

I really want a general solution so I can simply activate SVG LilyPond output as a blanket setting.

Going to try Inkscape-based cropping now instead.

**Comment by chr15m** [comment]
@josiah-wolf-oberholtzer I understand. What about rendering to PNG and then calculating the bounds changes before and after trim as a percentage?

It seems to me there are several cases for different cropping:

 1. When you have several full pages of score you don't really want any of them to be cropped at all.
 2. When you have a multi-line e.g. half page of staffs you probably only want them cropped vertically.
 3. When you have a small snippet you probably want it cropped completely.

Does that sound right to you? I guess it would be handy to have sensible defaults and then give the user the option to override them.

**Comment by josiah-wolf-oberholtzer** [comment]
During a double LilyPond render (once as SVG, once as PNG) and then cropping the PNG to find the bounds could work. Sort of disappointing that it would come to that.

Here's a sketch using Inkscape to get bounds info. It doesn't work yet, because I don't understand how the units relate between what Inkscape says and what's actually used in the SVG.

```
#! /usr/bin/env python
import os
import subprocess
import sys
from xml.dom import minidom


def get_inkscape_info(file_path):
    file_path = os.path.abspath(file_path)
    command = 'inkscape -z -S {!s}'.format(file_path)
    output = subprocess.check_output(command, shell=True)
    if sys.version_info[0] == 3:
        output = output.decode('utf-8')
    for line in output.splitlines():
        if line.startswith('svg'):
            return [float(_) for _ in line.split(',')[1:]]


def crop(file_path):
    with open(file_path, 'r') as file_pointer:
        document = minidom.parseString(file_pointer.read())
    svg_tag = document.getElementsByTagName('svg')[0]
    x, y, width, height = get_inkscape_info(file_path)
    bbox = ' '.join(str(_) for _ in (x, y, width + x, height + y))
    print(bbox)
    svg_tag.setAttribute('height', str(height) + 'px')
    svg_tag.setAttribute('width', str(width) + 'px')
    svg_tag.setAttribute('viewBox', bbox)
    #svg_tag.setAttribute('preserveAspectRatio', 'xMinYMin')
    file_path, _ = os.path.splitext(str(file_path))
    file_path = '{}-cropped.svg'.format(file_path)
    with open(file_path, 'w') as file_pointer:
        document.writexml(file_pointer)


if __name__ == '__main__':
    file_path = sys.argv[1]
    crop(file_path)
```

**Comment by FabriceSalvaire** [comment]
I am looking for a similar feature for Sphinx ...

Seems there issues with font handling
```
<text transform="translate(39.0936, 5.7941)" font-family="emmentaler-14" font-size="2.8284">
<altglyph glyphname="noteheads.s2"/><!-- FIXME: how to select glyph by name, altglyph is broken? -->&#57757;</text>
```

When we crop a document in Inscape, It recomputes all the coordinates, e.g. it removes all the transformations. We have thus to process each element and apply a translation. Then we can update the viewbox. But we need a full SVG rendere to get the bbox.

Unfortunately, Inkscape seems not able to crop an SVG output from the command line.

Maybe there is another solution in HTML: crop the svg in the browser

**Comment by FabriceSalvaire** [comment]
Found this ! But it requires gui ... --without-gui crashes Inkscape

`inkscape --verb=FitCanvasToDrawing --verb=FileSave --verb=FileQuit in.svg`

**Comment by josiah-wolf-oberholtzer** [comment]
@FabriceSalvaire Yes, I'm aware of Inkscape as a tool to do this. However, I would prefer not to use it as it overly complicates an already complex install process.

In better news, a LilyPond contributor is currently working on adding cropping to the SVG backend in LilyPond itself: https://codereview.appspot.com/326960043/

I don't know when these new cropping abilities will arrive in the development version of LilyPond. But once they do arrive, I will modify our documentation system (including IPython) to use them.

**Comment by 3id0** [comment]
Just wanted to say that I would like to have the ability to output SVG too. Cheers.

**Comment by josiah-wolf-oberholtzer** [comment]
@3id0 I'm still waiting to find out when the `-dcrop` option for cropping SVG output in LilyPond will be merged. Once the LilyPond developers allow that change in - even just to the unstable version of LilyPond - I'll jump on this.

**Comment by trevorbaca** [comment]
Leaving open in January 2019.

**Comment by sbowa** [comment]
<p>The option for <b>cropping SVG</b> output in LilyPond seems to be there according to:<br/>
<br/>
<a href="https://sourceforge.net/p/testlilyissues/issues/5165/">https://sourceforge.net/p/testlilyissues/issues/5165/</a><br/>
<a href="http://lilypond.org/doc/v2.19/Documentation/changes-big-page.html">http://lilypond.org/doc/v2.19/Documentation/changes-big-page.html</a> (search term '-dcrop')<br/>
<br/>
(Tested in LilyPond 2.19.83 and works like a charm.)</p>

**Comment by josiah-wolf-oberholtzer** [comment]
@sbowa I'm not totally happy with the `-dcrop` output. Wish it did it by individual system, rather than smashing all systems into a single SVG, disregarding any spacing setup between them.

**Comment by trevorbaca** [comment]
Closing.

LilyPond's SVG cropping appears now (2021-02) to work in all cases except one: when LilyPond crops multisystem output, LilyPond removes whitespace between systems.

The LilyPond developers know about this. When the LilyPond team change the cropping behavior to support inter-system whitespace, Abjad users will see those changes reflected.
