### ISSUE TITLE
Remove handlertools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#612]
Functionality no longer supported.

(Backstory: the classes in the `handlertools` package were specific to my own way of composing. My assumption was that, with time, I would extend the classes in such a way that they would become sufficiently general-purpose to be used easily by other composers. But this has not been the fate of these classes. There are better ways of working with the system and so I'll be removing the entire package. Importantly, `handlertools` was never the subject of a formal announcement to the community.)

**Comment by josiah-wolf-oberholtzer** [comment]
👍
