### ISSUE TITLE
Consider removing DivisionCallback classes from experimental.makertools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#615]
This should be doable because (presumably) most users aren't using much of anything in `experimental`.

Is anyone using any of the following six classes?:
```
experimental.makertools.DivisionMaker
experimental.makertools.FlattenDivisionCallback
experimental.makertools.FuseByCountsDivisionCallback
experimental.makertools.PartitionDivisionCallback
experimental.makertools.SplitByDurationsDivisionCallback
experimental.makertools.SplitByRoundedRatiosDivisionCallback
```
I implemented all six classes to model things in my own rhythmic practice.

I'm still using all six classes (and getting benefit from them). But I'm about to do a significant amount of refactoring the classes, possibly even resulting in the classes disappearing and being replaced transparently by pure expressions.

So my plan is to remove all six classes from experimental and migrated into my own composition packages during refactoring.

Lemme know if someone is, by some miracle, already using some of these classes. Will wait a day or two before removal.

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not using these. @jdavancens?

**Comment by jdavancens** [comment]
Nope!

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca Kill 'em. In searching all of GitHub, I can't find anyone else using these.

**Comment by trevorbaca** [comment]
K, doing it ...
