### ISSUE TITLE
Adjust python 3.4 performance test

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#622]
Travis reports this break after a recent commit:
```
______________ test_systemtools_IOManager_count_function_calls_01 ______________
    def test_systemtools_IOManager_count_function_calls_01():
    
        result = systemtools.IOManager.count_function_calls(
            "Note('c4')",
            globals(),
            )
        if sys.version_info[0] == 2:
            assert result < 14000
        else:
>           assert result < 19500
E           assert 21940 < 19500
```
Although I'm not sure why it now takes a couple thousand more function calls to instantiate a note under Python 3.4, the fix is simply to raise the numeric threshold (from 19500 function calls to, say, 23000 function calls).

**Comment by trevorbaca** [comment]
Although now I'm confused because pulling onto my local machine shows this to be fixed already!

Restarted build on Travis. (Perhaps Travis was reporting a false positive.)

**Comment by josiah-wolf-oberholtzer** [comment]
Sometimes this can happen when the parser tables need to be rebuilt for whatever reason. Without actually tracing the function call we can't really say.

**Comment by josiah-wolf-oberholtzer** [comment]
Actually, are you looking at this Travis-CI run?: https://travis-ci.org/Abjad/abjad/jobs/125466334

I added a release tag for 2.16, backdated to May of last year. I really don't know why Travis keeps running this one. Ignore it.

**Comment by trevorbaca** [comment]
Yes! That was the one, exactly!

Ok, will ignore.

**Comment by trevorbaca** [comment]
Hey @josiah-wolf-oberholtzer does it matter that https://travis-ci.org/Abjad/abjad continues to show all the builds in a failed state? Will be making (and incorporating) a PR in just a minute, and don't wanna generate confusion on Travis.

**Comment by josiah-wolf-oberholtzer** [comment]
Always look at what branch that Travis report is for. That failure is not
on master - it's on one of my branches.

**Comment by josiah-wolf-oberholtzer** [comment]
I admit, I think of the Travis interface is confusing. It always tells you
about the most recent results, no matter what branch.

**Comment by trevorbaca** [comment]
Then that'll mean that the commit I just pushed will test and then push those test results topmost? Which should be fine because the new commit should pass all the tests ;)

Ok, yeah, I see the "branches" tab in Travis now. Huh, interesting. Is that why you removed the tox file the other day? Was it causing the tests to fail against all of the 'feature' branches I was creating?

**Comment by josiah-wolf-oberholtzer** [comment]
1) Yup, the results from your commit - assuming it's the most recent - will become the topmost!

2) No, the tox.ini file was totally unused, wasn't working correctly, and has been obsoleted by Travis-CI. The point of the tox.ini file was to run the test suite against multiple versions of Python in isolated environments. Travis takes care of that better than Tox could!

**Comment by trevorbaca** [comment]
1. Awesome, and yup: (topmost) results log in Travis is now green and shiny.

2. Got it!
