### ISSUE TITLE
Design an icon for Abjad's umbrella organization.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#624]
I'm tired of seeing the default Github icon for everything related to Abjad. That same default icon appears just about anywhere you post about Abjad.

We should finally bite the bullet and design something - anything - to brand the project with.

**Comment by josiah-wolf-oberholtzer** [comment]
![abjad-logo](https://cloud.githubusercontent.com/assets/5505674/14804725/b2f16cfa-0b1a-11e6-81ff-fe758d3ec4f1.png)

**Comment by trevorbaca** [comment]
Wow, that's actually pretty striking.

The compositing of the Roman and Arabic really strongly appeals!

**Comment by josiah-wolf-oberholtzer** [comment]
We can always change it. But I figure better to have some branding than none.

**Comment by trevorbaca** [comment]
Yup, agreed.

**Comment by trevorbaca** [comment]
Closing because I see you've already posted!
