### ISSUE TITLE
Consider removing unused Leaf._get_leaf_index()

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#636]
Anyone have any opinions on removing unused private `Leaf._get_leaf_index()`?

Implementation:

```
    def _get_leaf_index(self):
        self._update_now(offsets=True)
        return self._leaf_index
```

Method is only called in the (private) py.test file `tools/scoretools/test/test_scoretools_Leaf__get_leaf_index.py`.

Theoretically no one should be using the method because no one knows it's there. If there are no objections I'll remove.

**Comment by josiah-wolf-oberholtzer** [comment]
I didn't know about it. And it's not used in any of my composition code or scores. Go ahead and remove it.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Done in 2.21.
