### ISSUE TITLE
Consider initializing a single session-global LilyPondParser

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#639]
The following is an interesting discovery but isn't urgent.

It turns out that firing up the parser takes a lot of time.

Here're a pair of test functions:
```
def create_notes(count=1, bypass_parser=False):
    for _ in range(count):
        if bypass_parser:
            Note(NamedPitch('C4'), Duration(1, 4))
        else:
            Note("c'4")

def profile_create_notes(count=1, bypass_parser=False):
    expr = 'create_notes(count={}, bypass_parser={})'
    expr = expr.format(count, bypass_parser)
    systemtools.IOManager.profile_expr(expr, line_count=24)
```
It takes about 45 seconds to create a thousand notes with the parser:
```
>>> profile_create_notes(count=1000)
Thu Apr 28 14:01:17 2016

         13726428 function calls (13578678 primitive calls) in 44.310 seconds

   Ordered by: cumulative time
   List reduced from 414 to 24 due to restriction <24>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   44.310   44.310 <string>:1(<module>)
        1    0.004    0.004   44.310   44.310 abjad_tmp.py:39(create_notes)
2000/1000    0.051    0.000   44.306    0.044 Note.py:40(__init__)
     1000    0.027    0.000   42.322    0.042 LilyPondParser.py:206(__init__)
     1000    0.082    0.000   42.214    0.042 Parser.py:31(__init__)
     1000    0.144    0.000   38.548    0.039 yacc.py:3191(yacc)
     1000    0.909    0.001   33.365    0.033 yacc.py:1980(read_pickle)
     6000   31.957    0.005   31.957    0.005 {cPickle.load}
     1000    0.172    0.000    3.345    0.003 lex.py:860(lex)
     1000    0.004    0.000    1.996    0.002 yacc.py:2924(get_all)
     1000    0.589    0.001    1.987    0.002 yacc.py:3104(get_pfunctions)
     1000    0.003    0.000    1.966    0.002 lex.py:577(validate_all)
     1000    0.269    0.000    1.896    0.002 lex.py:729(validate_rules)
976296/878292    0.498    0.000    1.765    0.000 {getattr}
     1000    0.007    0.000    1.561    0.002 LilyPondParser.py:232(__call__)
     4000    0.020    0.000    1.548    0.000 AbjadObject.py:81(__repr__)
     4000    0.018    0.000    1.528    0.000 StorageFormatManager.py:405(get_repr_format)
     1000    0.150    0.000    1.422    0.001 _parse.py:10(_parse)
     1000    0.435    0.000    1.170    0.001 lex.py:832(validate_module)
    10000    0.052    0.000    1.131    0.000 AbjadObject.py:103(_repr_specification)
     2000    0.003    0.000    1.093    0.001 AbjadObject.py:99(_one_line_menu_summary)
    10000    0.079    0.000    0.981    0.000 new.py:5(new)
     1000    0.003    0.000    0.879    0.001 yacc.py:286(__init__)
     1000    0.546    0.001    0.876    0.001 yacc.py:313(set_defaulted_states)
```
Bypassing the parser it takes only a fraction of a second to produces 1000 notes.

This is a performance increase of about 120 times:
```
>>> profile_create_notes(count=1000, bypass_parser=True)
Thu Apr 28 14:02:35 2016

         329004 function calls (328004 primitive calls) in 0.360 seconds

   Ordered by: cumulative time
   List reduced from 112 to 24 due to restriction <24>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.360    0.360 <string>:1(<module>)
        1    0.004    0.004    0.360    0.360 abjad_tmp.py:39(create_notes)
     1000    0.012    0.000    0.298    0.000 Note.py:40(__init__)
     1000    0.001    0.000    0.191    0.000 NamedPitch.py:260(__hash__)
     1000    0.001    0.000    0.190    0.000 Pitch.py:93(__hash__)
2000/1000    0.001    0.000    0.189    0.000 {repr}
     1000    0.003    0.000    0.188    0.000 AbjadObject.py:81(__repr__)
     1000    0.004    0.000    0.185    0.000 StorageFormatManager.py:405(get_repr_format)
     1000    0.005    0.000    0.109    0.000 AbjadObject.py:103(_repr_specification)
     1000    0.008    0.000    0.078    0.000 new.py:5(new)
     1000    0.004    0.000    0.065    0.000 new.py:10(update_dictionaries)
     1000    0.003    0.000    0.063    0.000 Leaf.py:35(__init__)
     2000    0.011    0.000    0.059    0.000 NamedPitch.py:43(__init__)
    35000    0.014    0.000    0.055    0.000 {isinstance}
    23000    0.027    0.000    0.047    0.000 abc.py:128(__instancecheck__)
     1000    0.005    0.000    0.042    0.000 StorageFormatManager.py:351(get_keyword_argument_dictionary)
     1000    0.038    0.000    0.038    0.000 {dir}
     1000    0.001    0.000    0.036    0.000 Note.py:250(written_duration)
     1000    0.002    0.000    0.035    0.000 Leaf.py:686(written_duration)
     1000    0.011    0.000    0.034    0.000 StorageFormatManager.py:173(get_format_pieces)
     1000    0.005    0.000    0.033    0.000 StorageFormatManager.py:368(get_keyword_argument_values)
     3000    0.005    0.000    0.032    0.000 Duration.py:137(__new__)
    34000    0.010    0.000    0.029    0.000 {getattr}
     1000    0.004    0.000    0.026    0.000 NamedPitch.py:429(_storage_format_specification)
```
What's taking all the time? The profiler output makes it look like it's the parser's `__init__()` method that takes almost all the time. A quick glance at the code makes it seem like this is likely because it looks like the parser may be performing a disk-read at every call to `__init__()`.

If this is true, then it is possible some of our users might experience a tremendous speed increase if we change the time(s) at which the parser(s) are initialized.

Now: parser is initialized every time the user creates a component with parseable (string) input (like `Note("c'4")`. Creating 1000 notes means firing up 1000 different parsers. (Parser has lexical scope.)

Possible future: parser is initialized only at the beginning of an Abjad session (and stored somewhere in global namespace). Creating 1000 notes will mean firing up exactly 1 parser. (Parser will have dynamic scope.)

If this thinking is correct, then this is actually a very happy discovery: it's not that we've mis-modeled anything in the parser itself (or themselves, if we think about the markup parser, too, which admits to this same analysis). Rather, it's that we mis-modeled *the time at which* parsers should initialize.

Important: what type of users would benefit from such a change?

Interestingly, some ad hoc testing shows that my own scores won't benefit from this change much at all. Why not? Because I use the rhythm-makers exclusively in my own scores. And it turns out that the rhythm-makers make no calls to the parser at all. (This is possible because the rhythm-makers all wrap the ancient `scoretools.make_notes()` function, which isn't dependent on the parser primarily because all output is unpitched and set to C4 by default.)

But would other types of user see benefit from a move to a session-global parser? It seems possible that newcomers to the system might benefit the most from such a change. Because it's a certainty that there are users out there, somewhere, who are initializing lists of notes (and everything else) in loops exactly as shown in the test functions, above. In fact, I think we would assume that this would be the behavior of almost every newcomer to the system for quite awhile (and possibly indefinitely). So while the user forecast is speculative, it's possible that almost all users not currently using the rhythm-makers might see a substantial performance increase in their own work that would be visible at every call to the interpreter in their own workcycle.

(The background here is that I'm optimizing a bunch of stuff in my own practice this week. So I've got the profiler open and I'm ruling out cases of false optimization. This case appeared early on because I saw a 1000x speed increase when building test scores to inspect! ;)

**Comment by josiah-wolf-oberholtzer** [comment]
Yup, the parser is very heavy-weight. And it does read from the filesystem in order to pull in pickled parser tables (which are even more expensive to build from scratch).

I would look at using `topleveltools.parse()` inside `scoretools.Container._parse_string()`. You'll want to instantiate the appropriate parsers as private module-level variables in `topleveltools.parse()` and just reference them directly. Take care to handle the possibility of different note-name languages (en, de, fr, etc.): you'll need a separate LilyPond parser for each language. I can work on streamlining that in the future.
