### ISSUE TITLE
Make _storage_format_specification a method.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#641]
There are currently two format-related properties on AbjadObject subclasses:
- `_storage_format_specification`
- `_repr_specification`

When `hasattr(..., '_storage_format_specification')` is called on an AbjadObject subclass instance, the property is evaluated. Then, typically, the property is accessed. This effectively totals a double evaluation of configuring and instantiating a StorageFormatSpecification object.

We should convert all such properties to `_get_...()` methods to avoid these double evaluations triggered by `hasattr()`.

**Comment by trevorbaca** [comment]
In June 2017 `_get_storage_format_specification()` now exists.

There are what look to be ancient (and probably unused) references to `_repr_specification` in `StorageFormatAgent`:
```
tools/systemtools/StorageFormatAgent.py
85:            hasattr(self._client, '_repr_specification') or
306:            spec = getattr(self._client, '_repr_specification', None)
309:                via = '_repr_specification'
596:            '_repr_specification' in dir(self._client) or
597:            hasattr(self._client, '_repr_specification') or
609:            specification = getattr(self.client, '_repr_specification',
621:            specification = getattr(self.client, '_repr_specification',
```
Will leave issue open until `_repr_specification` references are removed from `StorageFormatAgent`.

**Comment by trevorbaca** [comment]
Done in 2.21.
