### ISSUE TITLE
Verify Windows support.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#642]
None of Abjad's developers use or perhaps even have access to a Windows machine.

**Comment by filmor** [comment]
What exactly do you want verified here? The test suite passes (can't confirm for the PDF tests right now as I don't have PyPDF2 installed).

**Comment by josiah-wolf-oberholtzer** [comment]
Hi @filmor, I've run the full battery, built the docs etc. in a Windows 10 virtual machine. All works. Just neglected to close the issue.
