### ISSUE TITLE
Remove tab-completion

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#653]
Users should put tab-completion logic in their own Python startup files. The tab-completion logic is un-testable and liable to cause issues on various platforms (Windows, etc.).

**Comment by trevorbaca** [comment]
Agreed.

And FWIW I never use the tab completion currently in the system.

**Comment by josiah-wolf-oberholtzer** [comment]
I use it all the time, but I think users should set it up for themselves manually via `PYTHONSTARTUP`: https://docs.python.org/2/using/cmdline.html#envvar-PYTHONSTARTUP

**Comment by trevorbaca** [comment]
Excellent. I'll set locally too ...

**Comment by trevorbaca** [comment]
Is this still valid in June 2017?

**Comment by trevorbaca** [comment]
Done in 2.21.
