### ISSUE TITLE
Implement rename, delete and copy flags for score package scripts

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#697]
Should apply to segments, materials and build targets.

Renaming materials and segments should update names within the score package.
- `--copy SOURCE TARGET` / `-Y SOURCE TARGET`
- `--rename SOURCE TARGET` / `-M SOURCE TARGET`
- `--delete SOURCE` / `-D SOURCE TARGET`

**Comment by trevorbaca** [comment]
Experience from the IDE shows that this is tricky!

**Comment by josiah-wolf-oberholtzer** [comment]
It's not too hard. I have these flags implemented on a set of sister scripts in `supriya`:

- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/tools/commandlinetools/ProjectSectionScript.py#L38
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/tools/commandlinetools/ProjectSectionScript.py#L51
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/tools/commandlinetools/ProjectSectionScript.py#L108

**Comment by trevorbaca** [comment]
Moved to Abjad/abjad-ext-cli issue 3.
