### ISSUE TITLE
Remove pitchtools.PitchClassTree

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#700]
I added the class a couple of years ago, but I would find it surprising if anyone else had integrated the class into their own music!

Is anyone else using the class? Ok to remove? (Class will be ported to my `baca` Python package, publicly available on GitHub.)

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not using them.

**Comment by trevorbaca** [comment]
Cool.

**Comment by trevorbaca** [comment]
Done.
