### ISSUE TITLE
Remove datastructuretools.PayloadTree, datastructuretools.CyclicPayloadTree

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#701]
I added the classes a couple of years ago to model certain abstractions of pitch structure.

Is anyone else using the classes? Ok to remove? (Both classes will be available in my `baca` package, publicly available on GitHub.)

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not using them.

**Comment by trevorbaca** [comment]
Cool.

**Comment by trevorbaca** [comment]
Done.
