### ISSUE TITLE
Remove Duration.yield_durations() and Duration.yield_equivalent_durations()

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#708]
Both methods are probably left over from my own compositional practice.

If no one else is using the methods I'll out-migrate.

**Comment by josiah-wolf-oberholtzer** [comment]
I can't find any usage in my own scores.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Done in 2.21.
