### ISSUE TITLE
Implement indicatortools.LilyPondLiteral to generalize LilyPondCommand & LilyPondComment

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#747]
`LilyPondCommand` and `LilyPondComment` differ only slightly:
- `LilyPondCommand` prepends a backslash prior to contents.
- `LilyPondComment` prepends a percent sign prior to contents.

Implement a new `LilyPondLiteral` that will prepend nothing to contents.

This will give composers an important affordance: the ability  to insert arbitrary text in any LilyPond file.

(Question: is `LilyPondLiteral` the best name? Maybe `LilyPondString`? Or `LilyPondVerbatim`? Other suggestions?)

(Question: deprecate `LilyPondCommand` and `LilyPondString` after implementation? Or leave for backwards compatibility?)

**Comment by josiah-wolf-oberholtzer** [comment]
`RawLilyPond`? Just `LilyPond`?

All of this is getting at the idea of an attachable, formattable string, but LilyPond already has a notion of "strings" due to its Scheme integration. Likewise, "literal" is sometimes a term used in CS - could be confusing.

I'm leaning towards `LilyPondVerbatim`.

**Comment by trevorbaca** [comment]
LilypondLiteral now available in 2.21. Quite happy to change name!

**Comment by josiah-wolf-oberholtzer** [comment]
Naw, LilyPondLiteral is fine.

**Comment by trevorbaca** [comment]
Done in 2.20.
