### ISSUE TITLE
Remove "direction" from indicator classes; add to attach()

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#748]
What if `direction` wasn't a property of classes like `Markup`, but was instead a property of the `IndicatorExpression` class? While definitely a breaking change, it could really simplify many classes in the system.

Consider the use of the `direction` keyword throughout the `Markup` classes many methods, especially the markup command methods. How much simpler would all of those methods be if one didn't need to worry about applying or propagating a direction? Probably a lot.

To provide a direction while attaching, you would use `attach()` like so:

```
attach(my_markup, my_component, direction=Up)
```

This could also be done for "directed" spanners.

**Comment by trevorbaca** [comment]
I've had this thought a lot recently, too. Think it's a really good idea.

Any new reasons come up why we shouldn't?

**Comment by josiah-wolf-oberholtzer** [comment]
I was just bitten by this again when updating my scores for the 2.20 changes, where a direction which was `None` in a previous version became `Center`, and that direction indication showed up in an override, where it's a LilyPond syntax error:

```
\override NoteHead.text = - \markup { \triangle #f }
```

I think the only reason not to make this change would be backward compatibility concerns. But we would also have to provide a way to indicate which indicators (and spanners) can be directed, and to pass in the direction into their formatting logic from outside.

**Comment by trevorbaca** [comment]
Question still valid in June 2017.

**Comment by trevorbaca** [comment]
Accepted. Will refactor.

**Comment by trevorbaca** [comment]
For future consideration: should we do the same with `format_slot`?

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not sure about `format_slot`, but it seems fruitful!

Honestly, this issue was 99% about markup and 1% about articulations, which I should have done a better job describing in the description. I wasn't thinking about other types of indicators, only those that LilyPond mandates have Up/Center/Down directions. Markup seemed like a perfect choice for removing direction because we compose complex markup often in our work, and guaranteeing / predicting when and how direction cascades through those generative methods is tricky! (And because there are plenty of places in LilyPond where you want to suppress direction entirely!).

Direction is something that's a clear concept from the LilyPond docs, while `format_slot` is our invention and maybe less concrete than users. However there are a few indicators that we've historically needed to tweak the format slot on. One way to approach this would be to preserve a default format slot on the class level, and allow overriding that default when attaching, storing the user-supplied value in the indicator wrapper. That could be really useful!

At format time, we could pass in the direction (Up/Center/Down or None), the format slot, and the attached-to components as keywords to the indicator's `_get_lilypond_format_bundle()` method. The indicator could then choose what to do with them.

**Comment by trevorbaca** [comment]
Still valid in January 2019.

**Comment by trevorbaca** [comment]
Another candidate for this sort of refactor has emerged over the last year: the `leak` property I've added to all the indicators that appear amenable to LilyPond's so-called "empty chord" `<>` construct.

That functionality is currently implemented as a property on more than a dozen indicators. But I **think** the property can be removed from the indicators and added as `abjad.attach(..., leak=None)` and `abjad.Wrapper.leak`.
