### ISSUE TITLE
Audit necessity of all __eq__ implementations

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#750]
Many `__eq__()` and `__hash__()` implementations may be redundant.

They should be removed and/or refactored with `super()` calls.

This is especially relevant to subclasses of `AbjadValueObject`. Most overridden functions on `AbjadValueObject` subclasses can probably consist solely of docstring examples and a call to `super(...)__method_name__()`.

Methods to check:
- [ ] `__copy__()`
- [x] `__eq__()`
- [ ] `__format__()`
- [ ] `__getnewargs__()`
- [x] `__hash__()`
- [x] `__ne__()`
- [ ] `__repr__()`

Audits have to be done by hand.

**Comment by trevorbaca** [comment]
Agree strongly.

Also wonder if some (or even all) of these can simply be eliminated once we drop support for Python 2. (Seem to remember that the default way Python 3 handles equality-testing is basically exactly the way we implemented on AbjadObject. Or at least that's one of the motivations I remember for implementing AbjadObject in the first place. So it's possible that we may be able to eliminate a number __eq__ and other dunder definitions entirely with the move to 3.)

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Looks like `__hash__()` needs to be defined explicitly for only `AbjadValueObject` and `Selection`.

**Comment by trevorbaca** [comment]
Added commit that cleans up many (but not all) `__eq__()` definitions.

It remains problematic to strip custom equality-testing from classes in these packages:

* pitchtools
* quantizationtools
* schemetools
* tonalanalysistools

Not quite sure what's going on. But I think it has something to do with complicated `__init__(self, *arguments)` signatures.

**Comment by trevorbaca** [comment]
Both `abjad.AbjadObject` and `abjad.AbjadValueObject` are removed in 3.1.

Dunder methods are now just implemented on an as-needed basis on each class in the system.
