### ISSUE TITLE
Audit order of ### ... ### sections

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#751]
Abjad's class section comments should be in a consistent order:

- [ ] `### CLASS VARIABLES ###`
- [ ] `### CONSTRUCTOR ###`
- [ ] `### INITIALIZER ###`
- [ ] `### SPECIAL METHODS ###`
- [ ] `### PRIVATE METHODS ###`
- [ ] `### PUBLIC METHODS ###`
- [ ] `### PRIVATE PROPERTIES ###`
- [ ] `### PUBLIC PROPERTIES ###`

Write a script to verify that these section headers appear in the order expected, whenever they appear. Not all section headers appear in every class file. Some class files may include other section headers, notably in `lilypondparsertools` where they often group production rules by the name of the LH symbol.

Also verify that:
- [ ] _methods_ sections only contain methods
- [ ] _properties_ sections only contain properties
- [ ] section headers are not repeated

**Comment by ajyoon** [comment]
Anyone working on this? If not I'd be happy to take it on.

**Comment by josiah-wolf-oberholtzer** [comment]
@ajyoon Nope! Go ahead!

I'll just say that:
- Not all section headers appear in every class .py file.
- There are probably a few class files with headers that aren't listed here, mainly in `lilypondparsertools` (and in that package, that's fine).
- But I could be wrong about that.

**Comment by ajyoon** [comment]
I was thinking of just writing a script which crawls the whole codebase for classes and flags errors. Thoughts on just making this a uniform fix across the board for all nontrivial classes, and adding sections headers where omitted? The diff may end up being quite large, depending...

**Comment by josiah-wolf-oberholtzer** [comment]
Sorry for the late reply! I'd definitely start with a script that prints out the names of offending classes to terminal. Once you have that, you'll have an idea of the scope of the problem. I honestly don't know how many classes are affected.

Once we know though, we can decide how to go about fixing everything. I'm OK with a large diff, but you might go subpackage-by-subpackage per commit. That may simplify any rebasing other developers have to do against your changes, once they're merged into master.

**Comment by ajyoon** [comment]
~139 files failed checks across dozens of subpackages, mostly in `tools`. Most of the problems are in incorrect header ordering, but there are a fair number of properties in method areas and vice versa as well.

Is now a good time to fix this? If anyone is working on any large commits this may cause some woe.

**Comment by josiah-wolf-oberholtzer** [comment]
Nope, I think it's a fine time. We have relatively few PRs open at the moment. A few will go away soon, and the others are long-standing and require significant work to be brought up-to-date anyways.

Here's a good plan of attack:

1. Submit a PR with the diagnostic script. Put it in `scr/devel`.
2. Open a PR for the actual refactoring. Commit or rebase such that you make one commit per tools package.
3. We'll gauge the impact as the changes roll in.
4. We can merge the entire refactor PR, or cherry-pick per-tools-package commits out into separate PRs.

**Comment by josiah-wolf-oberholtzer** [comment]
Fixed in #760.
