### ISSUE TITLE
Audit path collection in commandline scripts

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#757]
Commandline scripts which recurse over directory trees should handle multiple kinds of input predictably:
- [ ] no input: `ajv my-script`
- [ ] current working directory: `ajv my-script .`
- [ ] home path expansion: `ajv my-script ~/Desktop`
- [ ] directories: `ajv my-script Desktop`
- [ ] files: `ajv my-script foo.txt`
- [ ] multiple paths: `ajv my-script ~/Documents ~/Desktop ~/Pictures foo.txt`

Additionally, files should be sorted to avoid platform specific sort problems.

This path iteration logic should be encapsulated as a method on CommandlineScript and factored into all subclasses when possible.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Moved to Abjad/abjad-ext-cli issue 4.
