### ISSUE TITLE
Change Abjad vimrc file

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#770]
The Abjad vimrc file currently lives in `etc/editors/vimrc`.

The file contains settings to suppress Vim's desire to add an EOL at the end of every file.

Remove those settings. This will allow Vim to add an EOL at the end of every file.

Reason being to avoid EOL at EOF contention between commits.

**Comment by josiah-wolf-oberholtzer** [comment]
@trevorbaca Nice!
