### ISSUE TITLE
Implement "alteration multipliers" against all named pitchtools classes (including abjad.Accidental)

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#777]
There's a gap (in the form of a not-yet-modeled generalization) in `pitchtools` that we should fill.

NAME. A description like "alteration multipliers" might be a good cover term for what's missing.

BACKGROUND:

First, consider that Abjad doesn't yet model double and triple sharps (or flats). Probably the (genealogical) reason for this is that these sorts of "multiple accidentals" arise usually only in tonal contexts (and, above all else, in transposition and modulations between key signatures). But this is a missing generalization in our model: the Abjad `Accidental` class should model sharps and flats that have been doubled or tripled (or, in the general case, "multiplied" any positive number of times); one result will be that a 99-tuple sharp will be possible to initialize and work with just as easily as a vanilla sharp currently is.

Then consider (and this may take a moment of reflection) that the five Named\* `pitchtools` classes should also generalize in this same way. The five Named\* `pitchtools` classes are these:

```
* NamedInterval
* NamedIntervalClass
* NamedInversionEquivalentIntervalClass
* NamedPitch
* NamedPitchClass
```

How do the Named\* `pitchtools` classes relate to `Accidental`?

In the same way that it should be possible to model a triple sharp, so it should also be possible to model a triply diminished eleventh:

```
* triply diminished eleventh (NamedInterval)
* triply diminished descending fourth (NamedIntervalClass)
* triply diminished descending fourth (NamedInversionEquivalentIntervalClass)
* C###5 (NamedPitch: ie, C triple-sharp in the 5th octave)
* C### (NamedPitchClass: ie, C triple-sharp)
```

MODEL: So how to model these sorts of "alteration multipliers"?

Possibly with new properties like these:

```
* Accidental.multiplier
* NamedInterval.quality_multiplier (to accompany existing quality_string property)
* NamedIntervalClass.quality_multiplier (ditto)
* NamedInversionEquivalentIntervalClass.quality_multiplier (ditto)
* NamedPitch.accidental.multiplier (will get for free with Accidental.multiplier)
* NamedPitchClass.accidental.multiplier (ditto)
```

But what to make of the three pairs of `quality_string` and `quality_multiply` that would result on `NamedInterval`, `NamedIntervalClass`, `NamedInversionEquivalentIntervalClass`?

These might suggest a first-class `Quality` class:

```
Quality.name
Quality.multiplier
```

... to give the following interface ...

```
NamedInterval.quality
NamedInterval.quality.name
NamedInterval.quality.multiplier

NamedIntervalClass.quality
NamedIntervalClass.quality.name
NamedIntervalClass.quality.multiplier

NamedInversionEquivalentIntervalClass.quality
NamedInversionEquivalentIntervalClass.quality.name
NamedInversionEquivalentIntervalClass.quality.multiplier
```

... instead.

Ok, that's enough sketching for now. Hopefully will give a starting hold when we begin to generalize.

Final comment: the implementation of these sorts of "alteration multipliers" (or "quality multipliers") is probably a necessary precondition to truly generalizing our (tonal) transposition methods.

**Comment by josiah-wolf-oberholtzer** [comment]
Thought I replied to this, but the comment is gone (?!).

Anyways, see #539 for some initial work on this: an arbitrarily-sharpable accidental and a new "enharmonic" interval class which could be the groundwork for implementing generalized transposition.

**Comment by trevorbaca** [comment]
Awesome. Yeah, the generalized `Accidental` you've got in #779 is great.

Merge that in? And then we can use the extra comments I've supplied here as a type of to-do list for bringing the Named* classes up to snuff with the shiny new Accidental improvements!

All of these are steps towards truly generalized transposition.

**Comment by josiah-wolf-oberholtzer** [comment]
I have an implementation of an arbitrarily-sharpable/flattable accidental
in my josiah/enharmonic-transposition branch. I'll pull that into a PR
branch so you can see it.

It doesn't have any notion of "multiplier", but simply lets you have as
many sharps or flats as you want, plus quarter tone alteration.

Could be a starting point for this work.

**Comment by josiah-wolf-oberholtzer** [comment]
Likewise, that branch sketches out a new interval class that allows
arbitrary diminution and augmentation.

**Comment by trevorbaca** [comment]
Still valid in June 2017.
