### ISSUE TITLE
\oneVoice, \voiceOne etc. ignored when parsing

### ISSUE THREAD

**Issue by sbowa** [Abjad/abjad#780]
\voiceOne etc. will be ignored by the parser
![music_output](https://cloud.githubusercontent.com/assets/23135225/19828714/eff19c56-9dcd-11e6-947e-73b006321a4b.png)

Minimal example:

``` python
from abjad.tools import lilypondparsertools
from abjad import *

parser = lilypondparsertools.LilyPondParser()
string = r'''
{
  \voiceOne c'' d''
  \voiceTwo e''4. c''8 c'4
}
'''
result = parser(string)
show(result)
```

http://abjad.mbrsi.org/api/tools/lilypondparsertools/LilyPondParser.html
claims this would work

**Comment by ajyoon** [comment]
Same on dev branch

**Comment by ajyoon** [comment]
For reference, this is the Lilypond 2.18.2 output on the same excerpt ![lilypond example](https://cloud.githubusercontent.com/assets/15976214/19831639/0f51143c-9ddd-11e6-9bb2-840fef0bf70e.png)

**Comment by josiah-wolf-oberholtzer** [comment]
@sbowa @ajyoon Getting this working is non-trivial. I'll happily accept a patch removing any mention of `\voiceOne` and friends from the documentation.

If anybody feels very brave, there's a long-suffering `josiah/lilypondparser-2.19` branch and accompanying PR #538 that could use some love. Finishing the work in that branch might allow for properly parsing those constructs.

**Comment by josiah-wolf-oberholtzer** [comment]
See #781 for a quick fix.
