### ISSUE TITLE
Removing Stems of notes

### ISSUE THREAD

**Issue by amirteymuri** [Abjad/abjad#782]
How can one write notes without stems? (only noteheads)

**Comment by sbowa** [comment]
```python
from abjad import *

voice = Voice("f' g' a'")
voice.remove_commands.append('Stem_engraver')
show(voice)
```
A similar example can be found here:
http://abjad.mbrsi.org/api/tools/scoretools/Context.html#abjad.tools.scoretools.Context.Context.remove_commands

**Comment by josiah-wolf-oberholtzer** [comment]
@amirteymuri There are a number of ways of hiding stems, as well as beams, flags, dots, etc.

@sbowa pointed out one way. I would use that sparingly, as removing engravers in LilyPond can sometimes lead to undefined behavior.

Given the following staff, here are some ways that I would hide stems in Abjad:

```
>>> staff = Staff("c'4 d'4 e'4 f'4")
```

1. Use `override()` to make a single stem transparent. The shape of the invisible stem will still be taken into account by LilyPond's spacing algorithm:
    
    ```
    >>> staff = Staff("c'4 d'4 e'4 f'4")
    >>> override(staff[1]).stem.transparent = True
    ```

2. Use `override()` to remove a single stem's stencil. It won't be taken into account by LilyPond's spacing algorithm:
    
    ```
    >>> staff = Staff("c'4 d'4 e'4 f'4")
    >>> override(staff[1]).stem.stencil = False
    ```

3. Use `override()` to make all stems in the staff transparent:
    
    ```
    >>> staff = Staff("c'4 d'4 e'4 f'4")
    >>> override(staff).stem.transparent = True
    ```

4. Use `override()` to remove all stem stencils from the staff:
    
    ```
    >>> staff = Staff("c'4 d'4 e'4 f'4")
    >>> override(staff).stem.stencil = False
    ```

5. Use `remove_commands` (like @sbowa showed) to remove the ability to make _any_ stems from the entire `Staff` context:
    
    ```
    >>> staff = Staff("c'4 d'4 e'4 f'4")
    >>> staff.remove_commands.append('Stem_engraver')
    ```

**Comment by josiah-wolf-oberholtzer** [comment]
@amirteymuri If you want to remove beams, flags, dots, etc., use some combination of the following:

```
override(staff).stem.transparent = True
override(staff).beam.transparent = True
override(staff).dots.transparent = True
override(staff).flag.transparent = True
```

If the transparent version causes spacing problems - usually because you don't see the graphic objects spaced as close together as you like - use a `stencil = False` version:

```
override(staff).stem.stencil = False
override(staff).beam.stencil = False
override(staff).dots.stencil = False
override(staff).flag.stencil = False
```

**Comment by amirteymuri** [comment]
@josiah-wolf-oberholtzer Thank you for your reply. Could you also give the link to the override function in the documentation? Can i also use override to remove time / bar signatures from the score?

**Comment by josiah-wolf-oberholtzer** [comment]
@amirteymuri The documentation for Abjad's `override()` is here: http://abjad.mbrsi.org/api/tools/topleveltools/override.html.

It's... a little thin.

Basically, you have to know your way around _LilyPond's_ documentation in order to know how to use Abjad's `override()` function: http://lilypond.org/doc/v2.19/Documentation/internals/stem

You can use `override()` to hide or entirely remove time signatures, as well as most graphic objects you see on the page:

```
override(staff).time_signature.transparent = True
```

```
override(staff).time_signature.stencil = False
```
