### ISSUE TITLE
Crash when running without normal environment variables

### ISSUE THREAD

**Issue by nickswalker** [Abjad/abjad#785]
I am attempting to run an Abjad project on a compute cluster. The first time Abjad is imported, it attempts to write a configuration file to the home directory. Because the cluster environment doesn't have any environment variables set, the script crashes here,
https://github.com/Abjad/abjad/blob/master/abjad/tools/systemtools/Configuration.py#L281

because the path variable is None.

I was able to fix this by specifying $HOME in my environment, but perhaps an error message could be added? Or a safe default could be used?

**Comment by josiah-wolf-oberholtzer** [comment]
@nickswalker Do you have any recommendations for a safe default? My inclination is to use whatever the system's temporary directory is, but I can't vouch for that technique.

Perhaps try the following change, and let me know if it gives you trouble:

```
     @property
     def home_directory(self):
         r'''Gets home directory.
         Returns string.
         '''
         path = (
             os.environ.get('HOME') or
             os.environ.get('HOMEPATH') or
-            os.environ.get('APPDATA')
+            os.environ.get('APPDATA') or 
+            tempfile.gettempdir()
             )
         return os.path.abspath(path)
```

**Comment by nickswalker** [comment]
That works! tempdir is the best solution as far as I can tell, though I'm not familiar enough with the codebase to say that using the temporary directory won't cause problems (it's possible, for instance, that the code assumes permissions which may not hold for tmp).

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not a sysadmin, and this is just a humble notation library. We can take our chances.
