### ISSUE TITLE
svg, png files instead of pdf?

### ISSUE THREAD

**Issue by amirteymuri** [Abjad/abjad#790]
This is a question: is it possible to get file formats other than pdf from abjad as saved file? For example png, svg, ...? These are possible in lilypond, how it work in abjad?

**Comment by josiah-wolf-oberholtzer** [comment]
PNG, yes.

```
>>> from abjad import *
>>> staff = Staff("c'4 d'4 e'4 f'4")
>>> persist(staff).as_png('~/Desktop/foo.png')
````

**Comment by josiah-wolf-oberholtzer** [comment]
@amirteymuri We don't currently have an equivalent SVG output method, but if this is something you have a demand for, I could put it together.

**Comment by ajyoon** [comment]
If you have inkscape installed you can use this small hack to convert pdf to svg:
```python
import subprocess

from abjad import *
staff = Staff("c'4 d'4 e'4 f'4")
persist(staff).as_pdf('tmp.pdf')
subprocess.call(['inkscape',
                 '--without-gui',
                 '--file=tmp.pdf',
                 '--export-plain-svg=foo.svg'])
```

**Comment by amirteymuri** [comment]
Thank you @josiah-wolf-oberholtzer @ajyoon  for your help. I have already found a solution. :+1:

**Comment by iwkse** [comment]
```
>>> from abjad import *
>>> staff = Staff("c'4 d'4 e'4 f'4")
>>> persist(staff).as_png('~/Desktop/foo.png')
```
This works nicely. Now there's a way to define the width/height of the image? I would like to load the image in a GtkImage, so it would be optimal to have it the actual size.
