### ISSUE TITLE
Understanding abjad!

### ISSUE THREAD

**Issue by amirteymuri** [Abjad/abjad#791]
This is getting ridiculous!
How is it possible to draw the Slur() from the last note in the first bar g' to the second note in the second bar (ef')???

import abjad

score = abjad.Score()
klavier = abjad.scoretools.StaffGroup([], context_name="Klavier")
rechts, links = [abjad.Staff() for _ in range(2)]
for staff in (rechts, links):
    klavier.append(staff)
for measure in xrange(2):
    rechts.append(abjad.Measure((3, 4), []))
    links.append(abjad.Measure((3, 4), []))

rechts[0].extend("r4 r g'")
rechts[1].extend("g'4 ef' c'")
abjad.attach(abjad.Tie(), [rechts[0][-1], rechts[1][0]])
abjad.attach(abjad.Slur(), rechts[:])

links[0].extend("r2.")
links[1].append(abjad.Chord("<c' ef'>2."))

score.append(klavier)
abjad.show(score)

**Comment by josiah-wolf-oberholtzer** [comment]
@amirteymuri For these sorts of questions (tutorials, not bug reports), please use the mailing list (https://groups.google.com/forum/#!forum/abjad-user). And please use the code-formatting tools on GitHub so I don't have to guess what your code is supposed to be. I'm guessing this is what your code looks like:

```
import abjad

score = abjad.Score()
klavier = abjad.scoretools.StaffGroup([], context_name="Klavier")
rechts, links = [abjad.Staff() for _ in range(2)]
for staff in (rechts, links):
    klavier.append(staff)

for measure in range(2):
    rechts.append(abjad.Measure((3, 4), []))
    links.append(abjad.Measure((3, 4), []))

rechts[0].extend("r4 r g'")
rechts[1].extend("g'4 ef' c'")
abjad.attach(abjad.Tie(), [rechts[0][-1], rechts[1][0]])
abjad.attach(abjad.Slur(), rechts[:])

links[0].extend("r2.")
links[1].append(abjad.Chord("<c' ef'>2."))

score.append(klavier)
abjad.show(score)
```

If you want to slur across the two `g'4` notes to the `ef'4`, you need to select those three notes. There are a few ways to do it.

You can use `select(...).by_leaf()` to get only the notes, rests and chords into a `Selection` - a special kind of list.

```
>>> leaves = abjad.select(rechts).by_leaf()
>>> print(leaves)
Selection([Rest('r4'), Rest('r4'), Note("g'4"), Note("g'4"), Note("ef'4"), Note("c'4")])
>>> selection = leaves[2:5]
>>> abjad.attach(abjad.Slur(), leaves)
```

Or you could use slice notation, make two slices and then concatenate them:

```
>>> [rechts[0][-1]] + rechts[1][:2]
Selection([Note("g'4"), Note("g'4"), Note("ef'4")])
```

Using `select()` is easier to read and more powerful than slice notation:

```
import abjad

score = abjad.Score()
klavier = abjad.scoretools.StaffGroup([], context_name="Klavier")
rechts, links = [abjad.Staff() for _ in range(2)]
for staff in (rechts, links):
    klavier.append(staff)

for measure in range(2):
    rechts.append(abjad.Measure((3, 4), []))
    links.append(abjad.Measure((3, 4), []))

rechts[0].extend("r4 r g'")
rechts[1].extend("g'4 ef' c'")
abjad.attach(abjad.Tie(), [rechts[0][-1], rechts[1][0]])
abjad.attach(abjad.Slur(), abjad.select(rechts).by_leaf()[2:5])

links[0].extend("r2.")
links[1].append(abjad.Chord("<c' ef'>2."))

score.append(klavier)
abjad.show(score)
```
