### ISSUE TITLE
Remove systemtools.Memoize

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#797]
No one's using Memoize, correct?

Think it entered mainline years back during musicexpressiontools.

**Comment by josiah-wolf-oberholtzer** [comment]
I've never used it. Go ahead!

**Comment by trevorbaca** [comment]
Done 2017-01-16 in a development branch.

Will leave open until PR'ed into main.

**Comment by trevorbaca** [comment]
Done in 2.20.
