### ISSUE TITLE
Use toplevel abjad-pathing for all storage formats

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#798]
The `import abjad` way of doing things really is the cleanest way to go.

Maybe this suggests that ...
```
>>> print(format(maker, 'storage'))
rhythmmakertools.TaleaRhythmMaker(
    talea=rhythmmakertools.Talea(
        counts=(1, 2),
        denominator=16,
        ),
    )
```
... should (by default) be ...
```
>>> print(format(maker, 'storage'))
abjad.rhythmmakertools.TaleaRhythmMaker(
    talea=abjad.rhythmmakertools.Talea(
        counts=(1, 2),
        denominator=16,
        ),
    )
```
... instead.

Two advantages:

1. any storage format will be able to be written to a file that carries only `import abjad` at top, just like new-style composition modules.

2. string evaluation for any storage format becomes trivially easy because only `import abjad` is required to be passed in `eval()` globals.

**Comment by josiah-wolf-oberholtzer** [comment]
Sounds good to me. Will require a lot of doc changes, but it's probably worth it.

**Comment by trevorbaca** [comment]
Great to hear. And yeah I was thinking the same: lots of doc changes but probably ok because we're coalescing on the permanent representation of a lot of things.

I've been making lots of tedious doc changes in the recent development waves. Don't mind doing them when they all point to a solid final result.

**Comment by trevorbaca** [comment]
Mostly done in 2.21!

Just have to decide what constitutes done and close the issue.
