### ISSUE TITLE
Python 3.4 installation issue

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#823]
I have installed Abjad following the advice [on this page](abjad.mbrsi.org/installation.html) but I am having troubles getting it to work with Python 3. I am running Python 3.4.3 on Linux Mint, and according to the installation page Abjad should be compatible with Python 3.3+, so I imagine I am doing something wrong. I installed it via `$ sudo pip install abjad` and I am able to use it with Python 2:

```
gilberto@gilberto-Inspiron-7520 ~ $ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import abjad
>>> abjad.__version__
'2.20'
>>> 
gilberto@gilberto-Inspiron-7520 ~ $ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import abjad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'abjad'
>>> 
```

Would anyone have some advice for me? Many thanks in advance.

**Comment by josiah-wolf-oberholtzer** [comment]
Hi! `pip` only targets one version of Python. For most Linux installations, that means Python 2.x, which is still usually the default. Libraries installed this way for Python 2 aren't available for Python 3 and vice versa.

In order to use `sudo pip install abjad`, you need to use the version of `pip` that targets 3.4. That's probably `pip3` or `pip3.4`:

```sudo pip3.4 install abjad```

**Comment by gilbertohasnofb** [comment]
@josiah-wolf-oberholtzer Hi Josiah, thanks for the quick reply! Using `pip3` does indeed solve my installation problems, thanks a lot for the help. I am quite new to Python (I am considering migrating to it exactly because of Abjad), and so I didn't know that `pip` targets only the default version of Python. Many thanks!
