### ISSUE TITLE
Disambiguate datastructuretools.Enumeration, sequencetools.Enumeration

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#837]

**Comment by trevorbaca** [comment]
Leave `datastructuretools.Enumeration` as is.

Change `sequencetools.Enumeration` to `sequencetools.Enumerator`.

**Comment by josiah-wolf-oberholtzer** [comment]
Yes, please leave `datastructuretools.Enumeration` as-is. That class is a convenience wrapper around Python's `enum.IntEnum` and friends, and I'm using it extensively.

**Comment by trevorbaca** [comment]
Done in 2.21:
```
>>> abjad.Enumeration
<enum 'Enumeration'>

>>> abjad.Enumerator
<class 'abjad.tools.sequencetools.Enumerator.Enumerator'>
```
