### ISSUE TITLE
Change abjad.set_() to abjad.setting()

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#841]
Trailing underscore still not fully supported by doc system.

Breaking change but can be included in 2.21 together with `inspect_()` -> `inspect()` breaking change at the same time.

Users will read `abjad.override()`, `abjad.setting()` as nouns (but in parallel).

**Comment by josiah-wolf-oberholtzer** [comment]
Yes, please, do this.

**Comment by trevorbaca** [comment]
Done in 2.21.
