### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by smoge** [Abjad/abjad#875]
```
import abjad

fragment = r'''
dis''16[
dih''8
dih'128
fih'64.
fisih''128
gis'64
fisih''128
eih''16

\times 8/9 {
e'64
gisih'64
gisih'128
dis'64.
fis''128]
}
'''


parser = abjad.lilypondparsertools.LilyPondParser('nederlands')
staff = parser(fragment)

# 
# ---------------------------------------------------------------------------
# LilyPondParserError                       Traceback (most recent call last)
# <ipython-input-35-aac756577b71> in <module>()
# ----> 1 staff = parser(fragment)
# 
# /usr/local/lib/python3.6/site-packages/abjad/tools/lilypondparsertools/LilyPondParser.py in __call__(self, input_string)
#     370             result = self._parser._lilypond_patch_parse(
#     371                 input_string,
# --> 372                 lexer=self._lexer,
#     373                 )
#     374         if isinstance(result, scoretools.Container):
# 
# /usr/local/lib/python3.6/site-packages/abjad/tools/lilypondparsertools/_parse.py in _parse(self, input, lexer, debug, tracking, tokenfunc)
#     246                     if errtoken and not hasattr(errtoken,'lexer'):
#     247                         errtoken.lexer = lexer
# --> 248                     tok = self.errorfunc(errtoken)
#     249                     del errok, token, restart   # Delete special functions
#     250 
# 
# /usr/local/lib/python3.6/site-packages/abjad/tools/lilypondparsertools/LilyPondSyntacticalDefinition.py in p_error(self, p)
#    3350     def p_error(self, p):
#    3351         #print p
# -> 3352         raise LilyPondParserError(p)
# 
# LilyPondParserError: LexToken(NOTENAME_PITCH,NamedPitchClass('ds'),1,1)
# 

```

**Comment by josiah-wolf-oberholtzer** [comment]
Hi Bernardo, you need to provide valid LilyPond input.

The LilyPond fragment you've provided won't compile in LilyPond itself (not counting the missing `\version ...`) command because the note syntax is not valid as a top-level expression in the grammar.

Wrap it in curly braces to create a music expression and it will compile. Additionally, curly braces alone will return a bare Abjad `Container` object, so I've added the `\new Staff { ... }` syntax to return the class I think you expect:

```
import abjad

fragment = r"""
\new Staff {
    dis''16 [
    dih''8
    dih'128
    fih'64.
    fisih''128
    gis'64
    fisih''128
    eih''16
    \times 8/9 {
        e'64
        gisih'64
        gisih'128
        dis'64.
        fis''128 ]
    }
}
"""

parser = abjad.lilypondparsertools.LilyPondParser('nederlands')
staff = parser(fragment)
```

```
>>> container = parser(fragment)
>>> print(format(container))
{
    ds''16
    dqs''8
    dqs'128
    fqs'64.
    ftqs''128
    gs'64
    ftqs''128
    eqs''16
    \times 8/9 {
        e'64
        gtqs'64
        gtqs'128
        ds'64.
        fs''128
    }
}
```

We typically don't use the `LilyPondParser` class directly, but pass the string to be parsed directly to a container constructor (e.g. `staff = Staff(fragment)`) - where the extra curly braces are optional, however Abjad assumes English note names in that case. Abjad will also always output LilyPond syntax with the English note names.

**Comment by smoge** [comment]
I must be blind, sorry. 

I did this way trying to import with materials with Dutch note names and didn't see I misplaced the curly bracket. 

I'll try to use English, but I have old materials with Dutch names. Those abjad classes (Measure, Staff, &c) are capable of parse another language? 

Thank you.

**Comment by josiah-wolf-oberholtzer** [comment]
No worries!

Those classes can parse anything the LilyPondParser can parse - they _basically_ create their own instance of the parser to use when given string input -, but they do not provide a way to select a different language than English. There's also no way in Abjad at the moment to specify that a given language is the default for all parser usage.

However, you can just toss a `\language nederlands` command in there to trigger the parsing you want:

```
>>> import abjad
>>> staff = abjad.Staff(r"\language nederlands cis'4 dis'4 ees'4 fes'4")
>>> print(format(staff))
\new Staff {
    cs'4
    ds'4
    ef'4
    ff'4
}
```
