### ISSUE TITLE
doesn't remember input argument Hertz

### ISSUE THREAD

**Issue by uummoo** [Abjad/abjad#877]
If I make a new `NamedPitch`-object via the awesome `from_hertz`-method, the created object won't remember my input number, but will immediately round it to the closest frequency in the 24-equal divided octave-tuning:

```python
import abjad
my_pitch = abjad.NamedPitch.from_hertz(200)
print(my_pitch.hertz)
```

> 195.99771799087463

Since abjad seems not to be only meant for a notation purpose, but also for composition, I wonder why the NamedPitch-object doesn't save the input Hertz-Number and just transforms it, when it is asked for the pitches name.

**Comment by josiah-wolf-oberholtzer** [comment]
Abjad is primarily concerned with working inside a 24ET pitch space. The `from_hertz()` method is provided as a convenience for coercing Hz into notatable pitches, nothing more, and makes no guarantees about maintaining the original Hz input.
