### ISSUE TITLE
Replace many assert statements with if {X}: raise {Y}Error constructs

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#879]
We've done well for ourselves with bare `assert` statements throughout the codebase, but our users will be better served by raising more specifically worded errors.

One realization is that Python allows `assert` to be _deactivated_ entirely via the `-O` flag. While unlikely in our normal usage, it does suggest that `assert` isn't the correct choice for signally incorrect input or behavior.

Note that this is not a suggestion for inventing new exception classes. The standard `ValueError`, `TypeError`, `KeyError`, `AttributeError`, `IndexError` classes (and perhaps a few more) are perfectly suitable for 99% of Abjad's error reporting use cases.

**Comment by trevorbaca** [comment]
Agreed completely.

And I suspect that we'll be helped in this process when we begin integrating type annotations (given that so much of our usage of `assert` has basically been a type of method-initial proxy for type checking).

**Comment by trevorbaca** [comment]
The built-in `TypeError`, `ValueError` etc won't really provide anything more to users.

What's really required is a much more verbose system of error messaging, mostly in the form of descriptive error message strings that point to the exact point in the system at which the error is raised. Closing this one for now; verbose erroring can be treated as its own dedicated project when the time comes.
