### ISSUE TITLE
Disambiguate abjad.Context.context_name and abjad.Context.name

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#895]
These two property names have long confounded some of the most intricate parts of the Abjad source: everything having to do with context resolution, especially surrounding `abjad.IndicatorWrapper`.

Consider the LilyPond invocation ...
```
\context ViolinStaff = "MyViolinStaff" { ... }
```
... in which ...

* the purpose of `abjad.Context.context_name` is to model `ViolinStaff`
* the purpose of `abjad.Context.name` is to model `MyViolinStaff`

The problem has been that both `ViolinStaff` and `MyViolinStaff` are clearly names, hence the current clash between `context_name` and `name`. (Appealing to a class / instance distinction here clashes with Python classes / objects in the rest of the code.)

I think we'll leave `abjad.Context.name` as is and change `abjad.Context.context_name` to `abjad.Context.headword`, recalling that "headword" is the name used to look up an entry in a dictionary. The primary advantage here not being the fit of the metaphor but disambiguation between the two properties.

**Comment by josiah-wolf-oberholtzer** [comment]
For what it's worth, LilyPond documentation uses "type" to describe how one kind of context is different from another (e.g. `Voice` vs `Staff`).

http://lilypond.org/doc/v2.18/Documentation/notation/changing-context-default-settings#changing-all-contexts-of-the-same-type

**Comment by trevorbaca** [comment]
Great suggestion: we'll go with `abjad.Context.lilypond_type` (as the replacement for `abjad.Context.context_name`).

The `abjad.Context.name` property will stay as-is.
