### ISSUE TITLE
Port Ligeti example forward

### ISSUE THREAD

**Issue by mrtnmgs** [Abjad/abjad#896]
The [Ligeti example](http://abjad.mbrsi.org/literature_examples/ligeti.html) mentions defining a function, and then goes on to using it but the part explaining the function definition seems to be missing. Same thing later on with `ligeti.make_desordre_staff` and `ligeti.make_desordre_score`

**Comment by josiah-wolf-oberholtzer** [comment]
@mrtnmgs Thanks for the report. This is definitely a broken example.

The functions mentioned are defined in `abjad.demos.ligeti`, but aren't included here for some reason.

**Comment by trevorbaca** [comment]
Fixed. Merging into mainline. Will be included in Abjad 3.1 build.
