### ISSUE TITLE
Clean up Abjad's internal package structure.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#898]
This issue acts as a staging area for proposing radical reorganizations of Abjad internal package structure, including merging and removing subpackages.

@kureta Feel free to suggest structures here!

**Comment by josiah-wolf-oberholtzer** [comment]
First, which packages are going to be externalized from the current Abjad structure?

As of this writing, we have the following tools packages:

```
abctools/
abjadbooktools/
commandlinetools/
datastructuretools/
documentationtools/
exceptiontools/
graphtools/
indicatortools/
instrumenttools/
lilypondfiletools/
lilypondnametools/
lilypondparsertools/
markuptools/
mathtools/
metertools/
pitchtools/
quantizationtools/
rhythmmakertools/
rhythmtreetools/
schemetools/
scoretools/
segmenttools/
spannertools/
systemtools/
timespantools/
tonalanalysistools/
topleveltools/
```

These packages will definitely or probably be removed before releasing Abjad 3.0:

```
abjadbooktools/
commandlinetools/
documentationtools/
graphtools/
quantizationtools/
rhythmtreetools/
segmenttools/
tonalanalysistools/
```

That leaves the following packages to be reorganized:

```
abctools/
datastructuretools/
exceptiontools/
indicatortools/
instrumenttools/
lilypondfiletools/
lilypondnametools/
lilypondparsertools/
markuptools/
mathtools/
metertools/ (could maybe be removed)
pitchtools/
rhythmmakertools/ (could maybe be removed)
schemetools/
scoretools/
spannertools/
systemtools/
timespantools/
topleveltools/
```

**Comment by trevorbaca** [comment]
- [ ] flatten the `abjad/tools/` directory

**Comment by trevorbaca** [comment]
- [ ] abjad/markup -> markups.py
- [ ] abjad/scheme -> scheme.py

**Comment by trevorbaca** [comment]
Abjad 3.1 dramatically cleans up Abjad's package structure.

Closing for now because a definition of done was never possible with this thread; can reopen anytime significant package restructuring takes place again.
