### ISSUE TITLE
save_pdf_as and Output or Input Encoding

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [Abjad/abjad#913]
I'm running Abjad with Python 3.6 on Windows 7. I'm interested to know about the IO options that `ly.systemtools` provides. I'm pleased to see that I can control where final files go via `ly.systemtools.IOManager.save_last_pdf_as()`. However, this function fails on Windows.

I'm getting the following error (stack trace shown to show that it's trying to decode CP1252, not Unicode):

```
Traceback (most recent call last):
  File "C:/Users/ssimo3/PycharmProjects/buehler_grande_sonate/abjad_test.py", line 11, in <module>
    IOManager.save_last_pdf_as("test.pdf")
  File "C:\Users\ssimo3\AppData\Roaming\Python\Python36\site-packages\abjad\tools\systemtools\IOManager.py", line 698, in save_last_pdf_as
    new.write(''.join(old.readlines()))
  File "D:\Anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 12: character maps to <undefined>
```
The current version of /tools/systemtools/IOManager.py, lines 762 and 763 (I believe) read:

```
with open(file_path, 'w') as new:
     with open(last_pdf_full_name, 'r') as old:
```

Windows automatically guesses that the encoding is CP1252. Actually the output PDF does contain some ANSI-encoded text, of which CP1252 is the Basic Latin version, but it also contains some custom-encoded text. Which begs the question: Why isn't Abjad specifying that all PDFs should be written and read in UTF-8 on _all_ operating systems? Making sure you are always encoding and decoding in the same format will save you tons of headaches.

**Comment by josiah-wolf-oberholtzer** [comment]
Hi, feel free to submit a PR to correct this. None of the Abjad developers use Windows, so we've never run across this problem.

**Comment by trevorbaca** [comment]
@ssimo3lsuhsc Good point; I'd run into this once or twice, too, even under OSX.

Those lines in `abjad.IOManager.sav_last_pdf_as()` now look like this:
```
        with open(file_path, "w") as new:
            with open(last_pdf_full_name, "r", encoding="ISO-8859-1") as old:
                new.write("".join(old.readlines()))
```

Don't remember when I made the change; some months back.
