### ISSUE TITLE
Impossible to make MultimeasureRest with un-assignable duration

### ISSUE THREAD

**Issue by markk** [Abjad/abjad#982]
It should be possible to make a MultimeasureRest in any TimeSignature. 

```
>>> mmr = abjad.MultimeasureRest((5, 8))
...
AssignabilityError: not assignable duration: Duration(5, 8).
```
It looks like a MultimeasureRest should be initialised as a Duration rather than as a Rest, and then formatted as `"R1*%s/%s" % (self.numerator, self.denominator)`.

**Comment by trevorbaca** [comment]
Hi Mark,

Use `abjad.Multiplier` objects for this; they work great:
```
>>> mmr = abjad.MultimeasureRest(1)
>>> multiplier = abjad.Multiplier(5, 8)
>>> abjad.attach(multiplier, mmr)

>>> abjad.f(mmr)
R1 * 5/8
```
This attach-a-multiplier-directly-to-a-leaf feature is very much underdocumented in the system; apologies for this.

Happily, though, knowing about this feature gives you a generalized way of setting LilyPond duration multipliers on **all** Abjad leaves:
```
>>> note = abjad.Note("c'4")
>>> multiplier = abjad.Multiplier(5, 8)
>>> abjad.attach(multiplier, note)

>>> abjad.f(note)
c'4 * 5/8
```
(This last example provides a very clean way of handling certain cases of duration-faking in polyphonic writing, which I'm sure you'll need in your piano writing.)

The key to this feature is that multipliers may be set to any rational value (and are not constrained by assignability).

And one last obscure-but-potentially-quite-clean feature: you can attach `abjad.NonreducedFraction` objects directly to leaves, too:
```
note = abjad.Note("c'4")
multiplier = abjad.NonreducedFraction(10, 16)
abjad.attach(multiplier, note)

abjad.f(note)
c'4 * 10/16
```
In the resulting LilyPond output (just above) note that numerator and denominator of the fraction are preserved exactly as initialized (that is, *not* reduced to relative primes). The graphic output (in Lily's PDF) of course looks identical to your original example with the 5/8 multiplier. But you can use `abjad.NonreducedFraction` objects when you want to preserve a series of multiplier denominators exactly as-is (usually for purposes of debugging your .ly source file): 10/16 ... 11/16 ... 12/16 is usually easier to read that 5/8 ... 11/16 ... 3/4 if the multipliers all participate in the same underlying prolation.

Also, great to see you on the Abjad list. I hope a good number of the tools will be genuinely useful for you.

Tag @markk

**Comment by markk** [comment]
OK, got it, thanks Trevor. I'm still getting into thinking in Abjad - not quite sure how much I can work abstractly and leave Abjad to deal with the LilyPond implementation details, and how much I need to think about the .ly source I want to produce.

**Comment by trevorbaca** [comment]
Totally. You know a tremendous amount about LilyPond formatting already (from reading your threads on the LilyPond list). That knowledge can help quite a bit in working with Abjad. So in your case my best advice would be to continue to think "what will Abjad produce as the resulting LilyPond source?" each step of the way. (Making liberal use of `abjad.f()` can really help in that respect.)

I suspect that you'll get pretty quickly a to point where you can (if you want) ignore the LilyPond output Abjad is creating, and just "think in Abjad." But there will always be moments where you'll want to go look at the (potentially 10,000-line) .ly files Abjad creates; so keeping your LilyPond knowledge in mind while working with Abjad is definitely recommended.
